### ISSUE TITLE
System.NotImplementedException: The method or operation is not implemented.

### ISSUE THREAD

**Issue by cengizhan** [RandomEngy/VidCoder#1008]
### What were you doing when VidCoder crashed?

nothing. just started the application

### Crash details

```text
VidCoder 7.14 Zip
System.NotImplementedException: The method or operation is not implemented.
   at MS.Internal.AppModel.ITaskbarList.HrInit()
   at System.Windows.Window.ApplyTaskbarItemInfo()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by RandomEngy** [comment]
This issue has [cropped up before](https://github.com/RandomEngy/VidCoder/issues/673). Are you using Remote Desktop? Does the installer or Portable version also throw an exception?

**Comment by cengizhan** [comment]
no remote desktop. i am using zip version not the portable one. i have used portable for a long time. i don't remember something like this. with second startup, this bug did not show up.

**Comment by RandomEngy** [comment]
Hmm okay. Going to chalk this one up to a WPF bug; I don't think there's anything I can do to fix it. Thanks for reporting.
