### ISSUE TITLE
Enqueue Multiple Files Not Working

### ISSUE THREAD

**Issue by mikeharvat** [RandomEngy/VidCoder#1011]
### Problem Description

Hello! I'm not sure when it started, but for the past several versions of Vidcoder, I have been unable to use the "Enqueue Multiple Files" option. I'm able to click on it, select the files, and it even scans them....but then nothing gets added to the queue.

Is this a known issue? I searched and couldn't find anything from anyone else. Out of curiosity, I tried uninstalling and re-installing the program, and it still doesn't work.

I have used Vidcoder for many years and find it very useful. Most recently, I am using it to convert the videos I make for my guitar students to a small size so I can share them quickly and my students can stream them easily. As it stands, I am now "opening" the files and then adding them to the queue one by one.

### What version of VidCoder are you running?

7.14

**Comment by RandomEngy** [comment]
Glad you've been finding it useful! I like hearing what people are using it for.

What does it say under the scan entries in the Log window? Does anything show up under the General entry at the top?

**Comment by mikeharvat** [comment]
Hello, sorry for the delay! So interestingly...today it worked. I want to be helpful, though, so I went digging and found the log of the most recent failure. Maybe you can make sense of it:

# VidCoder 7.14
# Update download failed.
System.Net.Http.HttpRequestException: No such host is known. (f001.backblazeb2.com:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at Squirrel.HttpClientFileDownloader.DownloadString(String url, String authorization) in ./FileDownloader.cs:line 90
   at Squirrel.UpdateManager.CheckForUpdateImpl.CheckForUpdate(UpdaterIntention intention, String localReleaseFile, String updateUrlOrPath, Boolean ignoreDeltaUpdates, Action`1 progress, IFileDownloader urlDownloader) in ./UpdateManager.CheckForUpdates.cs:line 80
   at Squirrel.UpdateManager.CheckForUpdate(Boolean ignoreDeltaUpdates, Action`1 progress, UpdaterIntention intention) in ./UpdateManager.cs:line 92
   at Squirrel.Utility.LogIfThrows[T](IFullLogger This, LogLevel level, String message, Func`1 block) in ./Internal/Utility.cs:line 659
   at Squirrel.EasyModeMixin.UpdateApp(IUpdateManager This, Action`1 progress) in ./IUpdateManager.cs:line 221
   at VidCoder.Services.Updater.StartBackgroundUpdate(Boolean isManualCheck)
# Worker ready: Pipe 'VidCoderWorker.1f6d0b98-bdf8-4299-b6d7-9afe6f90a3af' is open
# Connecting to process 5620 on pipe VidCoderWorker.1f6d0b98-bdf8-4299-b6d7-9afe6f90a3af
[12:17:19] CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
[12:17:19]  - Intel microarchitecture Kaby Lake
[12:17:19]  - logical processor count: 8
[12:17:19] Intel Quick Sync Video support: yes, gpu list: 0, 1
[12:17:19] Intel Quick Sync Video integrated adapter with index 0
[12:17:19]  - Intel Media SDK hardware: API 1.33 (minimum: 1.3)
[12:17:19]  - Decode support:  h264 hevc (8bit: yes, 10bit: yes)
[12:17:19]  - H.264 encoder: yes
[12:17:19]     - preferred implementation: hardware (1) via D3D11
[12:17:19]     - capabilities (hardware):  breftype icq+la+i+downs vsinfo opt1 opt2+mbbrc+extbrc+trellis+ib_adapt+nmpslice
[12:17:19]  - H.265 encoder: yes (8bit: yes, 10bit: yes)
[12:17:19]     - preferred implementation: hardware (1) via D3D11
[12:17:19]     - capabilities (hardware):  bpyramid icq vsinfo opt1
[12:17:19] Intel Quick Sync Video integrated adapter with index 1
[12:17:19]  - Intel Media SDK hardware: API 1.33 (minimum: 1.3)
[12:17:19]  - Decode support:  h264 hevc (8bit: yes, 10bit: yes)
[12:17:19]  - H.264 encoder: yes
[12:17:19]     - preferred implementation: hardware (2) via D3D11
[12:17:19]     - capabilities (hardware):  breftype icq+la+i+downs vsinfo opt1 opt2+mbbrc+extbrc+trellis+ib_adapt+nmpslice
[12:17:19]  - H.265 encoder: yes (8bit: yes, 10bit: yes)
[12:17:19]     - preferred implementation: hardware (2) via D3D11
[12:17:19]     - capabilities (hardware):  bpyramid icq vsinfo opt1
[12:17:19] hb_scan: path=C:\Users\Mike\Videos\Build My Life Playthrough.mp4, title_index=0
udfread ERROR: ECMA 167 Volume Recognition failed
src/libbluray/disc/disc.c:333: failed opening UDF image C:\Users\Mike\Videos\Build My Life Playthrough.mp4
src/libbluray/disc/disc.c:437: error opening file BDMV\index.bdmv
src/libbluray/disc/disc.c:437: error opening file BDMV\BACKUP\index.bdmv
src/libbluray/bluray.c:2646: nav_get_title_list(C:\Users\Mike\Videos\Build My Life Playthrough.mp4\) failed
[12:17:19] bd: not a bd - trying as a stream/file instead
libdvdread: DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdnav: vm: vm: failed to read VIDEO_TS.IFO
[12:17:19] dvd: not a dvd - trying as a stream/file instead
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\Mike\Videos\Build My Life Playthrough.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.76.100
  Duration: 00:06:11.78, start: 0.000000, bitrate: 43611 kb/s
  Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 43413 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 191 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
      title           : simple_aac_recording
[12:17:19] scan: decoding previews for title 1
[12:17:19] scan: audio 0x1: aac, rate=44100Hz, bitrate=191998 Unknown (AAC LC) (2.0 ch) (191 kbps)
[12:17:20] scan: 10 previews, 1920x1080, 30.000 fps, autocrop = 0/0/0/0, aspect 16:9, PAR 1:1, color profile: 1-1-1, chroma location: left
[12:17:20] scan: supported video decoders: avcodec qsv
[12:17:20] libhb: scan thread found 1 valid title(s)
[12:17:20] hb_init: starting libhb thread
[12:17:20] CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
[12:17:20]  - Intel microarchitecture Kaby Lake
[12:17:20]  - logical processor count: 8
[12:17:20] Intel Quick Sync Video support: yes, gpu list: 0, 1
[12:17:20] Intel Quick Sync Video integrated adapter with index 0
[12:17:20]  - Intel Media SDK hardware: API 1.33 (minimum: 1.3)
[12:17:20]  - Decode support:  h264 hevc (8bit: yes, 10bit: yes)
[12:17:20]  - H.264 encoder: yes
[12:17:20]     - preferred implementation: hardware (1) via D3D11
[12:17:20]     - capabilities (hardware):  breftype icq+la+i+downs vsinfo opt1 opt2+mbbrc+extbrc+trellis+ib_adapt+nmpslice
[12:17:20]  - H.265 encoder: yes (8bit: yes, 10bit: yes)
[12:17:20]     - preferred implementation: hardware (1) via D3D11
[12:17:20]     - capabilities (hardware):  bpyramid icq vsinfo opt1
[12:17:20] Intel Quick Sync Video integrated adapter with index 1
[12:17:20]  - Intel Media SDK hardware: API 1.33 (minimum: 1.3)
[12:17:20]  - Decode support:  h264 hevc (8bit: yes, 10bit: yes)
[12:17:20]  - H.264 encoder: yes
[12:17:20]     - preferred implementation: hardware (2) via D3D11
[12:17:20]     - capabilities (hardware):  breftype icq+la+i+downs vsinfo opt1 opt2+mbbrc+extbrc+trellis+ib_adapt+nmpslice
[12:17:20]  - H.265 encoder: yes (8bit: yes, 10bit: yes)
[12:17:20]     - preferred implementation: hardware (2) via D3D11
[12:17:20]     - capabilities (hardware):  bpyramid icq vsinfo opt1
[12:17:20] hb_scan: path=C:\Users\Mike\Videos\Build My Life Review.mp4, title_index=0
udfread ERROR: ECMA 167 Volume Recognition failed
src/libbluray/disc/disc.c:333: failed opening UDF image C:\Users\Mike\Videos\Build My Life Review.mp4
src/libbluray/disc/disc.c:437: error opening file BDMV\index.bdmv
src/libbluray/disc/disc.c:437: error opening file BDMV\BACKUP\index.bdmv
src/libbluray/bluray.c:2646: nav_get_title_list(C:\Users\Mike\Videos\Build My Life Review.mp4\) failed
[12:17:20] bd: not a bd - trying as a stream/file instead
libdvdread: DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdnav: vm: vm: failed to read VIDEO_TS.IFO
[12:17:20] dvd: not a dvd - trying as a stream/file instead
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'C:\Users\Mike\Videos\Build My Life Review.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.76.100
  Duration: 00:03:42.70, start: 0.000000, bitrate: 45341 kb/s
  Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(tv, bt709), 1920x1080 [SAR 1:1 DAR 16:9], 45143 kb/s, 30 fps, 30 tbr, 15360 tbn, 60 tbc (default)
    Metadata:
      handler_name    : VideoHandler
      vendor_id       : [0][0][0][0]
  Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 192 kb/s (default)
    Metadata:
      handler_name    : SoundHandler
      vendor_id       : [0][0][0][0]
      title           : simple_aac_recording
[12:17:20] scan: decoding previews for title 1
[12:17:20] scan: audio 0x1: aac, rate=44100Hz, bitrate=192000 Unknown (AAC LC) (2.0 ch) (192 kbps)
[12:17:21] scan: 10 previews, 1920x1080, 30.000 fps, autocrop = 0/0/0/0, aspect 16:9, PAR 1:1, color profile: 1-1-1, chroma location: left
[12:17:21] scan: supported video decoders: avcodec qsv
[12:17:21] libhb: scan thread found 1 valid title(s)

**Comment by RandomEngy** [comment]
Do you happen to have this setting enabled in your Picker window?

![image](https://user-images.githubusercontent.com/9450861/167080109-5fbeb080-8de3-4db6-aafc-a1c227da9b29.png)

**Comment by mikeharvat** [comment]
Oh man, that must be it! I had no clue that the picker would influence a mass add like that. I figured the "enqueue multiple files" function would simply add any of the files I select, regardless of the picker's current settings. I definitely changed the settings between the last unsuccessful attempt and the one that worked, so I'm confident that you sniffed out the issue.

My bad! Thanks for your help :)
