### ISSUE TITLE
System.NotImplementedException: The method or operation is not implemented.

### ISSUE THREAD

**Issue by razoarmani** [RandomEngy/VidCoder#1012]
### What were you doing when VidCoder crashed?

Trying to install the application

### Crash details

```text
VidCoder 7.14 SquirrelInstaller
System.NotImplementedException: The method or operation is not implemented.
   at MS.Internal.AppModel.ITaskbarList.HrInit()
   at System.Windows.Window.ApplyTaskbarItemInfo()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by razoarmani** [comment]
I figured out the issue... I get this error when I have my taskbar hidden, I am using [Cairo](https://cairoshell.com) to modify my desktop look, Cairo hides the windows taskbar by default. Once I close the Cairo app and restore the original taskbar, I can install VidCoder fine... hope this helps

**Comment by RandomEngy** [comment]
Thanks for the report. This is due to a WPF platform bug and unfortunately, I cannot catch the exception. Hopefully they will fix the issue.

**Comment by RandomEngy** [comment]
https://github.com/dotnet/wpf/pull/6547

They've fixed it, will eventually pick this up in a .NET update.
