### ISSUE TITLE
VidCoder 5.21 Exception on Windows 8.1 Pro x64 during H.265 encode

### ISSUE THREAD

**Issue by JNavas2** [RandomEngy/VidCoder#1022]
```
System.ArgumentNullException: Value cannot be null.
Parameter name: container
   at System.Windows.Controls.ItemContainerGenerator.IndexFromContainer(DependencyObject container, Boolean returnLocalIndex)
   at Fluent.RibbonTabControl.OnKeyDown(KeyEventArgs e) in C:\projects\fluent-ribbon\Fluent.Ribbon\Controls\RibbonTabControl.cs:line 526
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by RandomEngy** [comment]
Thanks for the report. I'll update the Fluent Ribbon library in case they've made a fix for this. If it still happens, I'll report the issue to them.

**Comment by JNavas2** [comment]
Thank you.
I restarted the encoding job and it completed successfully, so it's not related to the source file or options.
As best I can recall, the exception occurred when I accidentally clicked somewhere on the window.

**Comment by RandomEngy** [comment]
I just realized you are on a really old version of VidCoder. You would need to upgrade to Windows 10/11 and download VidCoder v7 to test out any potential fix.

**Comment by JNavas2** [comment]
Thank you, but I have no desire to jump out of the frying pan into the fire, especially over such a minor issue.

If I were to change anything, it would be the app rather than the platform. 

![WOvMUO3](https://user-images.githubusercontent.com/14850792/168496239-526f719e-184b-4ce8-a320-a1d22af54f11.jpg)

**Comment by JNavas2** [comment]
> My bad I looked up Windows 8 instead of 8.1. You do you.

Windows 8 is a painful kludge that should not have been released.
