### ISSUE TITLE
System.InvalidOperationException: Database too old

### ISSUE THREAD

**Issue by schernic** [RandomEngy/VidCoder#1048]
### What were you doing when VidCoder crashed?

Starting it for the first time

### Crash details

```text
VidCoder 7.15 SquirrelInstaller
System.InvalidOperationException: Database too old
   at VidCoder.Model.Database.Initialize()
   at VidCoder.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by schernic** [comment]
Same with portable and beta versions.

VidCoder Beta 8.5 Portable
System.InvalidOperationException: Database too old
   at VidCoder.Model.Database.Initialize() in C:\git\VidCoder\VidCoder\Model\Database.cs:line 56
   at VidCoder.App.OnStartup(StartupEventArgs e) in C:\git\VidCoder\VidCoder\App.xaml.cs:line 133
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
This happens when you have a really old version of VidCoder and it doesn't support a direct upgrade of the database file. If you want to keep your old settings you can run an older version once to an intermediate upgrade.

Or you can delete %appdata%\VidCoder-Beta\VidCoder.sqlite to start fresh.

**Comment by schernic** [comment]
Deleting my VidCoder.sqlite from 2011 helped. Thanks a lot. 
If I may suggest something, you could use your answer as exception message.
