### ISSUE TITLE
System.Data.SQLite.SQLiteException: database or disk is fulldatabase or disk is full

### ISSUE THREAD

**Issue by ddf2600** [RandomEngy/VidCoder#1054]
### What were you doing when VidCoder crashed?

打开就提示需要提交错误，之前在转换视频， 一共100个左右，90G大小

### Crash details

```text
VidCoder 8.5 Beta Portable
code = Full (13), message = System.Data.SQLite.SQLiteException (0x800007FF): database or disk is full
database or disk is full
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at VidCoder.Model.DatabaseConfig.SetInternal(String configName, String configValue, SQLiteConnection connection) in C:\git\VidCoder\VidCoder\Model\DatabaseConfig.cs:line 156
   at VidCoder.Model.DatabaseConfig.Set[T](String configName, T value, SQLiteConnection connection) in C:\git\VidCoder\VidCoder\Model\DatabaseConfig.cs:line 102
   at VidCoder.Config.Set[T](String key, T value) in C:\git\VidCoder\VidCoder\Model\Config\Config.cs:line 143
   at VidCoder.Config.set_VideoExpanded(Boolean value) in C:\git\VidCoder\VidCoder\Model\Config\Config.cs:line 344
   at VidCoder.ViewModel.MainViewModel.set_VideoExpanded(Boolean value) in C:\git\VidCoder\VidCoder\ViewModel\MainViewModel.cs:line 1228
   at VidCoder.ViewModel.MainViewModel..ctor() in C:\git\VidCoder\VidCoder\ViewModel\MainViewModel.cs:line 69
   at VidCoder.App.OnStartup(StartupEventArgs e) in C:\git\VidCoder\VidCoder\App.xaml.cs:line 166
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by RandomEngy** [comment]
Looks like your hard drive is full.
