### ISSUE TITLE
System.IO.IOException: The device is not ready. : 'E:\'

### ISSUE THREAD

**Issue by ROBERTSpa** [RandomEngy/VidCoder#1055]
### What were you doing when VidCoder crashed?

 Open source
Scan disc
crash!

### Crash details

```text
VidCoder 7.15 SquirrelInstaller
System.IO.IOException: The device is not ready. : 'E:\'
   at System.IO.DriveInfo.get_VolumeLabel()
   at VidCoder.Services.DriveService.GetDiscInformation()
   at VidCoder.ViewModel.MainViewModel.UpdateDriveCollection()
   at VidCoder.Services.DriveService.<HandleDiscEvent>b__3_0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by RandomEngy** [comment]
Fixed in 8.9 Beta.
