### ISSUE TITLE
ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.

### ISSUE THREAD

**Issue by Jigsaw289** [RandomEngy/VidCoder#1060]
### What were you doing when VidCoder crashed?

When I click on Crowse to find the directory I want to set as my folder to send my encoded file to I get the below error. Ive tried to uninstall and reinstall but same error.

### Crash details

```text
VidCoder 7.15 SquirrelInstaller
ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
 ---> System.ArgumentException: Value does not fall within the expected range.
   at MS.Internal.Interop.HRESULT.ThrowIfFailed()
   at MS.Internal.AppModel.ShellUtil.GetShellItemForPath(String path)
   at Microsoft.Win32.FileDialog.PrepareVistaDialog(IFileDialog dialog)
   at Microsoft.Win32.FileDialog.RunVistaDialog(IntPtr hwndOwner)
   at Microsoft.Win32.FileDialog.RunDialog(IntPtr hwndOwner)
   at Microsoft.Win32.CommonDialog.ShowDialog()
   at VidCoder.Services.FileService.GetFileNameSave(String initialDirectory, String title, String initialFileName, String defaultExt, String filter)
   at VidCoder.Services.OutputPathService.<get_PickOutputPath>b__37_0()
   at ReactiveUI.ReactiveCommand.<>c__DisplayClass0_0.<Create>b__1(IObserver`1 observer) in D:\a\ReactiveUI\ReactiveUI\src\ReactiveUI\ReactiveCommand\ReactiveCommand.cs:line 109
   at System.Reactive.Linq.QueryLanguage.CreateWithDisposableObservable`1.SubscribeCore(IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Creation.cs:line 35
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/ObservableBase.cs:line 58
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass10_0.<.cctor>b__2() in D:\a\ReactiveUI\ReactiveUI\src\ReactiveUI\RxApp.cs:line 106
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0() in /_/Rx.NET/Source/src/System.Reactive/Platforms/Desktop/Concurrency/DispatcherScheduler.cs:line 98
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by RandomEngy** [comment]
Huh. The built-in Windows file dialog is throwing that exception. The only thing I can think is that it doesn't like the initial directory being passed in. Can you try going to Global Options -> Advanced and unchecking "Remember previously used files and folders"? That will cause us to stop passing in an initial directory to that dialog.

**Comment by Jigsaw289** [comment]
Cheers that solved the problem

Sent from Yahoo Mail on Android 
 
  On Sat, 1 Oct 2022 at 6:07, David ***@***.***> wrote:   


Huh. The built-in Windows file dialog is throwing that exception. The only thing I can think is that it doesn't like the initial directory being passed in. Can you try going to Global Options -> Advanced and unchecking "Remember previously used files and folders"? That will cause us to stop passing in an initial directory to that dialog.

**Comment by RandomEngy** [comment]
Great! If you could send me your %appdata%\VidCoder\VidCoder.sqlite file I could figure out why the crash was happening and fix it for others.

**Comment by Jigsaw289** [comment]
This is my sqlite file hope it helps
    On Wednesday, 12 October 2022 at 05:42:18 BST, David Rickard ***@***.***> wrote:  
 
 


Great! If you could send me your %appdata%\VidCoder\VidCoder.sqlite file I could figure out why the crash was happening and fix it for others.

**Comment by RandomEngy** [comment]
The file doesn't actually get sent if you attach it to the email. You need to go on the GitHub website for that to work.

**Comment by Jigsaw289** [comment]
[VidCoder.zip](https://github.com/RandomEngy/VidCoder/files/9792603/VidCoder.zip)

**Comment by RandomEngy** [comment]
Thanks! Though of course the initial directory value that caused the crash has been cleared out so I can't see exactly what caused the crash. Maybe I'll ask the next person this happens to.
