### ISSUE TITLE
System.ArgumentException: Cannot find preset: 1280p-HEVC

### ISSUE THREAD

**Issue by bdlegend** [RandomEngy/VidCoder#1062]
### What were you doing when VidCoder crashed?

VidCoder 8.9 Beta Zip
System.ArgumentException: Cannot find preset: 1280p-HEVC
   at VidCoder.Services.ProcessingService.QueueFromFileWatcher(String parentFolder, String[] sourcePaths, String presetName, String pickerName) in C:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1305
   at VidCoder.Services.ProcessingService.QueueWatchedFiles(IEnumerable`1 watchedFiles) in C:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1387
   at VidCoder.Services.WatchedFileStatusTracker.Start() in C:\git\VidCoder\VidCoder\Services\WatchedFileStatusTracker.cs:line 48
   at VidCoder.Services.ProcessingService.<>c__DisplayClass25_0.<.ctor>b__0() in C:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 135
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Crash details

```text
VidCoder 8.9 Beta Zip
System.ArgumentException: Cannot find preset: 1280p-HEVC
   at VidCoder.Services.ProcessingService.QueueFromFileWatcher(String parentFolder, String[] sourcePaths, String presetName, String pickerName) in C:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1305
   at VidCoder.Services.ProcessingService.QueueWatchedFiles(IEnumerable`1 watchedFiles) in C:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1387
   at VidCoder.Services.WatchedFileStatusTracker.Start() in C:\git\VidCoder\VidCoder\Services\WatchedFileStatusTracker.cs:line 48
   at VidCoder.Services.ProcessingService.<>c__DisplayClass25_0.<.ctor>b__0() in C:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 135
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by RandomEngy** [comment]
Thanks for the report. I'll change this to an error that shows up in the log in the next beta release. For now you need to update the watcher to make sure the preset it's pointing to exists.
