### ISSUE TITLE
ERROR: Operation 'Ping' failed

### ISSUE THREAD

**Issue by Fluffyblock** [RandomEngy/VidCoder#1063]
### Problem Description

Trying to encode some x264 files, encoding randomly fails

### What version of VidCoder are you running?

7.15 SquirrelInstaller

### Encode Log

```text
# VidCoder 7.15
# Starting job 11/49
#   Source path: C:\Users\admin\Downloads\[IrizaRaws] Koi wa Sekai Seifuku no Ato de (BDRip 1920x1080 x264 10bit FLAC)\[IrizaRaws] Koi wa Sekai Seifuku no Ato de - 10 (BDRip 1920x1080 x264 10bit FLAC).mkv
#   Destination path: C:\Users\admin\Videos\[IrizaRaws] Koi wa Sekai Seifuku no Ato de - 10 (BDRip 1920x1080 x264 10bit FLAC).mkv
#   Title: 1
#   Range: All
#   Preset: Restored from Completed
# Worker ready: Pipe 'VidCoderWorker.4ab26e8f-7828-46f0-bf35-a95d0973a3e8' is open
# Connecting to process 2980 on pipe VidCoderWorker.4ab26e8f-7828-46f0-bf35-a95d0973a3e8
[23:42:04] hb_init: starting libhb thread
[23:42:04] CPU: Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz
[23:42:04]  - Intel microarchitecture Broadwell
[23:42:04]  - logical processor count: 4
[23:42:04] Intel Quick Sync Video support: no
[23:42:04] hb_scan: path=C:\Users\admin\Downloads\[IrizaRaws] Koi wa Sekai Seifuku no Ato de (BDRip 1920x1080 x264 10bit FLAC)\[IrizaRaws] Koi wa Sekai Seifuku no Ato de - 10 (BDRip 1920x1080 x264 10bit FLAC).mkv, title_index=1
udfread ERROR: ECMA 167 Volume Recognition failed
src/libbluray/disc/disc.c:333: failed opening UDF image C:\Users\admin\Downloads\[IrizaRaws] Koi wa Sekai Seifuku no Ato de (BDRip 1920x1080 x264 10bit FLAC)\[IrizaRaws] Koi wa Sekai Seifuku no Ato de - 10 (BDRip 1920x1080 x264 10bit FLAC).mkv
src/libbluray/disc/disc.c:437: error opening file BDMV\index.bdmv
src/libbluray/disc/disc.c:437: error opening file BDMV\BACKUP\index.bdmv
src/libbluray/bluray.c:2646: nav_get_title_list(C:\Users\admin\Downloads\[IrizaRaws] Koi wa Sekai Seifuku no Ato de (BDRip 1920x1080 x264 10bit FLAC)\[IrizaRaws] Koi wa Sekai Seifuku no Ato de - 10 (BDRip 1920x1080 x264 10bit FLAC).mkv\) failed
[23:42:04] bd: not a bd - trying as a stream/file instead
libdvdread: DVDOpenFileUDF:UDFFindFile /VIDEO_TS/VIDEO_TS.IFO failed
libdvdnav: vm: vm: failed to read VIDEO_TS.IFO
[23:42:04] dvd: not a dvd - trying as a stream/file instead
Input #0, matroska,webm, from 'C:\Users\admin\Downloads\[IrizaRaws] Koi wa Sekai Seifuku no Ato de (BDRip 1920x1080 x264 10bit FLAC)\[IrizaRaws] Koi wa Sekai Seifuku no Ato de - 10 (BDRip 1920x1080 x264 10bit FLAC).mkv':
  Metadata:
    encoder         : libebml v1.4.2 + libmatroska v1.6.4
    creation_time   : 2022-08-15T00:00:36.000000Z
  Duration: 00:23:42.97, start: 0.000000, bitrate: 9026 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 120.995000
      Metadata:
        title           : Intro
    Chapter #0:1: start 120.995000, end 211.002000
      Metadata:
        title           : OP
    Chapter #0:2: start 211.002000, end 690.981000
      Metadata:
        title           : Part A
    Chapter #0:3: start 690.981000, end 1184.016000
      Metadata:
        title           : Part B
    Chapter #0:4: start 1184.016000, end 1273.939000
      Metadata:
        title           : ED
    Chapter #0:5: start 1273.939000, end 1399.940000
      Metadata:
        title           : Outro
    Chapter #0:6: start 1399.940000, end 1422.965000
      Metadata:
        title           : Preview
  Stream #0:0(eng): Video: h264 (High 10), yuv420p10le(progressive), 1920x1080 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn, 47.95 tbc (default)
    Metadata:
      BPS             : 7527090
      DURATION        : 00:23:42.963000000
      NUMBER_OF_FRAMES: 34117
      NUMBER_OF_BYTES : 1338846436
      _STATISTICS_WRITING_APP: mkvmerge v66.0.0 ('Josie') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-08-15 00:00:36
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(jpn): Audio: flac, 48000 Hz, stereo, s32 (24 bit) (default)
    Metadata:
      title           : Main FLAC 2.0
      BPS             : 1497351
      DURATION        : 00:23:42.965000000
      NUMBER_OF_FRAMES: 16676
      NUMBER_OF_BYTES : 266334855
      _STATISTICS_WRITING_APP: mkvmerge v66.0.0 ('Josie') 64-bit
      _STATISTICS_WRITING_DATE_UTC: 2022-08-15 00:00:36
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
[23:42:04] scan: decoding previews for title 1
[23:42:04] scan: audio 0x1: flac, rate=48000Hz, bitrate=1 ??? (FLAC) (2.0 ch)
[23:42:05] scan: 10 previews, 1920x1080, 23.976 fps, autocrop = 0/0/0/0, aspect 16:9, PAR 1:1, color profile: 1-1-1, chroma location: left
[23:42:05] libhb: scan thread found 1 valid title(s)
[23:42:06] Starting work at: Sat Oct 08 23:42:06 2022
[23:42:06] 1 job(s) to process
[23:42:06] json job:
{
  "Audio": {
    "AudioList": [
      {
        "Bitrate": 192,
        "CompressionLevel": 0,
        "DRC": 0,
        "Encoder": "opus",
        "Gain": 0,
        "Mixdown": 4,
        "NormalizeMixLevel": false,
        "Samplerate": 0,
        "Name": "Main FLAC 2.0",
        "Track": 0,
        "DitherMethod": 0
      }
    ],
    "CopyMask": [
      "copy:aac",
      "copy:ac3",
      "copy:eac3",
      "copy:truehd",
      "copy:dts",
      "copy:dtshd",
      "copy:mp2",
      "copy:mp3",
      "copy:flac"
    ]
  },
  "Destination": {
    "ChapterList": [
      {
        "Name": "Intro"
      },
      {
        "Name": "OP"
      },
      {
        "Name": "Part A"
      },
      {
        "Name": "Part B"
      },
      {
        "Name": "ED"
      },
      {
        "Name": "Outro"
      },
      {
        "Name": "Preview"
      }
    ],
    "ChapterMarkers": true,
    "AlignAVStart": false,
    "File": "C:\\Users\\admin\\Videos\\[IrizaRaws] Koi wa Sekai Seifuku no Ato de - 10 (BDRip 1920x1080 x264 10bit FLAC).part.mkv",
    "Mp4Options": {
      "IpodAtom": false,
      "Mp4Optimize": false
    },
    "Mux": "av_mkv"
  },
  "Filters": {
    "FilterList": [
      {
        "ID": 4,
        "Settings": {
          "mode": "7"
        }
      },
      {
        "ID": 3,
        "Settings": {
          "block-height": "16",
          "block-thresh": "40",
          "block-width": "16",
          "filter-mode": "2",
          "mode": "3",
          "motion-thresh": "1",
          "spatial-metric": "2",
          "spatial-thresh": "1"
        }
      },
      {
        "ID": 6,
        "Settings": {
          "mode": "1"
        }
      },
      {
        "ID": 13,
        "Settings": {
          "crop-bottom": "0",
          "crop-left": "0",
          "crop-right": "0",
          "crop-top": "0",
          "height": "1080",
          "width": "1920"
        }
      }
    ]
  },
  "PAR": {
    "Num": 1,
    "Den": 1
  },
  "Metadata": {},
  "SequenceID": 0,
  "Source": {
    "Angle": 0,
    "Range": {
      "Type": "chapter",
      "Start": 1,
      "End": 7
    },
    "Title": 1,
    "Path": "C:\\Users\\admin\\Downloads\\[IrizaRaws] Koi wa Sekai Seifuku no Ato de (BDRip 1920x1080 x264 10bit FLAC)\\[IrizaRaws] Koi wa Sekai Seifuku no Ato de - 10 (BDRip 1920x1080 x264 10bit FLAC).mkv"
  },
  "Subtitle": {
    "Search": {
      "Burn": false,
      "Default": false,
      "Enable": false,
      "Forced": false
    },
    "SubtitleList": []
  },
  "Video": {
    "Encoder": "x265_10bit",
    "Level": "auto",
    "TwoPass": false,
    "Turbo": false,
    "ColorMatrixCode": 0,
    "Options": "limit-sao:bframes=8:psy-rd=1:aq-mode=3",
    "Preset": "slow",
    "Profile": "auto",
    "Quality": 22,
    "Tune": "animation",
    "QSV": {
      "Decode": false
    }
  }
}
[23:42:06] Starting Task: Encoding Pass
[23:42:06] Skipping crop/scale filter
[23:42:06] work: track 1, dithering not supported by codec
[23:42:06] job configuration:
[23:42:06]  * source
[23:42:06]    + C:\Users\admin\Downloads\[IrizaRaws] Koi wa Sekai Seifuku no Ato de (BDRip 1920x1080 x264 10bit FLAC)\[IrizaRaws] Koi wa Sekai Seifuku no Ato de - 10 (BDRip 1920x1080 x264 10bit FLAC).mkv
[23:42:06]    + title 1, chapter(s) 1 to 7
[23:42:06]    + container: matroska,webm
[23:42:06]    + data rate: 9026 kbps
[23:42:06]  * destination
[23:42:06]    + C:\Users\admin\Videos\[IrizaRaws] Koi wa Sekai Seifuku no Ato de - 10 (BDRip 1920x1080 x264 10bit FLAC).part.mkv
[23:42:06]    + container: Matroska (libavformat)
[23:42:06]      + chapter markers
[23:42:06]  * video track
[23:42:06]    + decoder: h264 8-bit (yuv420p)
[23:42:06]    + filters
[23:42:06]      + Comb Detect (mode=3:spatial-metric=2:motion-thresh=1:spatial-thresh=1:filter-mode=2:block-thresh=40:block-width=16:block-height=16)
[23:42:06]      + Decomb (mode=39)
[23:42:06]      + Framerate Shaper (mode=1)
[23:42:06]        + frame rate: 23.976 fps -> constant 23.976 fps
[23:42:06]    + Output geometry
[23:42:06]      + storage dimensions: 1920 x 1080
[23:42:06]      + pixel aspect ratio: 1 : 1
[23:42:06]      + display dimensions: 1920 x 1080
[23:42:06]    + encoder: H.265 10-bit (libx265)
[23:42:06]      + preset:  slow
[23:42:06]      + tune:    animation
[23:42:06]      + options: limit-sao:bframes=8:psy-rd=1:aq-mode=3
[23:42:06]      + profile: auto
[23:42:06]      + level:   auto
[23:42:06]      + quality: 22.00 (RF)
[23:42:06]      + color profile: 1-1-1
[23:42:06]      + chroma location: left
[23:42:06]  * audio track 1
[23:42:06]    + name: Main FLAC 2.0
[23:42:06]    + decoder: ??? (FLAC) (2.0 ch) (track 1, id 0x1)
[23:42:06]      + samplerate: 48000 Hz
[23:42:06]    + mixdown: Stereo
[23:42:06]    + encoder: Opus (libopus)
[23:42:06]      + bitrate: 192 kbps, samplerate: 48000 Hz
[23:42:06]      + compression level: 0.00
[23:42:06] sync: expecting 34117 video frames
x265 [info]: HEVC encoder version 3.5+1-f0c1022b6
x265 [info]: build info [Windows][GCC 10.2.0][64 bit] 10bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast LZCNT SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2
x265 [info]: Main 10 profile, Level-4 (Main tier)
x265 [info]: Thread pool created using 4 threads
x265 [info]: Slices                              : 1
x265 [info]: frame threads / pool features       : 2 / wpp(17 rows)
x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge         : star / 57 / 3 / 3
x265 [info]: Keyframe min / max / scenecut / bias  : 24 / 240 / 40 / 5.00
x265 [info]: Lookahead / bframes / badapt        : 25 / 8 / 2
x265 [info]: b-pyramid / weightp / weightb       : 1 / 1 / 0
x265 [info]: References / ref-limit  cu / depth  : 4 / on / on
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 3 / 0.4 / 32 / 1
x265 [info]: Rate Control / qCompress            : CRF-22.0 / 0.60
x265 [info]: tools: rect limit-modes rd=4 psy-rd=1.00 rdoq=2 psy-rdoq=1.00
x265 [info]: tools: rskip mode=1 signhide tmvp strong-intra-smoothing lslices=4
x265 [info]: tools: deblock(tC=1:B=1) sao
[23:42:06] sync: first pts video is 0
[23:42:06] sync: "Intro" (1) at frame 1 time 0
[23:42:06] sync: first pts audio 0x1 is 0
[23:54:43] sync: "OP" (2) at frame 2902 time 10889628
[00:11:34] sync: "Part A" (3) at frame 5060 time 18990221
ERROR: Operation 'Ping' failed: System.IO.IOException: Cannot invoke method. Pipe has faulted.
 ---> System.InvalidOperationException: No pending call found for ID 19795504267264
   at PipeMethodCalls.MethodInvoker`1.HandleResponse(SerializedPipeResponse response)
   at PipeMethodCalls.PipeStreamWrapper.ProcessMessageAsync(CancellationToken cancellationToken)
   at PipeMethodCalls.PipeMessageProcessor.StartProcessing(PipeStreamWrapper pipeStreamWrapper)
   --- End of inner exception stack trace ---
   at PipeMethodCalls.Utilities.EnsureReadyForInvoke(PipeState state, Exception pipeFault)
   at PipeMethodCalls.MethodInvoker`1.InvokeAsync[TResult](Expression`1 expression, CancellationToken cancellationToken)
   at VidCoder.RemoteProxyBase`2.<>c__DisplayClass41_0.<<PrepareWorkerProcessAsync>b__1>d.MoveNext()
ERROR: Encode failed with code ErrorProcessCommunication
# Could not clean up failed file 'C:\Users\admin\Videos\[IrizaRaws] Koi wa Sekai Seifuku no Ato de - 10 (BDRip 1920x1080 x264 10bit FLAC).part.mkv'.
System.IO.IOException: The process cannot access the file 'C:\Users\admin\Videos\[IrizaRaws] Koi wa Sekai Seifuku no Ato de - 10 (BDRip 1920x1080 x264 10bit FLAC).part.mkv' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at System.IO.FileInfo.Delete()
   at VidCoder.Services.ProcessingService.TryHandleFailedFile(FileInfo directOutputFileInfo, IAppLogger encodeLogger, String reason, String finalOutputPath)
# Job completed (Elapsed Time: 48m 55s)
```

**Comment by RandomEngy** [comment]
Does it fail around the same point each time? Or just randomly? I've had one other report of the same issue, but it's been difficult to debug. Been staring at the code and it all looks fine.
