### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'VidCoderFileWatcher, Version=8.9.0.0, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.

### ISSUE THREAD

**Issue by mpek** [RandomEngy/VidCoder#1071]
### What were you doing when VidCoder crashed?

trying to encode an mkv with 3 from 6 audio tracks were chosen to just copy. Video should be cropped and encoded to H265 with NVenc. No subtitles chosen. 
My Malwarescanner, Max Secure Total Security, reported a "Trojan.Malware.300953.susgen" in: 
vidcoderfilewatcher.dll
vidcoderrelevatedsetup.dll
vidcodercli.dll

Not sure what's wrong, but if I can help, please let me know. 

"Das System kann die angegebene Datei nicht finden." is german and translated to english: 
The system can not find the stated file.

### Crash details

```text
VidCoder Beta 8.9 Portable
System.IO.FileNotFoundException: Could not load file or assembly 'VidCoderFileWatcher, Version=8.9.0.0, Culture=neutral, PublicKeyToken=null'. Das System kann die angegebene Datei nicht finden.
File name: 'VidCoderFileWatcher, Version=8.9.0.0, Culture=neutral, PublicKeyToken=null'
   at VidCoder.Services.WatcherProcessManager.SetStatusToStopped()
   at VidCoder.Services.WatcherProcessManager.RefreshStatus() in C:\git\VidCoder\VidCoder\Services\WatcherProcessManager.cs:line 172
   at VidCoder.Services.WatcherProcessManager..ctor(IProcesses processes, IAppLogger logger) in C:\git\VidCoder\VidCoder\Services\WatcherProcessManager.cs:line 49
   at lambda_method12(Closure , IResolverContext )
   at DryIoc.Factory.<>c__DisplayClass26_1.<ApplyReuse>b__2()
   at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder)
   at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder)
   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request)
   at DryIoc.Factory.GetExpressionOrDefault(Request request)
   at DryIoc.Factory.GetDelegateOrDefault(Request request)
   at DryIoc.Container.ResolveAndCacheDefaultFactoryDelegate(Type serviceType, IfUnresolved ifUnresolved)
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved)
   at DryIoc.Resolver.Resolve[TService](IResolver resolver, IfUnresolved ifUnresolved)
   at VidCoder.ViewModel.MainViewModel.OnClosing() in C:\git\VidCoder\VidCoder\ViewModel\MainViewModel.cs:line 708
   at VidCoder.Services.Windows.WindowManager.OnClosing(Window window, Boolean userInitiated) in C:\git\VidCoder\VidCoder\Services\Windows\WindowManager.cs:line 650
   at VidCoder.Services.Windows.WindowManager.OnClosingHandler(Object sender, CancelEventArgs e) in C:\git\VidCoder\VidCoder\Services\Windows\WindowManager.cs:line 631
   at System.Windows.Window.OnClosing(CancelEventArgs e)
   at System.Windows.Window.WmClose()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by RandomEngy** [comment]
Looks like your antivirus had a false positive and deleted a DLL that VidCoder needs to run.
