### ISSUE TITLE
ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.

### ISSUE THREAD

**Issue by lukeszabo** [RandomEngy/VidCoder#1076]
### What were you doing when VidCoder crashed?

I selected from the main screen to edit the current selected encoding profile. Then the app just hung, I selected to wait, thinking it might possibly be just taking a little while to load, but then this crash error appeared.

### Crash details

```text
VidCoder 8.2 Beta Portable
ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
 ---> code = Busy (5), message = System.Data.SQLite.SQLiteException (0x800007AF): database is locked
database is locked
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at VidCoder.Model.DatabaseConfig.SetInternal(String configName, String configValue, SQLiteConnection connection) in C:\git\VidCoder\VidCoder\Model\DatabaseConfig.cs:line 159
   at VidCoder.Model.DatabaseConfig.Set[T](String configName, T value, SQLiteConnection connection) in C:\git\VidCoder\VidCoder\Model\DatabaseConfig.cs:line 102
   at VidCoder.Config.Set[T](String key, T value) in C:\git\VidCoder\VidCoder\Model\Config\Config.cs:line 139
   at VidCoder.Services.Windows.WindowManager.PrepareWindowForOpen(Object viewModel, Object ownerViewModel, Boolean userInitiated, Boolean isDialog) in C:\git\VidCoder\VidCoder\Services\Windows\WindowManager.cs:line 524
   at VidCoder.Services.Windows.WindowManager.OpenOrFocusWindow[T](Object ownerViewModel) in C:\git\VidCoder\VidCoder\Services\Windows\WindowManager.cs:line 302
   at VidCoder.ViewModel.MainViewModel.<get_OpenEncodingWindow>b__354_0() in C:\git\VidCoder\VidCoder\ViewModel\MainViewModel.cs:line 2689
   at ReactiveUI.ReactiveCommand.<>c__DisplayClass0_0.<Create>b__1(IObserver`1 observer) in D:\a\ReactiveUI\ReactiveUI\src\ReactiveUI\ReactiveCommand\ReactiveCommand.cs:line 109
   at System.Reactive.Linq.QueryLanguage.CreateWithDisposableObservable`1.SubscribeCore(IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Creation.cs:line 35
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/ObservableBase.cs:line 58
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass10_0.<.cctor>b__2() in D:\a\ReactiveUI\ReactiveUI\src\ReactiveUI\RxApp.cs:line 106
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0() in /_/Rx.NET/Source/src/System.Reactive/Platforms/Desktop/Concurrency/DispatcherScheduler.cs:line 96
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by RandomEngy** [comment]
Did you have the file watcher enabled?
