### ISSUE TITLE
System.NotImplementedException: The method or operation is not implemented.

### ISSUE THREAD

**Issue by NPC-Master3304** [RandomEngy/VidCoder#1123]
### What were you doing when VidCoder crashed?

It's really strange. This started happening out of nowhere. It used to work just fine, but now it's broken. It immediately crashes when I try to open it up. I've also tried the stable releases as well, same issues.

### Crash details

```text
VidCoder 9.1 Beta SquirrelInstaller
System.NotImplementedException: The method or operation is not implemented.
   at MS.Internal.AppModel.ITaskbarList.HrInit()
   at System.Windows.Window.ApplyTaskbarItemInfo()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by NPC-Master3304** [comment]
nvm retrobar was the cause

**Comment by RandomEngy** [comment]
They are also working on fixing it in WPF: https://github.com/dotnet/wpf/pull/6547
