### ISSUE TITLE
Encoding crashed

### ISSUE THREAD

**Issue by jglazer63** [RandomEngy/VidCoder#1171]
### Problem Description

I have used your program for encoding many videos.  For some reason it simply won't encode videos from this show.  See log below.

### What version of VidCoder are you running?

8.26 SquirrelInstaller

### Encode Log

```text
# VidCoder 8.26
# Starting job 1/7
#   Source path: N:\TV\Foundation (2021)\Season 2\Foundation - S02E01 - In Seldon’s Shadow.mkv
#   Destination path: c:\converted\Foundation - S02E01 - In Seldon’s Shadow.mkv
#   Title: 1
#   Range: All
#   Preset: H.265 MKV 720p (NVenc) - 1hr Show
# Worker ready: Pipe 'VidCoderWorker.3d028acb-8b9e-4645-8cb3-b4539b341892' is open
# Connecting to process 5024 on pipe VidCoderWorker.3d028acb-8b9e-4645-8cb3-b4539b341892
[07:25:49] CPU:
[07:25:49]  - logical processor count: 4
[07:25:49] Intel Quick Sync Video support: no
[07:25:49] hb_scan: path=N:\TV\Foundation (2021)\Season 2\Foundation - S02E01 - In Seldon's Shadow.mkv, title_index=1
udfread ERROR: ECMA 167 Volume Recognition failed
src/libbluray/disc/disc.c:333: failed opening UDF image N:\TV\Foundation (2021)\Season 2\Foundation - S02E01 - In Seldonâ€™s Shadow.mkv
src/libbluray/disc/disc.c:437: error opening file BDMV\index.bdmv
src/libbluray/disc/disc.c:437: error opening file BDMV\BACKUP\index.bdmv
[07:25:49] bd: not a bd - trying as a stream/file instead
libdvdread: Could not open input:
libdvdread: Can't open N:\TV\Foundation (2021)\Season 2\Foundation - S02E01 - In Seldon’s Shadow.mkv for reading
libdvdnav: vm: failed to open/read the DVD
[07:25:49] dvd: not a dvd - trying as a stream/file instead
Input #0, matroska,webm, from 'N:\TV\Foundation (2021)\Season 2\Foundation - S02E01 - In Seldonâ€™s Shadow.mkv':
  Metadata:
    encoder         : libebml v1.4.4 + libmatroska v1.7.1
  Duration: 00:49:20.19, start: 0.000000, bitrate: 3621 kb/s
  Stream #0:0(eng): Video: h264 (High), yuv420p(tv, bt709, progressive), 1280x720 [SAR 1:1 DAR 16:9], 23.98 fps, 23.98 tbr, 1k tbn (default)
    Metadata:
      BPS             : 2846608
      DURATION        : 00:49:20.166000000
      NUMBER_OF_FRAMES: 70973
      NUMBER_OF_BYTES : 1053304037
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:1(eng): Audio: eac3, 48000 Hz, 5.1(side), fltp, 768 kb/s (default)
    Metadata:
      BPS             : 768000
      DURATION        : 00:49:20.192000000
      NUMBER_OF_FRAMES: 92506
      NUMBER_OF_BYTES : 284178432
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:2(eng): Subtitle: subrip
    Metadata:
      title           : English
      BPS             : 60
      DURATION        : 00:46:42.303000000
      NUMBER_OF_FRAMES: 557
      NUMBER_OF_BYTES : 21358
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:3(eng): Subtitle: subrip
    Metadata:
      title           : English (SDH)
      BPS             : 66
      DURATION        : 00:46:44.722000000
      NUMBER_OF_FRAMES: 612
      NUMBER_OF_BYTES : 23411
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:4(ara): Subtitle: subrip
    Metadata:
      title           : Ø§Ù„Ø¹Ø±Ø¨ÙŠØ©
      BPS             : 85
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 562
      NUMBER_OF_BYTES : 30856
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:5(bul): Subtitle: subrip
    Metadata:
      title           : Ð±ÑŠÐ»Ð³Ð°Ñ€ÑÐºÐ¸
      BPS             : 89
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 478
      NUMBER_OF_BYTES : 32422
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:6(cze): Subtitle: subrip
    Metadata:
      title           : ÄŒeÅ¡tina
      BPS             : 56
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 523
      NUMBER_OF_BYTES : 20283
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:7(dan): Subtitle: subrip
    Metadata:
      title           : dansk
      BPS             : 59
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 509
      NUMBER_OF_BYTES : 21572
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:8(ger): Subtitle: subrip
    Metadata:
      title           : Deutsch
      BPS             : 61
      DURATION        : 00:48:13.101000000
      NUMBER_OF_FRAMES: 558
      NUMBER_OF_BYTES : 22175
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:9(gre): Subtitle: subrip
    Metadata:
      title           : Î•Î»Î»Î·Î½Î¹ÎºÎ¬
      BPS             : 101
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 557
      NUMBER_OF_BYTES : 36788
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:10(spa): Subtitle: subrip
    Metadata:
      title           : EspaÃ±ol (EspaÃ±a)
      BPS             : 59
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 557
      NUMBER_OF_BYTES : 21544
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:11(spa): Subtitle: subrip
    Metadata:
      title           : EspaÃ±ol (LatinoamÃ©rica)
      BPS             : 59
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 569
      NUMBER_OF_BYTES : 21505
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:12(est): Subtitle: subrip
    Metadata:
      title           : eesti
      BPS             : 56
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 539
      NUMBER_OF_BYTES : 20495
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:13(fin): Subtitle: subrip
    Metadata:
      title           : Suomi
      BPS             : 55
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 551
      NUMBER_OF_BYTES : 20057
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:14(fre): Subtitle: subrip
    Metadata:
      title           : FranÃ§ais (France)
      BPS             : 58
      DURATION        : 00:47:41.111000000
      NUMBER_OF_FRAMES: 650
      NUMBER_OF_BYTES : 21040
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:15(fre): Subtitle: subrip
    Metadata:
      title           : FranÃ§ais (Canada)
      BPS             : 58
      DURATION        : 00:47:41.111000000
      NUMBER_OF_FRAMES: 651
      NUMBER_OF_BYTES : 21049
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:16(heb): Subtitle: subrip
    Metadata:
      title           : ×¢×‘×¨×™×ª
      BPS             : 79
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 562
      NUMBER_OF_BYTES : 28612
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:17(hin): Subtitle: subrip
    Metadata:
      title           : à¤¹à¤¿à¤¨à¥à¤¦à¥€
      BPS             : 153
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 563
      NUMBER_OF_BYTES : 55610
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:18(hun): Subtitle: subrip
    Metadata:
      title           : magyar
      BPS             : 62
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 560
      NUMBER_OF_BYTES : 22635
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:19(ind): Subtitle: subrip
    Metadata:
      title           : Bahasa Indonesia
      BPS             : 61
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 559
      NUMBER_OF_BYTES : 22263
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:20(ita): Subtitle: subrip
    Metadata:
      title           : Italiano
      BPS             : 62
      DURATION        : 00:47:20.298000000
      NUMBER_OF_FRAMES: 561
      NUMBER_OF_BYTES : 22356
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:21(jpn): Subtitle: subrip
    Metadata:
      title           : æ—¥æœ¬èªž
      BPS             : 52
      DURATION        : 00:48:12.976000000
      NUMBER_OF_FRAMES: 551
      NUMBER_OF_BYTES : 18993
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:22(kor): Subtitle: subrip
    Metadata:
      title           : í•œêµ­ì–´
      BPS             : 63
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 563
      NUMBER_OF_BYTES : 22959
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:23(lit): Subtitle: subrip
    Metadata:
      title           : lietuviÅ³
      BPS             : 59
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 562
      NUMBER_OF_BYTES : 21393
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:24(lav): Subtitle: subrip
    Metadata:
      title           : latvieÅ¡u
      BPS             : 59
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 551
      NUMBER_OF_BYTES : 21505
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:25(may): Subtitle: subrip
    Metadata:
      title           : Bahasa Melayu
      BPS             : 57
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 559
      NUMBER_OF_BYTES : 20604
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:26(dut): Subtitle: subrip
    Metadata:
      title           : Nederlands
      BPS             : 55
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 462
      NUMBER_OF_BYTES : 20184
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:27(nor): Subtitle: subrip
    Metadata:
      title           : norsk
      BPS             : 56
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 516
      NUMBER_OF_BYTES : 20511
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:28(pol): Subtitle: subrip
    Metadata:
      title           : polski
      BPS             : 55
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 542
      NUMBER_OF_BYTES : 20101
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:29(por): Subtitle: subrip
    Metadata:
      title           : PortuguÃªs
      BPS             : 58
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 555
      NUMBER_OF_BYTES : 21105
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:30(por): Subtitle: subrip
    Metadata:
      title           : PortuguÃªs (Brasil)
      BPS             : 56
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 535
      NUMBER_OF_BYTES : 20355
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:31(rus): Subtitle: subrip
    Metadata:
      title           : Ð ÑƒÑÑÐºÐ¸Ð¹
      BPS             : 87
      DURATION        : 00:47:21.967000000
      NUMBER_OF_FRAMES: 545
      NUMBER_OF_BYTES : 31140
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:32(slo): Subtitle: subrip
    Metadata:
      title           : SlovenÄina
      BPS             : 55
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 560
      NUMBER_OF_BYTES : 19903
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:33(slv): Subtitle: subrip
    Metadata:
      title           : slovenÅ¡Äina
      BPS             : 50
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 523
      NUMBER_OF_BYTES : 18171
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:34(swe): Subtitle: subrip
    Metadata:
      title           : Svenska
      BPS             : 59
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 559
      NUMBER_OF_BYTES : 21506
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:35(tam): Subtitle: subrip
    Metadata:
      title           : à®¤à®®à®¿à®´à¯
      BPS             : 194
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 562
      NUMBER_OF_BYTES : 70282
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:36(tel): Subtitle: subrip
    Metadata:
      title           : à°¤à±†à°²à±à°—à±
      BPS             : 177
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 562
      NUMBER_OF_BYTES : 64015
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:37(tha): Subtitle: subrip
    Metadata:
      title           : à¹„à¸—à¸¢
      BPS             : 153
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 562
      NUMBER_OF_BYTES : 55490
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:38(tur): Subtitle: subrip
    Metadata:
      title           : TÃ¼rkÃ§e
      BPS             : 59
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 537
      NUMBER_OF_BYTES : 21446
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:39(ukr): Subtitle: subrip
    Metadata:
      title           : ÑƒÐºÑ€Ð°Ñ—Ð½ÑÑŒÐºÐ°
      BPS             : 95
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 563
      NUMBER_OF_BYTES : 34430
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:40(vie): Subtitle: subrip
    Metadata:
      title           : Tiáº¿ng Viá»‡t
      BPS             : 80
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 560
      NUMBER_OF_BYTES : 29135
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:41(chi): Subtitle: subrip
    Metadata:
      title           : å»£æ±è©±
      BPS             : 53
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 563
      NUMBER_OF_BYTES : 19506
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:42(chi): Subtitle: subrip
    Metadata:
      title           : ä¸­æ–‡ï¼ˆç¹é«”ï¼‰
      BPS             : 53
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 563
      NUMBER_OF_BYTES : 19335
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
  Stream #0:43(chi): Subtitle: subrip
    Metadata:
      title           : ä¸­æ–‡ï¼ˆç®€ä½“ï¼‰
      BPS             : 53
      DURATION        : 00:48:09.973000000
      NUMBER_OF_FRAMES: 562
      NUMBER_OF_BYTES : 19383
      _STATISTICS_WRITING_APP: mkvmerge v76.0 ('Celebration') 64-bit
      _STATISTICS_TAGS: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES
[07:25:49] scan: decoding previews for title 1
[07:25:49] scan: audio 0x1: eac3, rate=48000Hz, bitrate=768000 English (E-AC3) (5.1 ch) (768 kbps)
[07:25:50] scan: 10 previews, 1280x720, 23.976 fps, autocrop = 94/94/0/0, aspect 16:9, PAR 1:1, color profile: 1-1-1, chroma location: topleft
[07:25:50] libhb: scan thread found 1 valid title(s)
ERROR: Worker process crashed. Please report this error so it can be fixed in the future:
System.ArgumentException: Video encoder nvenc_h265 not recognized.
   at VidCoderCommon.Model.JsonEncodeFactory.CreateVideo(VCJob job, SourceTitle title, Int32 previewLengthSeconds)
   at VidCoderCommon.Model.JsonEncodeFactory.CreateJsonObject(VCJob job, SourceTitle title, String defaultChapterNameFormat, Int32 previewNumber, Int32 previewSeconds, Int32 previewCount)
   at VidCoderWorker.HandBrakeEncodeWorker.<>c__DisplayClass4_0.<StartEncode>b__0(JsonScanObject scanObject)
   at VidCoderWorker.HandBrakeEncodeWorker.<>c__DisplayClass6_0.<StartEncodeInternal>b__0(Object o, EventArgs e)
ERROR: Operation 'Ping' failed, worker process has crashed.
ERROR: Encode failed with code ErrorHandBrakeProcessCrashed
# Job completed (Elapsed Time: 11s)
```

**Comment by RandomEngy** [comment]
> System.ArgumentException: Video encoder nvenc_h265 not recognized.

It looks like your current hardware doesn't support NVEnc x265. What happens when you switch to a different encoder?
