### ISSUE TITLE
System.TypeInitializationException: The type initializer for 'MS.Internal.Text.InternalEncoding' threw an exception.

### ISSUE THREAD

**Issue by HDMOVIESOURCE** [RandomEngy/VidCoder#1207]
### What were you doing when VidCoder crashed?

Encoding x264 while working with my browser over the day.

### Crash details

```text
VidCoder 9.16 Beta SquirrelInstaller
System.TypeInitializationException: The type initializer for 'MS.Internal.Text.InternalEncoding' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.Encoding.CodePages, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Text.Encoding.CodePages, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at MS.Internal.Text.InternalEncoding..cctor()
   --- End of inner exception stack trace ---
   at System.Windows.Documents.FontTableEntry.ComputePreferredCodePage()
   at System.Windows.Documents.XamlToRtfWriter..ctor(String xaml)
   at System.Windows.Documents.XamlRtfConverter.ConvertXamlToRtf(String xamlContent)
   at System.Windows.Documents.TextEditorCopyPaste.ConvertXamlToRtf(String xamlContent, Stream wpfContainerMemory)
   at System.Windows.Documents.TextEditorCopyPaste._CreateDataObject(TextEditor This, Boolean isDragDrop)
   at System.Windows.Documents.TextEditorCopyPaste.Copy(TextEditor This, Boolean userInitiated)
   at System.Windows.Documents.TextEditorCopyPaste.OnCopy(Object target, ExecutedRoutedEventArgs args)
   at System.Windows.Input.CommandBinding.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.Input.CommandManager.FindCommandBinding(Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
   at System.Windows.Input.CommandManager.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.UIElement.OnExecutedThunk(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.RoutedCommand.ExecuteImpl(Object parameter, IInputElement target, Boolean userInitiated)
   at System.Windows.Input.RoutedCommand.ExecuteCore(Object parameter, IInputElement target, Boolean userInitiated)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by RandomEngy** [comment]
I think this must be in the same category as the #1093, where some basic DLL is missing due to a .NET upgrade issue. It's already reported but unfortunately there's nothing I can do about it right now.

**Comment by HDMOVIESOURCE** [comment]
Okay, I made sure I downloaded all the new .NET versions after, and I haven't seen any issues since. So maybe that's it.
