### ISSUE TITLE
Crash when toggling custom presets

### ISSUE THREAD

**Issue by mrlenny** [RandomEngy/VidCoder#1209]
### What were you doing when VidCoder crashed?

toggling between custom presets

### Crash details

```text
VidCoder 9.17 SquirrelInstaller
ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at VidCoder.ViewModel.VideoFiltersPanelViewModel.get_ColorspacePreset()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at ReactiveUI.Reflection.TryGetValueForPropertyChain[TValue](TValue& changeValue, Object current, IEnumerable`1 expressionChain) in D:\a\ReactiveUI\ReactiveUI\src\ReactiveUI\Expression\Reflection.cs:line 261
   at ReactiveUI.ObservedChangedMixin.TryGetValue[TSender,TValue](IObservedChange`2 item, TValue& changeValue) in D:\a\ReactiveUI\ReactiveUI\src\ReactiveUI\Mixins\ObservedChangedMixin.cs:line 131
   at ReactiveUI.ObservedChangedMixin.GetValueOrDefault[TSender,TValue](IObservedChange`2 item) in D:\a\ReactiveUI\ReactiveUI\src\ReactiveUI\Mixins\ObservedChangedMixin.cs:line 79
   at ReactiveUI.ReactiveNotifyPropertyChangedMixin.<>c.<NestedObservedChanges>b__5_0(IObservedChange`2 x) in D:\a\ReactiveUI\ReactiveUI\src\ReactiveUI\Mixins\ReactiveNotifyPropertyChangedMixin.cs:line 194
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 48
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass10_0.<.cctor>b__2() in D:\a\ReactiveUI\ReactiveUI\src\ReactiveUI\RxApp.cs:line 106
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0() in /_/Rx.NET/Source/src/System.Reactive/Platforms/Desktop/Concurrency/DispatcherScheduler.cs:line 98
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by mrlenny** [comment]
dup
