### ISSUE TITLE
ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.

### ISSUE THREAD

**Issue by mrlenny** [RandomEngy/VidCoder#1210]
### What were you doing when VidCoder crashed?

changing between custom presets

### Crash details

```text
VidCoder 9.17 SquirrelInstaller
ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at VidCoder.ViewModel.VideoFiltersPanelViewModel.GetCustomFilterToolTip(hb_filter_ids filter)
   at VidCoder.ViewModel.VideoFiltersPanelViewModel.<>c.<.ctor>b__4_14(VCDeinterlace deinterlaceType)
   at ReactiveUI.WhenAnyMixin.<>c__DisplayClass1_0`3.<WhenAnyValue>b__0(IObservedChange`2 c1) in D:\a\ReactiveUI\ReactiveUI\src\ReactiveUI\VariadicTemplates.cs:line 54
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Select.cs:line 39
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass10_0.<.cctor>b__2() in D:\a\ReactiveUI\ReactiveUI\src\ReactiveUI\RxApp.cs:line 106
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0() in /_/Rx.NET/Source/src/System.Reactive/Platforms/Desktop/Concurrency/DispatcherScheduler.cs:line 98
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by RandomEngy** [comment]
Are you using a custom hb.dll ?

**Comment by mrlenny** [comment]
I am indeed, and that was the issue, I built a fresh build of 1.7.0 from handbrake because when you released your new version that's what they had defaulted in their git. a quick tag switch to 1.7.2 and all's right as rain. (at least with this issue.)
