### ISSUE TITLE
Encoding a preview clip generates an error if you use a 'Custom' NL-Means denoise preset

### ISSUE THREAD

**Issue by KevinInSeattle** [RandomEngy/VidCoder#124]
Encoding a preview clip generates an error if you use a 'Custom' NL-Means denoise preset

**Description:**
If you try and encode a preview clip with a custom 'NL-Means' preset, such as "1:1:1:1", Vidcoder gives an error that says "Preview clip generation failed. See the Log window for details."  However, it will generate a preview if you use a preset other than 'Custom'.

I am using VidCoder version 2.33 Beta (x64) on Windows 10 Pro 64-Bit.

**Repro:**
1. Select Settings
2. Press the Video Filters tab
3. Select 'NL-Means' under Denoise
4. Create a Custom preset of '1:1:1:1'
5. Press Preview
6. Press Encode Preview Clip

**Actual Results:**
VidCoder gives an error that says "Preview clip generation failed. See the Log window for details."

**Expected Results:**
A preview clip is generated.

**Log File:**
# Generating preview clip
#   Path: C:\Users\klepe\AppData\Local\VidCoder-Beta\preview.mp4
#   Title: 1
#   Preview #: 4
# Worker ready: Service state is Opened on pipe VidCoderWorker.b3f7a667-e018-413c-8a54-a77274fd4e2d
# Connecting to process 5360 on pipe VidCoderWorker.b3f7a667-e018-413c-8a54-a77274fd4e2d
[22:29:27] hb_init: starting libhb thread
[22:29:27] CPU: Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
[22:29:27]  - Intel microarchitecture Ivy Bridge
[22:29:27]  - logical processor count: 8
[22:29:27] OpenCL device #1: NVIDIA Corporation GeForce GTX 680
[22:29:27]  - OpenCL version: 1.2 CUDA
[22:29:27]  - driver version: 368.81
[22:29:27]  - device type:    GPU
[22:29:27]  - supported:      no
[22:29:27] Intel Quick Sync Video support: no
[22:29:27] hb_scan: path=G:\, title_index=1
[22:29:28] scan: BD has 120 title(s)
[22:29:28] bd: scanning title 1
[22:29:28] bd: playlist 00011.MPLS
[22:29:28] bd: duration is 01:46:27 (6387381 ms)
[22:29:28] bd: video id=0x1011, stream type=H.264, format 1080p
[22:29:28] bd: aspect = 16:9
[22:29:28] bd: audio id=0x761100, lang=English (AC3), 3cc=eng
[22:29:28] bd: audio id=0x721100, lang=English (TrueHD), 3cc=eng
[22:29:28] bd: audio id=0x761101, lang=Francais (AC3), 3cc=fra
[22:29:28] bd: audio id=0x721101, lang=Francais (TrueHD), 3cc=fra
[22:29:28] bd: audio id=0x1102, lang=espa¤ol (AC3), 3cc=spa
[22:29:28] bd: audio id=0x761103, lang=Portugues (AC3), 3cc=por
[22:29:28] bd: audio id=0x721103, lang=Portugues (TrueHD), 3cc=por
[22:29:28] bd: subtitle id=0x1200, lang=English, 3cc=eng
[22:29:28] bd: subtitle id=0x1201, lang=English, 3cc=eng
[22:29:28] bd: subtitle id=0x1202, lang=Francais, 3cc=fra
[22:29:28] bd: subtitle id=0x1203, lang=espa¤ol, 3cc=spa
[22:29:28] bd: subtitle id=0x1204, lang=??, 3cc=zho
[22:29:28] bd: subtitle id=0x1205, lang=???, 3cc=kor
[22:29:28] bd: subtitle id=0x1206, lang=Portugues, 3cc=por
[22:29:28] bd: subtitle id=0x1207, lang=???, 3cc=tha
[22:29:28] bd: chap 1 packet=768, 459083 ms
[22:29:28] bd: chap 2 packet=2484720576, 199407 ms
[22:29:28] bd: chap 3 packet=3551246208, 471220 ms
[22:29:28] bd: chap 4 packet=6072958848, 290498 ms
[22:29:28] bd: chap 5 packet=7630982208, 478519 ms
[22:29:28] bd: chap 6 packet=10119709248, 342216 ms
[22:29:28] bd: chap 7 packet=11980887168, 386594 ms
[22:29:28] bd: chap 8 packet=14034140352, 291666 ms
[22:29:28] bd: chap 9 packet=15633201216, 451659 ms
[22:29:28] bd: chap 10 packet=18010370496, 459542 ms
[22:29:28] bd: chap 11 packet=20435300928, 305847 ms
[22:29:28] bd: chap 12 packet=22079723712, 484692 ms
[22:29:28] bd: chap 13 packet=24626278656, 313438 ms
[22:29:28] bd: chap 14 packet=26370421056, 381130 ms
[22:29:28] bd: chap 15 packet=28390149888, 335209 ms
[22:29:28] bd: chap 16 packet=30252201792, 736652 ms
[22:29:28] bd: title 1 has 16 chapters
[22:29:28] scan: decoding previews for title 1
[22:29:28] scan: title angle(s) 1
[22:29:28] scan: audio 0x761100: ac3, rate=48000Hz, bitrate=448000 English (AC3) (5.1 ch)
[22:29:28] scan: audio 0x761101: ac3, rate=48000Hz, bitrate=640000 Francais (AC3) (5.1 ch)
[22:29:28] scan: audio 0x1102: ac3, rate=48000Hz, bitrate=640000 espa¤ol (AC3) (5.1 ch)
[22:29:28] scan: audio 0x761103: ac3, rate=48000Hz, bitrate=640000 Portugues (AC3) (5.1 ch)
[22:29:28] scan: audio 0x721100: truehd, rate=48000Hz, bitrate=200000 English (TrueHD) (5.1 ch)
[22:29:28] scan: audio 0x721101: truehd, rate=48000Hz, bitrate=200000 Francais (TrueHD) (5.1 ch)
[22:29:28] scan: audio 0x721103: truehd, rate=48000Hz, bitrate=200000 Portugues (TrueHD) (5.1 ch)
[22:29:29] scan: 10 previews, 1920x1080, 23.976 fps, autocrop = 140/140/0/0, aspect 16:9, PAR 1:1
[22:29:29] scan: supported video decoders: avcodec qsv
[22:29:29] stream: 5 good frames, 0 errors (0%)
[22:29:29] libhb: scan thread found 1 valid title(s)
[22:29:29] hb_parse_filter_settings: Error parsing (none)
# Worker process crashed. Please report this error so it can be fixed in the future:
System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.IO.StringReader..ctor(String s)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at VidCoderCommon.Model.JsonEncodeFactory.CreateFilters(VCProfile profile, SourceTitle title, Geometry anamorphicSize) in D:\docs\projects\VidCoder\VidCoderCommon\Model\JsonEncodeFactory.cs:line 440
   at VidCoderCommon.Model.JsonEncodeFactory.CreateJsonObject(VCJob job, SourceTitle title, String defaultChapterNameFormat, Boolean dxvaDecoding, Int32 previewNumber, Int32 previewSeconds, Int32 previewCount, ILogger logger) in D:\docs\projects\VidCoder\VidCoderCommon\Model\JsonEncodeFactory.cs:line 68
   at VidCoderWorker.HandBrakeEncoder.<>c__DisplayClass4_2.<StartEncode>b__4(Object o, EventArgs e) in D:\docs\projects\VidCoder\VidCoderWorker\HandBrakeEncoder.cs:line 106
# Preview clip generation failed

**Comment by RandomEngy** [comment]
HandBrake updated the format of custom filter settings, it's now `property1=value1:property2=value2:...` 

Copied from the HandBrakeCLI help:
```
   --nlmeans[=string]      Denoise video with NLMeans filter
                           Presets:
                               ultralight
                               light
                               medium
                               strong
                           Custom Format:
                               y-strength=y:y-origin-tune=y:y-patch-size=y:
                               y-range=y:y-frame-count=y:y-prefilter=y:
                               cb-strength=c:cb-origin-tune=c:cb-patch-size=c:
                               cb-range=c:cb-frame-count=c:cb-prefilter=c:
                               cr-strength=c:cr-origin-tune=c:cr-patch-size=c:
                               cr-range=c:cr-frame-count=c:cr-prefilter=c
                           Default:
                               y-strength=6:y-origin-tune=1:y-patch-size=7:
                               y-range=3:y-frame-count=2:y-prefilter=0:
                               cb-strength=6:cb-origin-tune=1:cb-patch-size=7:
                               cb-range=3:cb-frame-count=2:cb-prefilter=0
```

In the next version of VidCoder I'll update it to give a better error message.

**Comment by RandomEngy** [comment]
Updated the error message in 2.35 Beta.
