### ISSUE TITLE
System.InvalidOperationException: Impossible d'affecter Visible à Visibility ou d'appeler Show, ShowDialog, Close ou WindowInteropHelper.EnsureHandle lorsqu'un objet Window est en cours de fermeture.

### ISSUE THREAD

**Issue by Bleue7** [RandomEngy/VidCoder#1261]
### What were you doing when VidCoder crashed?

Bonjour,
Depuis hier soir, dès que je lance le ré encodage d'un film ou série rien ne s'affiche = pas de temps, pas de barre d'avancement. 
![image_2024-06-21_094952103](https://github.com/RandomEngy/VidCoder/assets/173446214/a979f354-af0b-4b17-a615-ef133efca19e)
Et lorsque je veux arrêter ou fermer VidCoder, il est indiqué qu'il est en cours de ré encodage ; sauf qu'il n'y a pas de film dans mon dossier destinataire.
Je n'ai rien touché dans les paramètres / options depuis qu'il est installé (février 2024)

Je vous joins les 2 messages d'erreur récupérés.

[VC [082851] VidCoder 9.20 - error 1.txt](https://github.com/user-attachments/files/15924417/VC.082851.VidCoder.9.20.-.error.1.txt)
[VidCoder 9.20 SquirrelInstaller.txt](https://github.com/user-attachments/files/15924418/VidCoder.9.20.SquirrelInstaller.txt)

--------------------------------

Good morning,
Since last night, as soon as I start the re-encoding of a movie or series nothing is displayed = no time, no progress bar. 
![image_2024-06-21_094952103](https://github.com/RandomEngy/VidCoder/assets/173446214/a979f354-af0b-4b17-a615-ef133efca19e)
And when I want to stop or close VidCoder, it says that it is being re-encoded; except that there is no movie in my recipient folder.
I haven’t touched anything in the settings/options since it was installed (February 2024)

I attach the 2 recovered error messages.

### Crash details

```text
- ouverture de VidCoder
- ajout du film ou épisode
- réglage des paramètres de sortie
- clique sur " encoder "
-> et rien ne se passe

----------

- opening of VidCoder
- addition of film or episode
- adjustment of output parameters
- click on "encode"
-> and nothing happens
```

**Comment by RandomEngy** [comment]
This error I can help with:

System.InvalidOperationException: Impossible d'affecter Visible à Visibility ou d'appeler Show, ShowDialog, Close ou WindowInteropHelper.EnsureHandle lorsqu'un objet Window est en cours de fermeture.
   at System.Windows.Window.VerifyNotClosing()
   at System.Windows.Window.Show()
   at VidCoder.View.Main.<RestoreWindow>b__15_0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

With the next Beta release, it should no longer crash. I think that's separate from your other "encoding hang" issue, though.

I do see in the first log: "libhb: scan thread found 0 valid title(s)". That means that the HandBrake core scanned it but did not find any title that met the minimum video length. What do you see on the main window when you open that video file?

**Comment by Bleue7** [comment]
Hi David,
Thank you for your answer  :-) and sorry for my late, I could not come before, being very busy.

What I did was uninstall version 9.20 properly and install the new version. I wanted to put the Beta but the stable was available. My problems of re-encoding were fixed suddenly.

But to answer you to
What do you see on the main window when you open that video file?
hoping I understood the question... 
Regarding the video, when I was watching the information about codecs included + media on VLC, everything seemed correct. They were identical to those I could have for other videos. The title of the videos were present, speed, size, etc...
And if your question concerns VidCoder and the parameters to choose, with version 9.20, I took " mkv ". And then I adjusted the other options according to my needs.

Overnight this little problem happened and yet I had not touched anything special (I do not know enough).

Well, the main thing is that everything works again  :-) I like this little software  :-)

Thank you again and nice evening or day.

**Comment by Bleue7** [comment]
Good morning,
I wanted to re-encode a movie again and it didn’t work. I have a failed error message. I tried for the same movie with several parameters, it does not work.
I’m attaching the log that shows where the problem is coming from, but I don’t know what to do:(
Thanks in advance for reading me and future help.
Good evening or day
[2024-07-02 17.14.23 Encode The Elephant Queen (2019).mkv-failed.txt](https://github.com/user-attachments/files/16071740/2024-07-02.17.14.23.Encode.The.Elephant.Queen.2019.mkv-failed.txt)
