### ISSUE TITLE
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by elchdriver942** [RandomEngy/VidCoder#1270]
### What were you doing when VidCoder crashed?

start vidcoder

### Crash details

```text
VidCoder Beta 11.3 Portable
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at VidCoder.Config.get_UseWorkerProcess() in C:\git\VidCoder\VidCoder\Model\Config\Config.cs:line 645
   at VidCoder.CustomConfig.get_UseWorkerProcess() in C:\git\VidCoder\VidCoder\Model\Config\CustomConfig.cs:line 55
   at VidCoder.Ioc.<>c__DisplayClass0_0.<SetUp>b__0() in C:\git\VidCoder\VidCoder\Utilities\Ioc.cs:line 43
   at Microsoft.AnyContainer.DryIoc.DryIocSingletonScopeRegistrar.<>c__DisplayClass4_0`1.<Register>b__0(IResolverContext c)
   at DryIoc.Registrator.<>c__DisplayClass26_0`1.<RegisterDelegate>b__0(IResolverContext r)
   at DryIoc.Factory.<>c__DisplayClass26_1.<ApplyReuse>b__2()
   at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder)
   at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder)
   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request)
   at DryIoc.Factory.GetExpressionOrDefault(Request request)
   at DryIoc.Factory.GetDelegateOrDefault(Request request)
   at DryIoc.DelegateFactory.GetDelegateOrDefault(Request request)
   at DryIoc.Container.ResolveAndCacheDefaultFactoryDelegate(Type serviceType, IfUnresolved ifUnresolved)
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved)
   at DryIoc.Resolver.Resolve[TService](IResolver resolver, IfUnresolved ifUnresolved)
   at Microsoft.AnyContainer.DryIoc.DryIocAnyContainer.Resolve[T]()
   at Microsoft.AnyContainer.StaticResolver.Resolve[T]()
   at VidCoder.Services.Windows.WindowManager..ctor() in C:\git\VidCoder\VidCoder\Services\Windows\WindowManager.cs:line 33
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at DryIoc.ReflectionFactory.<>c__DisplayClass21_0.<GetActivator>b__0()
   at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder)
   at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder)
   at DryIoc.ReflectionFactory.CreateServiceExpression(MemberInfo ctorOrMember, Expression factoryExpr, Expression[] paramExprs, Request request)
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request)
   at DryIoc.Factory.GetExpressionOrDefault(Request request)
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request)
   at DryIoc.Factory.GetExpressionOrDefault(Request request)
   at DryIoc.Factory.GetDelegateOrDefault(Request request)
   at DryIoc.Container.ResolveAndCacheDefaultFactoryDelegate(Type serviceType, IfUnresolved ifUnresolved)
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved)
   at DryIoc.Resolver.Resolve[TService](IResolver resolver, IfUnresolved ifUnresolved)
   at Microsoft.AnyContainer.DryIoc.DryIocAnyContainer.Resolve[T]()
   at Microsoft.AnyContainer.StaticResolver.Resolve[T]()
   at VidCoder.Model.Database.Initialize() in C:\git\VidCoder\VidCoder\Model\Database.cs:line 55
   at VidCoder.App.OnStartup(StartupEventArgs e) in C:\git\VidCoder\VidCoder\App.xaml.cs:line 125
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by RandomEngy** [comment]
Looks like this crashed because it was trying to upgrade a DB version that was too old, and the code to display the message had an issue. Try running v3.15 once, then running the latest version.
