### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Robert-62** [RandomEngy/VidCoder#1275]
### What were you doing when VidCoder crashed?

Adding extra items to the queue using drag and drop

### Crash details

```text
VidCoder 10.14 VelopackInstaller
System.NullReferenceException: Object reference not set to an instance of an object.
   at VidCoder.Services.ProcessingService.FindSubtitleFile(String sourcePath, Picker picker, Boolean openDialogOnMissingCharCode)
   at VidCoder.Services.ProcessingService.AutoPickSubtitles(VCJob job, SourceTitle title, Boolean useCurrentContext, Boolean openDialogOnMissingCharCode, Picker picker)
   at VidCoder.Services.ProcessingService.QueueFromScanResults(IList`1 scanResults, Boolean start)
   at VidCoder.Services.QueueAdderService.<>c__DisplayClass28_0.<AddResultsToQueue>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by RandomEngy** [comment]
Thanks for the report. There's a fix in v11.4 Beta.
