### ISSUE TITLE
System.IO.FileNotFoundException: Could not find file 'C:\Users\jaska\AppData\Local\VidCoder.Stable\preview.mp4'.

### ISSUE THREAD

**Issue by jaska-sen** [RandomEngy/VidCoder#1278]
### What were you doing when VidCoder crashed?

I can't rememember.

### Crash details

```text
VidCoder 10.14 VelopackInstaller
System.IO.FileNotFoundException: Could not find file 'C:\Users\jaska\AppData\Local\VidCoder.Stable\preview.mp4'.
File name: 'C:\Users\jaska\AppData\Local\VidCoder.Stable\preview.mp4'
   at System.IO.FileInfo.get_Length()
   at VidCoder.ViewModel.PreviewWindowViewModel.<>c__DisplayClass111_0.<get_GeneratePreview>b__7()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by RandomEngy** [comment]
Thanks for the report. This should be fixed in 11.5 Beta.
