### ISSUE TITLE
System.Data.SQLite.SQLiteException: unable to open database file

### ISSUE THREAD

**Issue by Luvong** [RandomEngy/VidCoder#1283]
### What were you doing when VidCoder crashed?

start exe; after download

### Crash details

```text
VidCoder 10.14 Portable
code = CantOpen (14), message = System.Data.SQLite.SQLiteException (0x87AF03F3): unable to open database file
   at System.Data.SQLite.SQLite3.Open(String strFilename, String vfsName, SQLiteConnectionFlags connectionFlags, SQLiteOpenFlagsEnum openFlags, Int32 maxPoolSize, Boolean usePool)
   at System.Data.SQLite.SQLiteConnection.Open()
   at VidCoder.Model.Database.CreateConnection() in C:\git\VidCoder\VidCoder\Model\Database.cs:line 539
   at VidCoder.Model.Database.get_Connection() in C:\git\VidCoder\VidCoder\Model\Database.cs:line 497
   at VidCoder.Model.Database.get_Version() in C:\git\VidCoder\VidCoder\Model\Database.cs:line 105
   at VidCoder.Model.Database.Initialize() in C:\git\VidCoder\VidCoder\Model\Database.cs:line 36
   at VidCoder.App.OnStartup(StartupEventArgs e) in C:\git\VidCoder\VidCoder\App.xaml.cs:line 125
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by RandomEngy** [comment]
Hmm. What folder were you running it in? It looks like it crashed trying to open VidCoder.sqlite . Do you have a VidCoder.sqlite next to your portable .exe? If so, what happens if you rename it?
