### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by misterjohnk** [RandomEngy/VidCoder#1290]
### What were you doing when VidCoder crashed?

I did a clean install on Win7 64-bit.  Every launch attempt fails with an "System.NullReferenceException: Object reference not set to an instance of an object." error.

### Crash details

```text
VidCoder 11.5 Beta VelopackInstaller
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.AnyContainer.StaticResolver.Resolve[T]()
   at VidCoder.View.ExceptionDialog.copyButton_Click(Object sender, RoutedEventArgs e)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by RandomEngy** [comment]
Thanks for the report. I put a fix in for 11.6 Beta that should improve the error message here. Can you let me know what it says on v 11.6?

**Comment by misterjohnk** [comment]
The error now is:

`VidCoder 11.6 Beta Portable
System.DllNotFoundException: Unable to load DLL 'hb' or one of its dependencies: The specified procedure could not be found. (0x8007007F)
   at HandBrake.Interop.Interop.HbLib.HBFunctions.hb_global_init_no_hardware()
   at HandBrake.Interop.Interop.HandBrakeUtils.EnsureGlobalInit(Boolean initNoHardwareMode) in C:\git\HandBrake\win\CS\HandBrake.Interop\Interop\HandBrakeUtils.cs:line 95
   at VidCoder.App.OnStartup(StartupEventArgs e) in C:\git\VidCoder\VidCoder\App.xaml.cs:line 121
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
`

I'm guessing Win7 is not supported?  If so, do you know the latest version which supports Win7?  Thanks.

**Comment by RandomEngy** [comment]
Yes, that's right. For a while now, Windows 7/8 has been "run at your own risk". In the latest VidCoder beta I've extended the OS version error and block to cover Win7/8.

The latest version that supports Windows 7 is VidCoder 5.21.
