### ISSUE TITLE
Unexpected parameters - System Error modal dialog?

### ISSUE THREAD

**Issue by wkearney99** [RandomEngy/VidCoder#1298]
### Problem Description

I have a number of video clips being transcoded.  A dialog appears with the title: VidCoderWorker.exe - System error, a red (x) icon and the text: "Exception Processing Message 0xc0000005 - Unexpected Parameters".

However, the queue shows no errors?  It seems like all files transcoded properly.

Searching the appdata logs folder did not find 'unexpected' or 'parameters' in any of the log files.

The modal dialog pops up on the active desktop, not the virtual desktop in which vidcoder is running.  Which, I suppose, is understandable as it's a modal dialog requiring attention.  However, the transcoding actions kept running in the background, so the modal nature of the dialog didn't appear to be stopping anything from continuing.  Since it didn't stop anything I can't quite pin down which video was actually triggering the error.

I've re-run the same video files and it's not popping up the same errors.

In checking the combined log I did see "HB Fatal error"

I think the 'threaded' nature of the logging/transcoding makes it tricky to tell which video caused HB to throw that error.  I did manage (using notepad++ 'find in files' search) to find the fatal error in an individual video log.  Oddly, it was at the END of the log file and the video appears to have transcoded properly.

I do not know if the HB error was what was causing VC to throw the modal error.

### What version of VidCoder are you running?

11.6 Beta

### Encode Log

```text
VC [07:46:52] VidCoder 11.6 Beta
VC [07:46:52] Starting job 27/56
VC [07:46:52]   Source path: c:\temp\editedfilename_1080p.mp4
VC [07:46:52]   Destination path: c:\temp\editedfilename_1080p (Encoded).mp4
VC [07:46:52]   Title: 1
VC [07:46:52]   Range: All
VC [07:46:52]   Preset: test H.265 NVENC 720 low
VC [07:46:52]   Picker: h265 720width
VC [07:46:52] Worker ready: Pipe 'VidCoderWorker.0a276762-7d3f-4ba3-92fd-a1af09882ce3' is open
VC [07:46:52] Connecting to process 64068 on pipe VidCoderWorker.0a276762-7d3f-4ba3-92fd-a1af09882ce3
HB [07:46:53] CPU: AMD Ryzen 9 5900X 12-Core Processor
[07:46:53]  - logical processor count: 24
[07:46:53] Intel Quick Sync Video support: no
[07:46:53] hb_scan: path=c:\temp\editedfilename_1080p.mp4, title_index=1
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'c:\temp\editedfilename_1080p.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    title           : Downloaded
    encoder         : Lavf58.29.100
    comment         : Downloaded
    episode_sort    : 0
    season_number   : 0
    media_type      : 9
    hd_video        : 0
  Duration: 00:16:55.66, start: 0.000000, bitrate: 6202 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 1015.000000
      Metadata:
        title           : Chapter 1
  Stream #0:0[0x1](eng): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709, progressive), 1920x1080 [SAR 1:1 DAR 16:9], 6003 kb/s, 50 fps, 50 tbr, 50k tbn (default)
      Metadata:
        handler_name    : MP4 Video Media Handler
        vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 189 kb/s (default)
      Metadata:
        handler_name    : MP4 Sound Media Handler
        vendor_id       : [0][0][0][0]
  Stream #0:2[0x3](eng): Data: bin_data (text / 0x74786574)
      Metadata:
        handler_name    : SubtitleHandler
[07:46:53] scan: decoding previews for title 1
[07:46:53] scan: audio 0x1: aac, rate=48000Hz, bitrate=189467 English (AAC LC, 2.0 ch, 189 kbps)
HB [07:46:53] using container PAR 1:1
[07:46:53] scan: 10 previews, 1920x1080, 50.000 fps, autocrop = 0/0/0/0, aspect 16:9, PAR 1:1, color profile: 1-1-1, chroma location: left
[07:46:53] libhb: scan thread found 1 valid title(s)
HB [07:46:53] Starting work at: Tue Aug 27 07:46:53 2024
[07:46:53] 1 job(s) to process
[07:46:53] json job:
{
  "Audio": {
    "AudioList": [
      {
        "Bitrate": 160,
        "DRC": 0,
        "Encoder": "copy",
        "Gain": 0,
        "Mixdown": 4,
        "NormalizeMixLevel": false,
        "Samplerate": 48000,
        "Track": 0,
        "DitherMethod": 0
      }
    ],
    "CopyMask": [
      "copy:aac",
      "copy:ac3",
      "copy:eac3",
      "copy:truehd",
      "copy:dts",
      "copy:dtshd",
      "copy:mp2",
      "copy:mp3",
      "copy:flac",
      "copy:opus"
    ],
    "FallbackEncoder": "av_aac"
  },
  "Destination": {
    "ChapterList": [
      {
        "Name": "Chapter 1"
      }
    ],
    "ChapterMarkers": true,
    "AlignAVStart": false,
    "File": "c:\\temp\\editedfilename_1080p (Encoded).part.mp4",
    "Options": {
      "IpodAtom": false,
      "Optimize": false
    },
    "Mux": "av_mp4"
  },
  "Filters": {
    "FilterList": [
      {
        "ID": 20,
        "Settings": {
          "crop-bottom": "0",
          "crop-left": "0",
          "crop-right": "0",
          "crop-top": "0",
          "height": "404",
          "width": "720"
        }
      }
    ]
  },
  "PAR": {
    "Num": 1,
    "Den": 1
  },
  "Metadata": {
    "Comment": "Downloaded",
    "Name": "Downloaded"
  },
  "SequenceID": 0,
  "Source": {
    "Angle": 0,
    "Range": {
      "Type": "chapter",
      "Start": 1,
      "End": 1
    },
    "Title": 1,
    "Path": "c:\\temp\\editedfilename_1080p.mp4",
    "HWDecode": 0,
    "KeepDuplicateTitles": false
  },
  "Subtitle": {
    "Search": {
      "Burn": false,
      "Default": false,
      "Enable": false,
      "Forced": false
    },
    "SubtitleList": []
  },
  "Video": {
    "Encoder": "nvenc_h265",
    "Level": "auto",
    "MultiPass": false,
    "Turbo": false,
    "ColorMatrixCode": 0,
    "Options": "rc-lookahead=10",
    "Preset": "medium",
    "Profile": "auto",
    "Quality": 32,
    "QSV": {
      "Decode": false
    },
    "HardwareDecode": 4
  }
}
[07:46:54] Starting Task: Encoding Pass
[07:46:54] Auto Passthru: allowed codecs are AAC, AC3, E-AC3, TrueHD, DTS, DTS-HD, MP2, MP3, FLAC, Opus
[07:46:54] Auto Passthru: fallback is AAC (avcodec)
[07:46:54] Auto Passthru: using AAC Passthru for track 1
[07:46:54] work: only 1 chapter, disabling chapter markers
[07:46:54] job configuration:
[07:46:54]  * source
[07:46:54]    + c:\temp\editedfilename_1080p.mp4
[07:46:54]    + title 1, chapter(s) 1 to 1
[07:46:54]    + container: mov,mp4,m4a,3gp,3g2,mj2
[07:46:54]    + data rate: 6202 kbps
[07:46:54]  * destination
[07:46:54]    + c:\temp\editedfilename_1080p (Encoded).part.mp4
[07:46:54]    + container: MPEG-4 (libavformat)
[07:46:54]  * video track
[07:46:54]    + decoder: h264 8-bit (yuv420p)
[07:46:54]      + bitrate 6003 kbps
[07:46:54]    + filters
[07:46:54]      + Crop and Scale (width=720:height=404:crop-top=0:crop-bottom=0:crop-left=0:crop-right=0)
[07:46:54]        + source: 1920 * 1080, crop (0/0/0/0): 1920 * 1080, scale: 720 * 404
[07:46:54]    + Output geometry
[07:46:54]      + storage dimensions: 720 x 404
[07:46:54]      + pixel aspect ratio: 1 : 1
[07:46:54]      + display dimensions: 720 x 404
[07:46:54]    + encoder: H.265 (NVEnc)
[07:46:54]      + preset:  medium
[07:46:54]      + options: rc-lookahead=10
[07:46:54]      + profile: auto
[07:46:54]      + level:   auto
[07:46:54]      + quality: 32.00 (CQ)
[07:46:54]      + color profile: 1-1-1
[07:46:54]      + color range: tv
[07:46:54]      + chroma location: left
[07:46:54]  * audio track 1
[07:46:54]    + decoder: English (AAC LC, 2.0 ch, 189 kbps) (track 1, id 0x1)
[07:46:54]      + bitrate: 189 kbps, samplerate: 48000 Hz
[07:46:54]    + AAC Passthru
[07:46:54] sync: expecting 50783 video frames
[07:46:54] encavcodecInit: H.265 (Nvidia NVENC)
[07:46:54] encavcodec: encoding at rc=vbr, 32.00
[07:46:54] encavcodec: encoding with stored aspect 1/1
HB [07:46:54] sync: first pts audio 0x1 is 0
[07:46:54] sync: first pts video is 3600
[07:46:54] sync: "Chapter 1" (1) at frame 1 time 3600
HB [07:48:25] reader: done. 1 scr changes
HB [07:48:26] work: average encoding speed for job is 554.916931 fps
HB [07:48:26] aac-decoder done: 47609 frames, 0 decoder errors
[07:48:26] h264-decoder done: 50781 frames, 0 decoder errors
[07:48:26] sync: got 50781 frames, 50783 expected
[07:48:26] sync: framerate min 50.000 fps, max 50.000 fps, avg 50.000 fps
HB [07:48:26] mux: track 0, 50781 frames, 92821091 bytes, 731.11 kbps, fifo 8192
[07:48:26] mux: track 1, 47609 frames, 24054252 bytes, 189.46 kbps, fifo 8192
[07:48:26] Finished work at: Tue Aug 27 07:48:26 2024
[07:48:26] libhb: work result = 0
VC [07:48:26] Job completed (Elapsed Time: 1m 34s)
HB Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at HandBrake.Interop.Interop.HandBrakeInstance.Dispose(Boolean)
   at HandBrake.Interop.Interop.HandBrakeInstance.Dispose()
   at VidCoderWorker.HandBrakeWorkerBase`1+<<TearDownWorker>b__30_0>d[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at VidCoderWorker.HandBrakeWorkerBase`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<TearDownWorker>b__30_0()
   at System.Threading.Tasks.Task`1[[System.__Canon, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
```

**Comment by wkearney99** [comment]
![vidcoder unexpected parameters](https://github.com/user-attachments/assets/5416f7a6-65dd-487f-bc43-6a190a91029c)

**Comment by wkearney99** [comment]
re-running the queue with the same files did not reproduce the error.

**Comment by wkearney99** [comment]
I've had it happen again, with different files, and wonder if it might be something to do with the Handbrake subsystem being called and available CPU/RAM resources.  The machine's pretty busy most of the time and that's when the errors have occurred. I have Vidcoder settings to a max of 2 jobs at Normal priority.  I do not have the [] checked for Capping simultaneous encodes.  I have the CPU throttling set to 50%.

I'm using an RTX3070 and when VC is running I see it utilizing two of the four GPUs on it.  I was not running anything else that'd have been using the other two GPUs (and they showed as otherwise idle in the task manager Performance tab).

I have run thousands of videos through this process and have never seen this error before.  I don't know if it's related to anything recent in Vidcoder or not.

**Comment by RandomEngy** [comment]
Thanks for the report. This looks like an issue within the HandBrake core. Did the encode actually fail? It looks like it happened during cleanup after the encode completed.

**Comment by wkearney99** [comment]
The encodes succeed, but the process gets halted until the modal error is dismissed.
