### ISSUE TITLE
System.Data.SQLite.SQLiteException: disk I/O errordisk I/O error

### ISSUE THREAD

**Issue by sirjohn771103** [RandomEngy/VidCoder#1316]
### What were you doing when VidCoder crashed?

VidCoder 11.6 béta Portable
code = IoErr (10), message = System.Data.SQLite.SQLiteException (0x87AF045D): disk I/O error
disk I/O error
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at VidCoderCommon.Model.DatabaseConfig.SetInternal(String configName, String configValue, SQLiteConnection connection) in C:\git\VidCoder\VidCoderCommon\Model\DatabaseConfig.cs:line 133
   at VidCoderCommon.Model.DatabaseConfig.Set[T](String configName, T value, SQLiteConnection connection) in C:\git\VidCoder\VidCoderCommon\Model\DatabaseConfig.cs:line 84
   at VidCoder.Config.Set[T](String key, T value) in C:\git\VidCoder\VidCoder\Model\Config\Config.cs:line 150
   at VidCoder.Config.set_EncodeJobs2(String value) in C:\git\VidCoder\VidCoder\Model\Config\Config.cs:line 181
   at VidCoder.Model.EncodeJobStorage.set_EncodeJobs(IList`1 value) in C:\git\VidCoder\VidCoder\Model\EncodeJobStorage.cs:line 27
   at VidCoder.Services.ProcessingService.SaveEncodeQueue() in C:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 2832
   at VidCoder.Services.ProcessingService.<.ctor>b__24_35(IChangeSet`1 changeSet) in C:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 116
   at System.Reactive.AutoDetachObserver`1.OnNextCore(T value) in /_/Rx.NET/Source/src/System.Reactive/Internal/AutoDetachObserver.cs:line 58
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 136
   at DynamicData.SourceList`1.InvokeNext(IChangeSet`1 changes) in D:\a\DynamicData\DynamicData\src\DynamicData\List\SourceList.cs:line 166
   at DynamicData.SourceList`1.Edit(Action`1 updateAction) in D:\a\DynamicData\DynamicData\src\DynamicData\List\SourceList.cs:line 139
   at DynamicData.SourceListEditConvenienceEx.Remove[T](ISourceList`1 source, T item) in D:\a\DynamicData\DynamicData\src\DynamicData\List\SourceListEditConvenienceEx.cs:line 155
   at VidCoder.Services.ProcessingService.<>c__DisplayClass249_0.<OnEncodeCompleted>b__0() in C:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 2332
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Crash details

```text
VidCoder 11.6 béta Portable
code = IoErr (10), message = System.Data.SQLite.SQLiteException (0x87AF045D): disk I/O error
disk I/O error
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at VidCoderCommon.Model.DatabaseConfig.SetInternal(String configName, String configValue, SQLiteConnection connection) in C:\git\VidCoder\VidCoderCommon\Model\DatabaseConfig.cs:line 133
   at VidCoderCommon.Model.DatabaseConfig.Set[T](String configName, T value, SQLiteConnection connection) in C:\git\VidCoder\VidCoderCommon\Model\DatabaseConfig.cs:line 84
   at VidCoder.Config.Set[T](String key, T value) in C:\git\VidCoder\VidCoder\Model\Config\Config.cs:line 150
   at VidCoder.Config.set_EncodeJobs2(String value) in C:\git\VidCoder\VidCoder\Model\Config\Config.cs:line 181
   at VidCoder.Model.EncodeJobStorage.set_EncodeJobs(IList`1 value) in C:\git\VidCoder\VidCoder\Model\EncodeJobStorage.cs:line 27
   at VidCoder.Services.ProcessingService.SaveEncodeQueue() in C:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 2832
   at VidCoder.Services.ProcessingService.<.ctor>b__24_35(IChangeSet`1 changeSet) in C:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 116
   at System.Reactive.AutoDetachObserver`1.OnNextCore(T value) in /_/Rx.NET/Source/src/System.Reactive/Internal/AutoDetachObserver.cs:line 58
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 136
   at DynamicData.SourceList`1.InvokeNext(IChangeSet`1 changes) in D:\a\DynamicData\DynamicData\src\DynamicData\List\SourceList.cs:line 166
   at DynamicData.SourceList`1.Edit(Action`1 updateAction) in D:\a\DynamicData\DynamicData\src\DynamicData\List\SourceList.cs:line 139
   at DynamicData.SourceListEditConvenienceEx.Remove[T](ISourceList`1 source, T item) in D:\a\DynamicData\DynamicData\src\DynamicData\List\SourceListEditConvenienceEx.cs:line 155
   at VidCoder.Services.ProcessingService.<>c__DisplayClass249_0.<OnEncodeCompleted>b__0() in C:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 2332
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by RandomEngy** [comment]
Looks like your hard drive failed to read the data. VidCoder can't operate when the hardware/OS fails to read from disk.

**Comment by sirjohn771103** [comment]
thank you. i close this.
