### ISSUE TITLE
VidCoder won't start after installing latest update.

### ISSUE THREAD

**Issue by MarylinC** [RandomEngy/VidCoder#174]
After installing the latest update last night, when I tried starting it up for the first time I got some kind of exception error and the program won't start.   I have pasted below the details of the error message so hopefully this will help with dianosing the issue with the new update.

------------------------------------------------
System.TypeInitializationException: The type initializer for 'VidCoder.Model.Database' threw an exception. ---> System.Data.SQLite.SQLiteException: Abort due to constraint violation
column name is not unique
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at VidCoder.Model.Database.ExecuteNonQuery(String query, SQLiteConnection connection) in D:\docs\projects\VidCoder\VidCoder\Model\Database.cs:line 700
   at VidCoder.Model.Database.UpgradeDatabaseTo35() in D:\docs\projects\VidCoder\VidCoder\Model\Database.cs:line 443
   at VidCoder.Model.Database..cctor() in D:\docs\projects\VidCoder\VidCoder\Model\Database.cs:line 85
   --- End of inner exception stack trace ---
   at VidCoder.Model.Database.get_Connection()
   at VidCoder.App.OnStartup(StartupEventArgs e) in D:\docs\projects\VidCoder\VidCoder\App.xaml.cs:line 83
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
If you have your old %appdata%\VidCoder\VidCoder.sqlite file I can take a look at it.

**Comment by MarylinC** [comment]
Thanks for responding but I no longer have it as I did a full uninstall including all settings and preferances before installing the latest version again by downloading a fresh copy from the site.

**Comment by batjac7** [comment]
Mine (non beta) don't start either. Will email sqlite to notifications at github.

- - - 
System.TypeInitializationException: The type initializer for 'VidCoder.Model.Database' threw an exception. ---> System.Data.SQLite.SQLiteException: Abort due to constraint violation
column name is not unique
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at VidCoder.Model.Database.ExecuteNonQuery(String query, SQLiteConnection connection) in D:\docs\projects\VidCoder\VidCoder\Model\Database.cs:line 700
   at VidCoder.Model.Database.UpgradeDatabaseTo35() in D:\docs\projects\VidCoder\VidCoder\Model\Database.cs:line 443
   at VidCoder.Model.Database..cctor() in D:\docs\projects\VidCoder\VidCoder\Model\Database.cs:line 85
   --- End of inner exception stack trace ---
   at VidCoder.Model.Database.get_Connection()
   at VidCoder.App.OnStartup(StartupEventArgs e) in D:\docs\projects\VidCoder\VidCoder\App.xaml.cs:line 83
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Hmm not sure what you mean by "email to notifications at GitHub". Have not received the file. Did you send to david.rickard@gmail.com ?
