### ISSUE TITLE
Crashes at startup, Windows Creators Update

### ISSUE THREAD

**Issue by AndruwGX** [RandomEngy/VidCoder#195]
Every time I start Vidcoder it automatically crashes, no exceptions. Doesn't work in the new Windows update, perio
![vidcoder](https://cloud.githubusercontent.com/assets/27390914/24986333/a9987622-1fc7-11e7-9cd9-febfb2bbc6b3.JPG)
d. Any help will be appreciated.

**Comment by RandomEngy** [comment]
Hmm. You running x86 or x64 version of VidCoder? I have not seen this crash on either machine that has gotten the creator's update; so I wonder if something got messed up in .NET during the OS upgrade for you.

**Comment by sr55** [comment]
Disable RivaTuner, MSI Afterburner or any other application that hooks d3d9.dll for monitoring. 

It's a driver/os bug.

**Comment by Madekuji** [comment]
Creators Update also screwed up Vidcoder for me, but it pops up an error message as well:
`System.TypeInitializationException: The type initializer for 'VidCoder.Ioc' threw an exception. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at Microsoft.Practices.Unity.Utility.Guard.InstanceIsAssignable(Type assignmentTargetType, Object assignmentInstance, String argumentName)
   at Microsoft.Practices.Unity.UnityContainer.RegisterInstance(Type t, String name, Object instance, LifetimeManager lifetime)
   at Microsoft.Practices.Unity.UnityContainerExtensions.RegisterInstance[TInterface](IUnityContainer container, TInterface instance, LifetimeManager lifetimeManager)
   at Microsoft.Practices.Unity.UnityContainer.AddExtension(UnityContainerExtension extension)
   at Microsoft.Practices.Unity.UnityContainer..ctor(UnityContainer parent)
   at Microsoft.Practices.Unity.UnityContainer..ctor()
   at VidCoder.Ioc..cctor() in D:\docs\projects\VidCoder\VidCoder\Utilities\Ioc.cs:line 15
   --- End of inner exception stack trace ---
   at VidCoder.Ioc.Get[T]()
   at VidCoder.App.OnStartup(StartupEventArgs e) in D:\docs\projects\VidCoder\VidCoder\App.xaml.cs:line 102
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
`
Tried using all versions of Vidcoder, no luck.
