### ISSUE TITLE
Windows 10 Creators Update-caused crash

### ISSUE THREAD

**Issue by Madekuji** [RandomEngy/VidCoder#199]
Creators Update also screwed up Vidcoder for me, but it pops up an error message as well:
`System.TypeInitializationException: The type initializer for 'VidCoder.Ioc' threw an exception. ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown. at Microsoft.Practices.Unity.Utility.Guard.InstanceIsAssignable(Type assignmentTargetType, Object assignmentInstance, String argumentName) at Microsoft.Practices.Unity.UnityContainer.RegisterInstance(Type t, String name, Object instance, LifetimeManager lifetime) at Microsoft.Practices.Unity.UnityContainerExtensions.RegisterInstance[TInterface](IUnityContainer container, TInterface instance, LifetimeManager lifetimeManager) at Microsoft.Practices.Unity.UnityContainer.AddExtension(UnityContainerExtension extension) at Microsoft.Practices.Unity.UnityContainer..ctor(UnityContainer parent) at Microsoft.Practices.Unity.UnityContainer..ctor() at VidCoder.Ioc..cctor() in D:\docs\projects\VidCoder\VidCoder\Utilities\Ioc.cs:line 15 --- End of inner exception stack trace --- at VidCoder.Ioc.Get[T]() at VidCoder.App.OnStartup(StartupEventArgs e) in D:\docs\projects\VidCoder\VidCoder\App.xaml.cs:line 102 at System.Windows.Application.<.ctor>b__1_0(Object unused) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`
Tried using all versions of Vidcoder, no luck.

**Comment by RandomEngy** [comment]
How much free memory does your system have when this fails?

**Comment by Madekuji** [comment]
2.0GB/4GB. But the message is different now when I reinstalled it:
`System.TypeInitializationException: The type initializer for 'VidCoder.Ioc' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Globalization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.Practices.Unity.Utility.Guard.InstanceIsAssignable(Type assignmentTargetType, Object assignmentInstance, String argumentName)
   at Microsoft.Practices.Unity.UnityContainer.RegisterInstance(Type t, String name, Object instance, LifetimeManager lifetime)
   at Microsoft.Practices.Unity.UnityContainerExtensions.RegisterInstance[TInterface](IUnityContainer container, TInterface instance, LifetimeManager lifetimeManager)
   at Microsoft.Practices.Unity.UnityContainer.AddExtension(UnityContainerExtension extension)
   at Microsoft.Practices.Unity.UnityContainer..ctor(UnityContainer parent)
   at Microsoft.Practices.Unity.UnityContainer..ctor()
   at VidCoder.Ioc..cctor() in D:\docs\projects\VidCoder\VidCoder\Utilities\Ioc.cs:line 15
   --- End of inner exception stack trace ---
   at VidCoder.Ioc.Get[T]()
   at VidCoder.App.OnStartup(StartupEventArgs e) in D:\docs\projects\VidCoder\VidCoder\App.xaml.cs:line 102
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
`

**Comment by RandomEngy** [comment]
Not sure what's going on here. Looks like the .NET framework is corrupted or something.
