### ISSUE TITLE
VidCoder 2.55 stopped transcoding

### ISSUE THREAD

**Issue by IttoUsagi** [RandomEngy/VidCoder#216]
In the middle of a batch transcoding project VidCoder stopped transcoding. Attempts to re-initialize the batch project for the remaining files yielded the following error message:

System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at VidCoder.Services.Windows.WindowManager.PrepareWindowForOpen(Object viewModel, Object ownerViewModel, Boolean userInitiated, Boolean isDialog) in D:\docs\projects\VidCoder\VidCoder\Services\Windows\WindowManager.cs:line 402
   at VidCoder.Services.Windows.WindowManager.OpenDialog(Object viewModel, Object ownerViewModel) in D:\docs\projects\VidCoder\VidCoder\Services\Windows\WindowManager.cs:line 169
   at VidCoder.Services.ProcessingService.QueueMultiple(IEnumerable`1 sourcePaths) in D:\docs\projects\VidCoder\VidCoder\Services\ProcessingService.cs:line 987
   at VidCoder.ViewModel.MainViewModel.HandleDropAsPaths(IList`1 itemList) in D:\docs\projects\VidCoder\VidCoder\ViewModel\MainViewModel.cs:line 559
   at VidCoder.ViewModel.MainViewModel.<>c__DisplayClass41_0.<HandlePaths>b__0() in D:\docs\projects\VidCoder\VidCoder\ViewModel\MainViewModel.cs:line 541
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Thanks for the report. Should be fixed in 2.56.

**Comment by IttoUsagi** [comment]
Thanks!
