### ISSUE TITLE
v2.17 beta startup error

### ISSUE THREAD

**Issue by BugMagnet** [RandomEngy/VidCoder#24]
windows 7 pro

System.TypeInitializationException: The type initializer for 'VidCoder.Model.Database' threw an exception. ---> System.InvalidOperationException: There was an error reflecting type 'VidCoder.Model.Picker'. ---> System.InvalidOperationException: Cannot serialize member 'VidCoder.Model.Picker.AudioLanguageCodes' of type 'System.Collections.Generic.IList`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]', see inner exception for more details. ---> System.NotSupportedException: Cannot serialize member VidCoder.Model.Picker.AudioLanguageCodes of type System.Collections.Generic.IList`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] because it is an interface.
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.StructModel.CheckSupportedMember(TypeDesc typeDesc, MemberInfo member, Type type)
   at System.Xml.Serialization.StructModel.GetPropertyModel(PropertyInfo propertyInfo)
   at System.Xml.Serialization.StructModel.GetFieldModel(MemberInfo memberInfo)
   at System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(StructMapping mapping, StructModel model, Boolean openModel, String typeName, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportStructLikeMapping(StructModel model, String ns, Boolean openModel, XmlAttributes a, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportElement(TypeModel model, XmlRootAttribute root, String defaultNamespace, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(Type type, XmlRootAttribute root, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
   at VidCoder.Model.Database.UpgradeDatabaseTo28(Int32 oldDatabaseVersion) in D:\docs\projects\VidCoder\VidCoder\Model\Database.cs:line 228
   at VidCoder.Model.Database..cctor() in D:\docs\projects\VidCoder\VidCoder\Model\Database.cs:line 68
   --- End of inner exception stack trace ---
   at VidCoder.Model.Database.get_Connection()
   at VidCoder.App.OnStartup(StartupEventArgs e) in D:\docs\projects\VidCoder\VidCoder\App.xaml.cs:line 74
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

===============

Not sure if is the same but this was from v2.16:

System.TypeInitializationException: The type initializer for 'VidCoder.Model.Database' threw an exception. ---> System.InvalidOperationException: There was an error reflecting type 'VidCoder.Model.Picker'. ---> System.InvalidOperationException: Cannot serialize member 'VidCoder.Model.Picker.AudioLanguageCodes' of type 'System.Collections.Generic.IList`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]', see inner exception for more details. ---> System.NotSupportedException: Cannot serialize member VidCoder.Model.Picker.AudioLanguageCodes of type System.Collections.Generic.IList`1[[System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] because it is an interface.
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.StructModel.CheckSupportedMember(TypeDesc typeDesc, MemberInfo member, Type type)
   at System.Xml.Serialization.StructModel.GetPropertyModel(PropertyInfo propertyInfo)
   at System.Xml.Serialization.StructModel.GetFieldModel(MemberInfo memberInfo)
   at System.Xml.Serialization.XmlReflectionImporter.InitializeStructMembers(StructMapping mapping, StructModel model, Boolean openModel, String typeName, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportStructLikeMapping(StructModel model, String ns, Boolean openModel, XmlAttributes a, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportElement(TypeModel model, XmlRootAttribute root, String defaultNamespace, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(Type type, XmlRootAttribute root, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
   at VidCoder.Model.Database.UpgradeDatabaseTo28(Int32 oldDatabaseVersion) in D:\docs\projects\VidCoder\VidCoder\Model\Database.cs:line 228
   at VidCoder.Model.Database..cctor() in D:\docs\projects\VidCoder\VidCoder\Model\Database.cs:line 68
   --- End of inner exception stack trace ---
   at VidCoder.Model.Database.get_Connection()
   at VidCoder.App.OnStartup(StartupEventArgs e) in D:\docs\projects\VidCoder\VidCoder\App.xaml.cs:line 74
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Fixed in 2.18 Beta.

**Comment by BugMagnet** [comment]
v2.18

System.TypeInitializationException: The type initializer for 'VidCoder.Model.Database' threw an exception. ---> System.InvalidOperationException: There is an error in XML document (1, 1). ---> System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlReader.MoveToContent()
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPicker.Read7_Picker()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at VidCoder.Model.PickerStorage.ParsePickerXml(String pickerXml, XmlSerializer serializer) in D:\docs\projects\VidCoder\VidCoder\Model\PickerStorage.cs:line 38
   at VidCoder.Model.Database.UpgradeDatabaseTo28(Int32 oldDatabaseVersion) in D:\docs\projects\VidCoder\VidCoder\Model\Database.cs:line 230
   at VidCoder.Model.Database..cctor() in D:\docs\projects\VidCoder\VidCoder\Model\Database.cs:line 68
   --- End of inner exception stack trace ---
   at VidCoder.Model.Database.get_Connection()
   at VidCoder.App.OnStartup(StartupEventArgs e) in D:\docs\projects\VidCoder\VidCoder\App.xaml.cs:line 74
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Could you send me your %appdata%\VidCoder-Beta\VidCoder.sqlite file so I can see what exactly is wrong?

**Comment by BugMagnet** [comment]
Thinking back.. If I recall correctly... I opened the beta to test. I hadn't used it in a few days and in the interim, I had changed/deleted the target folder. When I opened the beta, it hung with some message like 'can't find dir' and it forze. I could not pause/stop or even x-out of that session. I had to fore-kill the process with my TaskInfo system monitor utility.

After that I did a 'complete' program removal, including all data and settings and reinstalled. It is on these 'fresh install' attempts that I am getting there error. It appears that the beta is reading in the data from my stable version folders.

**Comment by RandomEngy** [comment]
The beta shouldn't be reading directly from your stable version folder... it should be copying it from the stable version folder and then trying to upgrade it. Could you send your stable VidCoder.sqlite ( %appdata%\VidCoder\VidCoder.sqlite ) so I can see if the DB upgrade happens correctly?

**Comment by BugMagnet** [comment]
Is there a way I can send that file to you privately?

**Comment by RandomEngy** [comment]
Email to david.rickard@gmail.com

**Comment by BugMagnet** [comment]
for now I did a reinstall tricking the beta into not importing any existing config or data.
On first start, I tried to load a batch of files and it hung 1/2 way through. So starting off easier..

On start: 641 handles
Loading/scanning 1 files: 967 handles
adding to queue: 955 handles
encoding: 995 handles
completed: 922 handles (start +280)
loaded 5 more: 1050 handles and these began encoding.

Attempted to load a batch of 32 more files.. Scanning progress hung at about 85% and encoding progress seemed to halt also. Handles went up to 1041, and after a while the progress creeped forward and the add to queue finished. Seemed like this took at least 10 minutes. 1000 Handles. ETA 5 hours.

Attempting to add 30 more files to queue and this time they loaded in just 1 minute.
1002 handles -  ETA 8 hours.

Adding 67 more files: loaded in a couple minutes.  Not sure why it hung a couple times earlier trying to load batches of files in this same session, but seems to be working smoothly now.
992 handles - ETA 18 hours. 

Looks like you got a handle on the handles leak in v2.18beta  :)

I'll keep an eye on they file loading quirk.

**Comment by RandomEngy** [comment]
Great! Thanks for sending that file; I've figured out what was going wrong and will fix later today.

**Comment by BugMagnet** [comment]
I have to give it to you. You seem to know your stuff . Glad people like you are out there and on our side.

**Comment by RandomEngy** [comment]
Fixed in 2.19 Beta.

**Comment by BugMagnet** [comment]
confirmed
v2.19 install importing data from the stable version now starts and runs with it.
and it has less than 800 handles open with 60 files loaded and encoding
:)
