### ISSUE TITLE
File Path Error

### ISSUE THREAD

**Issue by amb9800** [RandomEngy/VidCoder#293]
I'm getting the file path error below (followed by app crash) when I try to encode some DVDs I have saved in a network share. The MP4 is the destination path (which is the same folder as the source VOBs).

> System.IO.FileNotFoundException: Could not find file '\\\mediaserver\G\Lectures\Lecture at Central Town Hall 3\DVD 3\1.mp4'.
File name: '\\\mediaserver\G\Lectures\Lecture at Central Town Hall 3\DVD 3\1.mp4'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.get_Length()
   at VidCoder.Services.ProcessingService.<>c__DisplayClass175_0.<OnEncodeCompleted>b__0() in D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1542
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**EDIT: turned out it was just a file permissions issue (friendlier / more useful error message would be nice, though).**

**Comment by RandomEngy** [comment]
Yeah I have a fix ready in the next version. It definitely shouldn't crash like that.

**Comment by RandomEngy** [comment]
Should be fixed in 3.5 Beta.
