### ISSUE TITLE
VidCoder Crash

### ISSUE THREAD

**Issue by macmcd47** [RandomEngy/VidCoder#329]
VidCoder crashed at 0.0% converting an mkv file.

System.NullReferenceException: Object reference not set to an instance of an object.
   at VidCoder.RemoteEncodeProxy.StopAndWait() in D:\git\VidCoder\VidCoder\Services\HandBrakeProxy\RemoteEncodeProxy.cs:line 99
   at VidCoder.ViewModel.MainViewModel.OnClosing() in D:\git\VidCoder\VidCoder\ViewModel\MainViewModel.cs:line 766
   at VidCoder.Services.Windows.WindowManager.OnClosing(Window window, Boolean userInitiated) in D:\git\VidCoder\VidCoder\Services\Windows\WindowManager.cs:line 518
   at VidCoder.Services.Windows.WindowManager.OnClosingHandler(Object sender, CancelEventArgs e) in D:\git\VidCoder\VidCoder\Services\Windows\WindowManager.cs:line 499
   at System.Windows.Window.OnClosing(CancelEventArgs e)
   at System.Windows.Window.WmClose()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Fixed in 3.11 Beta.
