### ISSUE TITLE
Version 4.1. Windows 7 The program does not start. Version 4.0-Works.

### ISSUE THREAD

**Issue by spikaspika** [RandomEngy/VidCoder#342]
Start the program. 
Next-the following window with the message:

Microsoft.Practices.Unity.ResolutionFailedException: Resolution of the dependency failed, type = "VidCoder.Services.IUpdater", name = "(none)".
Exception occurred while: Calling constructor VidCoder.Services.Updater().
Exception is: ResolutionFailedException - Resolution of the dependency failed, type = "VidCoder.Services.IAppLogger", name = "(none)".
Exception occurred while: while resolving.
Exception is: FormatException - Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
-----------------------------------------------
At the time of the exception, the container was:

  Resolving VidCoder.Services.AppLogger,(none) (mapped from VidCoder.Services.IAppLogger, (none))

-----------------------------------------------
At the time of the exception, the container was:

  Resolving VidCoder.Services.Updater,(none) (mapped from VidCoder.Services.IUpdater, (none))
  Calling constructor VidCoder.Services.Updater()
 ---> Microsoft.Practices.Unity.ResolutionFailedException: Resolution of the dependency failed, type = "VidCoder.Services.IAppLogger", name = "(none)".
Exception occurred while: while resolving.
Exception is: FormatException - Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
-----------------------------------------------
At the time of the exception, the container was:

  Resolving VidCoder.Services.AppLogger,(none) (mapped from VidCoder.Services.IAppLogger, (none))
 ---> System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at VidCoder.Utilities.get_VersionString() in D:\git\VidCoder\VidCoder\Utilities\Utilities.cs:line 84
   at VidCoder.Services.AppLogger..ctor(IAppLogger parent, String baseFileName) in D:\git\VidCoder\VidCoder\Services\AppLogger.cs:line 68
   at VidCoder.Ioc.<>c.<.cctor>b__0_0(IUnityContainer c) in D:\git\VidCoder\VidCoder\Utilities\Ioc.cs:line 30
   at Microsoft.Practices.ObjectBuilder2.FactoryDelegateBuildPlanPolicy.BuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
   at Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object existing, String name, IEnumerable`1 resolverOverrides)
   --- End of inner exception stack trace ---
   at Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object existing, String name, IEnumerable`1 resolverOverrides)
   at Microsoft.Practices.Unity.UnityContainer.Resolve(Type t, String name, ResolverOverride[] resolverOverrides)
   at Microsoft.Practices.Unity.UnityContainerExtensions.Resolve[T](IUnityContainer container, ResolverOverride[] overrides)
   at lambda_method(Closure , IBuilderContext )
   at Microsoft.Practices.ObjectBuilder2.DynamicBuildPlanGenerationContext.<>c__DisplayClass1.<GetBuildMethod>b__0(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.BuildPlanStrategy.PreBuildUp(IBuilderContext context)
   at Microsoft.Practices.ObjectBuilder2.StrategyChain.ExecuteBuildUp(IBuilderContext context)
   at Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object existing, String name, IEnumerable`1 resolverOverrides)
   --- End of inner exception stack trace ---
   at Microsoft.Practices.Unity.UnityContainer.DoBuildUp(Type t, Object existing, String name, IEnumerable`1 resolverOverrides)
   at Microsoft.Practices.Unity.UnityContainer.Resolve(Type t, String name, ResolverOverride[] resolverOverrides)
   at Microsoft.Practices.Unity.UnityContainerExtensions.Resolve[T](IUnityContainer container, ResolverOverride[] overrides)
   at VidCoder.App.OnStartup(StartupEventArgs e) in D:\git\VidCoder\VidCoder\App.xaml.cs:line 108
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Agree to closed programs.

**Comment by tfanion** [comment]
Hi. Same issue since 4.1 update. Maybe this could help :
My PC is configured in "French", so I installed "En-US" language and switched the "windows language" to english, to get the crash report in english. And ... Vidcoder started without crashing. Switched back to French as "windows language", without uninstalling En-US : crash is back.

**Comment by spikaspika** [comment]
Removed all languages from the program folder.
Vidcoder started the second time.
Works in English.
Probably a problem with localization.

**Comment by spikaspika** [comment]
Tried to return language packs to the Programs folder.
The program is refusing to run, works only in English.
This information may be useful for you.
Sincerely.

**Comment by spikaspika** [comment]
Thanks for the promptness, it's just brilliant!
I'm excited. Now work for the translation of the interface, some items of the top menu are not translated into Russian. This is at least about the other languages do not know.
Thanks again.
