### ISSUE TITLE
4.2 Beta crash on startup (FileNotFound - System.Net.Http) [English]

### ISSUE THREAD

**Issue by forteefi** [RandomEngy/VidCoder#343]
Just in-place upgraded to 4.2 from 4.0 (the version that introduced the ribbon). Now getting a crash on startup about a missing file or assembly.

Windows 10 x64 1709 English

Tried uninstall and reinstall of VidCoder to no avail. Have not tried deleting preferences yet, I'd rather keep those if possible since it takes awhile to recreate them.

**EDIT** Version 4.1 also crashes on startup. Version 4.0 works.
```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at VidCoder.Services.Updater.<StartBackgroundUpdate>b__23_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VidCoder.Services.Updater.<StartBackgroundUpdate>d__23.MoveNext() in D:\git\VidCoder\VidCoder\Services\Updater.cs:line 247
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

```

**Comment by RandomEngy** [comment]
Thanks. You're using the installer version, then?

**Comment by forteefi** [comment]
Yes, installer version. Just edited my comment. 4.1 also crashes, but 4.0 works.

**Comment by Ghastor** [comment]
me too.
System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Impossibile trovare il file specificato.
File name: 'System.Net.Http, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at VidCoder.Services.Updater.<StartBackgroundUpdate>b__23_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VidCoder.Services.Updater.<StartBackgroundUpdate>d__23.MoveNext() in D:\git\VidCoder\VidCoder\Services\Updater.cs:line 247
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

AVV: la registrazione dell'associazione di assembly è disattivata.
Per abilitare la registrazione degli errori di associazione di assembly, impostare il valore del Registro di sistema [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) su 1.
Nota: alcune penalità di prestazione sono associate alla registrazione degli errori di associazione di assembly.
Per disattivare la funzionalità, rimuovere il valore del Registro di sistema [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by RandomEngy** [comment]
Give 4.3 Beta a shot.

**Comment by forteefi** [comment]
Hi, thanks for your quick reply and work. I've installed 4.3 Beta and it opens without issue.

**Comment by linucksrox** [comment]
Thanks! It's working for me now.
