### ISSUE TITLE
Exception on loading source

### ISSUE THREAD

**Issue by Plutocratic** [RandomEngy/VidCoder#367]
OK, onto the next one.

Loading a fairly random source file for testing purposes led to the following exception messages being generated immediately following the "scanning source" phase, after the basic statistics of the source material had been painted in the main window.

I confirm that this exception does not occur with 4.4, although 4.4 does not seem able to get much further with the actual work – some of the output dimension statistics are -ve, so something is clearly going wrong.

I can upload the vid in question to your PCloud if this will be useful.

`ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case. ---> System.ArgumentException: '-73.4201345622702' is not a valid value for property 'Width'.
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at VidCoder.View.Main.<OnDataContextChanged>b__19_8(OutputSizeInfo size) in D:\git\VidCoder\VidCoder\View\Main.xaml.cs:line 283
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.DistinctUntilChanged`2._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Switch`1._.InnerObserver.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Cast`2._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.EnumerableSelector._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Buffer`2.Boundaries._.BufferClosingObserver.OnNext(TBufferClosing value)
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)
   at System.Reactive.Observer`1.OnNext(T value)
   at ReactiveUI.IReactiveObjectExtensions.ExtensionState`1.notifyObservable[T](TSender rxObj, T item, ISubject`1 subject)
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass0_0.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

**Comment by RandomEngy** [comment]
Yes, a source file is always handy when debugging. I'll look into it, thanks.

**Comment by RandomEngy** [comment]
Should be fixed in 4.9 Beta.

**Comment by Plutocratic** [comment]
4.9 checked and OK
