### ISSUE TITLE
4.8 Beta crashing at start

### ISSUE THREAD

**Issue by iamjaydear** [RandomEngy/VidCoder#368]
Can't start at all :(
===========================================
VidCoder Beta: VidCoder.exe - Application Error
The exception unknown software exception (0xe0434352) occurred in
the application at location 0x537d95fc.
===========================================
System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at VidCoder.Services.Updater.<StartBackgroundUpdate>b__23_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VidCoder.Services.Updater.<StartBackgroundUpdate>d__23.MoveNext() in D:\git\VidCoder\VidCoder\Services\Updater.cs:line 248
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by RandomEngy** [comment]
Thanks for the report. I'll fix this in the next version. Sorry for all the trouble. I'm just going through and upgrading a lot of support libraries and there's a bit of churn here.

**Comment by RandomEngy** [comment]
Should be fixed in 4.9 Beta.
