### ISSUE TITLE
BUG (intermittent?) 4.12-beta Pause doesn't pause VidCoder Worker tasks

### ISSUE THREAD

**Issue by bcurran3** [RandomEngy/VidCoder#399]
DISCLAIMER: To my knowledge this has only happened once, right now.

I've got a 10 day batch queue going on my computer that I'm typing on right now. VidCoder is set to run 3 worker processes at below normal priority. I generally let it run in the background but pause it from time to time when I need the extra "oomph." 

I paused VidCoder because I needed the extra "oomph." A couple minutes later I noticed the computer fans were still going full blast. I checked Task Manager and the VidCoder Worker processes are still running. I hit Pause and Resume three times since with no desired result of actually pausing.

![image](https://user-images.githubusercontent.com/14026600/45718511-1e029c00-bb52-11e8-9402-22f1d449dd84.png)

The VidCoder Worker processes ran to the end and finished processing the three files all the while VidCoder was "Paused." VidCoder "thinks" the processes ARE still paused. Somehow VidCoder got disconnected from communicating with its children.

![image](https://user-images.githubusercontent.com/14026600/45718596-88b3d780-bb52-11e8-919a-852e821d7155.png)

![image](https://user-images.githubusercontent.com/14026600/45718639-ac771d80-bb52-11e8-8975-eb4ff0c2ec4a.png)

I hit Resume after the worker processes finished and VidCoder started trying to process the files again.

![image](https://user-images.githubusercontent.com/14026600/45718739-f3651300-bb52-11e8-9016-410d7371ac5e.png)

I hit Stop, got asked if i wanted to stop the encode, hit yes or OK.

![image](https://user-images.githubusercontent.com/14026600/45718798-260f0b80-bb53-11e8-89b8-d451a5c05bcf.png)

Note the green bars above and the no encoding below:

![image](https://user-images.githubusercontent.com/14026600/45718828-3fb05300-bb53-11e8-8b46-b85f2de4e976.png)

Weird huh?

I'm going to quit VidCoder, upgrade to 4.13-beta and I'll report if it happens again.

**Comment by bcurran3** [comment]
4.13 just threw me this error: (Yeah, I know, should be a separate issue.)

![image](https://user-images.githubusercontent.com/14026600/45719004-da109680-bb53-11e8-95f7-25878ef43495.png)

> System.ArgumentNullException: Value cannot be null.
> Parameter name: fileName
>    at System.IO.FileInfo..ctor(String fileName)
>    at VidCoder.Services.ProcessingService.<>c__DisplayClass191_0.<OnEncodeCompleted>b__0() in D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1619
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>

**Comment by RandomEngy** [comment]
In 4.14 Beta I added a lot more error logging for problems with remote encode commands like pause/resume. If this happens again, please share the logs with me and it could help figure out what's going on.

As for the latest error you posted, that should also be fixed in 4.14 Beta.

**Comment by bcurran3** [comment]
This is happening still with 4.20-beta:

![image](https://user-images.githubusercontent.com/14026600/48804497-a07e1800-ecc9-11e8-93fb-59bb0c8ed289.png)

![image](https://user-images.githubusercontent.com/14026600/48804505-a7a52600-ecc9-11e8-9a49-0965bea1960f.png)


I'll e-mail logs

**Comment by bcurran3** [comment]
I have VidCoder configured for **4** worker processes.

My only ability to reconcile what was going on is the info in the two screenshots above. :( I did not notice the yellow progress bars moving. I honestly didn't sit and monitor it, I quit the program.

I'm absolutely clueless as to what the 2 extra processes were doing.

On that particular machine, I do pause/resume multiple times a day.
