### ISSUE TITLE
BUG/ERROR: 4.16-beta VidCoder has experienced an unexpected error.

### ISSUE THREAD

**Issue by bcurran3** [RandomEngy/VidCoder#418]
I've got 10 of these:
![image](https://user-images.githubusercontent.com/14026600/46493667-d91f6c00-c7c5-11e8-9d7f-08aa0b9b1d58.png)
System.NullReferenceException: Object reference not set to an instance of an object.
   at VidCoder.Services.ProcessingService.<>c__DisplayClass180_0.<OnEncodeCompleted>b__0() in D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1585
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

--------------------------------------------------------------------------------------------------
This displayed on both my computers running 4.16-beta batching transcodes. Both displayed 10 (or more) of this error via the task bar VidCoder icon task view. Both terminated VC after closing one of the error messages.

**Comment by bcurran3** [comment]
This is the corresponding error from 3.16:

![image](https://user-images.githubusercontent.com/14026600/46493871-46cb9800-c7c6-11e8-9c97-125db5934cf1.png)

**Comment by RandomEngy** [comment]
Fixed in 4.17 Beta.
