### ISSUE TITLE
When trying to encode a m2ts-file...

### ISSUE THREAD

**Issue by jhemp01** [RandomEngy/VidCoder#420]
System.NullReferenceException: Object reference not set to an instance of an object.
   at VidCoder.Services.ProcessingService.<>c__DisplayClass180_0.<OnEncodeCompleted>b__0() in D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1585
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Fixed in 4.17 Beta.
