### ISSUE TITLE
just started crashing. crashed on same vids

### ISSUE THREAD

**Issue by trsBasicLine10** [RandomEngy/VidCoder#423]
`System.NullReferenceException: Object reference not set to an instance of an object.
   at VidCoder.Services.OutputPathService.GetTranslatedSourceName() in D:\git\VidCoder\VidCoder\Services\OutputPathService.cs:line 574
   at VidCoder.Services.OutputPathService.ReplaceArguments(String nameFormat, Picker picker) in D:\git\VidCoder\VidCoder\Services\OutputPathService.cs:line 583
   at VidCoder.Services.ProcessingService.<>c__DisplayClass176_0.<OnEncodeCompleted>b__0() in D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1566
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)`

`System.NullReferenceException: Object reference not set to an instance of an object.
   at VidCoder.Services.OutputPathService.GetTranslatedSourceName() in D:\git\VidCoder\VidCoder\Services\OutputPathService.cs:line 574
   at VidCoder.Services.OutputPathService.ReplaceArguments(String nameFormat, Picker picker) in D:\git\VidCoder\VidCoder\Services\OutputPathService.cs:line 583
   at VidCoder.Services.ProcessingService.<>c__DisplayClass176_0.<OnEncodeCompleted>b__0() in D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1566
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

`

**Comment by RandomEngy** [comment]
Fixed in 4.17 Beta.
