### ISSUE TITLE
VidCoder-4.16-Beta-Portable

### ISSUE THREAD

**Issue by RogerT42** [RandomEngy/VidCoder#429]
As VidCoder starts, receive the following crash report:
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Windows.Baml2006.Baml2006Reader.Process_PropertyWithConverter()
   at System.Windows.Baml2006.Baml2006Reader.Process_OneBamlRecord()
   at System.Windows.Baml2006.Baml2006Reader.Process_BamlRecords()
   at System.Windows.Baml2006.Baml2006Reader.Read()
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at VidCoder.View.Main..ctor() in D:\git\VidCoder\VidCoder\View\Main.xaml.cs:line 76
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at VidCoder.Services.Windows.WindowManager.CreateWindow(Type viewModelType) in D:\git\VidCoder\VidCoder\Services\Windows\WindowManager.cs:line 673
   at VidCoder.Services.Windows.WindowManager.PrepareWindowForOpen(Object viewModel, Object ownerViewModel, Boolean userInitiated, Boolean isDialog) in D:\git\VidCoder\VidCoder\Services\Windows\WindowManager.cs:line 430
   at VidCoder.Services.Windows.WindowManager.OpenWindow(Object viewModel, Object ownerViewModel, Boolean userInitiated) in D:\git\VidCoder\VidCoder\Services\Windows\WindowManager.cs:line 162
   at VidCoder.App.OnStartup(StartupEventArgs e) in D:\git\VidCoder\VidCoder\App.xaml.cs:line 141
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Hmm. I can't reproduce this and I can't find anything online about what might cause this.

You do have a rather old version of Windows 10 that does not have .NET 4.7.1 installed by default, which is what VidCoder 4 Beta uses. There's a couple things you might try:

Uninstall and reinstall .NET 4.7.1.
Try upgrading to a more recent Windows version like 1803.
