### ISSUE TITLE
multiple chapters encoder error

### ISSUE THREAD

**Issue by mithodea** [RandomEngy/VidCoder#431]
System.NullReferenceException: Object reference not set to an instance of an object.
   at VidCoder.Services.ProcessingService.<>c__DisplayClass180_0.<OnEncodeCompleted>b__0() in D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1585
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Is this on Beta or Stable?

**Comment by mithodea** [comment]
In beta versión 4.16, this error occurs when i try to coder multiple chapters. (apology my english)

Sent from Mail for Windows 10

**Comment by RandomEngy** [comment]
Can you try running this Debug version and copying the error you get there?

http://engy.us/misc/VidCoder-4.18-Beta-Portable.exe
