### ISSUE TITLE
VidCoder 4.23 Beta error message

### ISSUE THREAD

**Issue by bcurran3** [RandomEngy/VidCoder#457]
> ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case. ---> System.NullReferenceException: Object reference not set to an instance of an object.
>    at VidCoder.ViewModel.EncodeJobViewModel.CalculateWork() in D:\git\VidCoder\VidCoder\ViewModel\DataModels\EncodeJobViewModel.cs:line 233
>    at VidCoder.Services.ProcessingService.<>c.<StartEncodeQueue>b__177_1(EncodeJobViewModel job) in D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1370
>    at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
>    at VidCoder.Services.QueueWorkTracker.ReportEncodeStart(IEnumerable`1 initialWork) in D:\git\VidCoder\VidCoder\Services\QueueWorkTracker.cs:line 85
>    at VidCoder.Services.ProcessingService.StartEncodeQueue() in D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1370
>    at ReactiveUI.ReactiveCommand.<>c__DisplayClass0_0.<Create>b__1(IObserver`1 observer)
>    at System.Reactive.AnonymousObservable`1.SubscribeCore(IObserver`1 observer)
>    at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer)
>    --- End of inner exception stack trace ---
>    at ReactiveUI.RxApp.<>c__DisplayClass0_0.<.cctor>b__2()
>    at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
>    at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0()
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Got this today. Not sure why. I had searched for files in File Explorer, dragged them over, then told it to encode, then blamo!

Re-ran VC, tried again, same thing 3x.

**Comment by RandomEngy** [comment]
Not sure exactly what is going wrong so I added some more handling/logging. If you see this happen again please post the updated error details.
