### ISSUE TITLE
4.31 Crash and Burn

### ISSUE THREAD

**Issue by aotgunrt** [RandomEngy/VidCoder#496]
System.NotSupportedException: The given path's format is not supported.
   at System.Security.Permissions.FileIOPermission.EmulateFileIOPermissionChecks(String fullPath)
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, String fullPath, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.FileInfo.Init(String fileName, Boolean checkHost)
   at VidCoder.Services.ProcessingService.<>c__DisplayClass194_0.<OnEncodeCompleted>b__0() in D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1723
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by padi543** [comment]
Just interested: 
- Which version: Portable or Installer?
- Which OS?

**Comment by RandomEngy** [comment]
I think this happened because somehow a colon ":" got put in the output path somehow. Do you have a colon character in any of your custom file name formats?

**Comment by aotgunrt** [comment]
Windows 10 Professional (x64) Version 1803 (build 17134.556)

Installer Version 4.31 Handbrake 1.2.0

 

Drag and drop Video source NO colon ":"ns

 

Thanks Steve

**Comment by RandomEngy** [comment]
Does it reproduce reliably? If so I can get you a special build of VidCoder to help pinpoint what's going on.

**Comment by aotgunrt** [comment]
No 

 

It has happened several times on different files.

Always part of a batch loaded from the q.

It consistently fails after crash and file is still in the q, try to encode from the q it crashes again and again.

If you delete from the q, re-drag and drop add to q it encodes no problem. 

 

I always burn sub titles.

 

I have tried the drag and drop for subtitles, the app stated “sub accepted”, but no evidence they are there, either on screen on in a preview.

At that point a manually browse to sub file. Then add to q.

 

I don’t Know if the files that crashed were added like that on not, just an fyi.

 

Because, of the workaround its not a serious problem.

The second try it the one 😲

 

Steve

**Comment by RandomEngy** [comment]
4.32 is released. One, it should fix the drag and drop SRT bug. Two, it should have more logging in case the crash happens again. Next time you see the crash, post the new stack trace here and I can figure more about what's going on.

**Comment by aotgunrt** [comment]
OK got it. (4.32)

If and when.

Steve
