### ISSUE TITLE
VidCoder 4.32  and 5.4Beta  Crash

### ISSUE THREAD

**Issue by markl7620** [RandomEngy/VidCoder#502]
ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at VidCoder.ViewModel.EncodeJobViewModel.CalculateWork() in D:\git\VidCoder\VidCoder\ViewModel\DataModels\EncodeJobViewModel.cs:line 234
   at VidCoder.Services.ProcessingService.<>c.<StartEncodeQueue>b__177_1(EncodeJobViewModel job) in D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1377
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at VidCoder.Services.QueueWorkTracker.ReportEncodeStart(IEnumerable`1 initialWork) in D:\git\VidCoder\VidCoder\Services\QueueWorkTracker.cs:line 85
   at VidCoder.Services.ProcessingService.StartEncodeQueue() in D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1377
   at ReactiveUI.ReactiveCommand.<>c__DisplayClass0_0.<Create>b__1(IObserver`1 observer)
   at System.Reactive.AnonymousObservable`1.SubscribeCore(IObserver`1 observer)
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer)
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass11_0.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Is this happening every time you try to start the encode queue? Or in any particular circumstance? If so could you share %appdata%\VidCoder\VidCoder.sqlite ? This is a very odd stack trace because I don't see anywhere in that method that could possible throw a null reference exception.

**Comment by markl7620** [comment]
I have uninstalled both versions and reinstalled 4.32.  It seems to be
working now.  I'll let you know of any further issues
