### ISSUE TITLE
Vidcoder Beta 5.6 crash while initiating batch encode.

### ISSUE THREAD

**Issue by ZaphodX77** [RandomEngy/VidCoder#523]

**Comment by ZaphodX77** [comment]
ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at VidCoder.ViewModel.EncodeJobViewModel.CalculateWork() in D:\git\VidCoder\VidCoder\ViewModel\DataModels\EncodeJobViewModel.cs:line 234
   at VidCoder.Services.ProcessingService.<>c.<StartEncodeQueue>b__192_1(EncodeJobViewModel job) in D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1480
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at VidCoder.Services.QueueWorkTracker.ReportEncodeStart(IEnumerable`1 initialWork) in D:\git\VidCoder\VidCoder\Services\QueueWorkTracker.cs:line 85
   at VidCoder.Services.ProcessingService.StartEncodeQueue() in D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1480
   at ReactiveUI.ReactiveCommand.<>c__DisplayClass0_0.<Create>b__1(IObserver`1 observer)
   at System.Reactive.AnonymousObservable`1.SubscribeCore(IObserver`1 observer)
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer)
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass11_0.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ZaphodX77** [comment]
ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at VidCoder.ViewModel.EncodeJobViewModel.CalculateWork() in D:\git\VidCoder\VidCoder\ViewModel\DataModels\EncodeJobViewModel.cs:line 234
   at VidCoder.Services.ProcessingService.<>c.<StartEncodeQueue>b__192_1(EncodeJobViewModel job) in D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1480
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at VidCoder.Services.QueueWorkTracker.ReportEncodeStart(IEnumerable`1 initialWork) in D:\git\VidCoder\VidCoder\Services\QueueWorkTracker.cs:line 85
   at VidCoder.Services.ProcessingService.StartEncodeQueue() in D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1480
   at ReactiveUI.ReactiveCommand.<>c__DisplayClass0_0.<Create>b__1(IObserver`1 observer)
   at System.Reactive.AnonymousObservable`1.SubscribeCore(IObserver`1 observer)
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer)
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass11_0.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ZaphodX77** [comment]
Additional troubleshooting indicates that this was caused by a bad video file that I placed in the queue. It was not the first, it was the 2nd of 10 files. Perhaps something could be done to reject such files from the queue with a message to the user? 

Thank you for a great program. I am a long time user.

**Comment by RandomEngy** [comment]
Do you have a copy of that problematic file? If you could give me that, and the %appdata%\VidCoder-Beta\VidCoder.sqlite file you're using I could reproduce this. This has been reported before but unfortunately the stack trace makes no sense as there's nowhere in CalculateWork() that could throw a NullReferenceException.

**Comment by RandomEngy** [comment]
I made a change that might affect how the error is logged in 5.8 Beta. Let me know if you get the error again there.
