### ISSUE TITLE
VidCoder 4.34 Open source error

### ISSUE THREAD

**Issue by k4noe** [RandomEngy/VidCoder#530]
Got this when I tried : Open Source --> enqueue multiple files, or another open source method

> ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case. ---> System.ArgumentException: Value does not fall within the expected range.
>    at MS.Internal.AppModel.ShellUtil.GetShellItemForPath(String path)
>    at Microsoft.Win32.FileDialog.PrepareVistaDialog(IFileDialog dialog)
>    at Microsoft.Win32.FileDialog.RunVistaDialog(IntPtr hwndOwner)
>    at Microsoft.Win32.CommonDialog.ShowDialog()
>    at VidCoder.Services.FileService.GetFileNames(String initialDirectory) in D:\git\VidCoder\VidCoder\Services\FileService.cs:line 48
>    at VidCoder.Services.ProcessingService.<get_QueueFiles>b__125_0() in D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 470
>    at ReactiveUI.ReactiveCommand.<>c__DisplayClass0_0.<Create>b__1(IObserver`1 observer)
>    at System.Reactive.AnonymousObservable`1.SubscribeCore(IObserver`1 observer)
>    at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer)
>    --- End of inner exception stack trace ---
>    at ReactiveUI.RxApp.<>c__DisplayClass11_0.<.cctor>b__2()
>    at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
>    at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0()
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Looks like this was caused by a bad file path. In 5.8 beta it should no longer crash when trying to queue files. It will instead just not include that file when scanning it, and it will write a error message to the log. If you see the log message let me know and it should tell me what the bad path was.
