### ISSUE TITLE
System.IO.FileNotFoundException with 5.7 Beta

### ISSUE THREAD

**Issue by linucksrox** [RandomEngy/VidCoder#531]
Immediately upon opening the application (after upgrading from 5.6 to 5.7 beta), I get this exception message. Things work normally again if I roll back to 5.6.
```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at VidCoder.Services.Updater.<StartBackgroundUpdate>b__23_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VidCoder.Services.Updater.<StartBackgroundUpdate>d__23.MoveNext() in D:\git\VidCoder\VidCoder\Services\Updater.cs:line 252
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

=== Pre-bind state information ===
LOG: DisplayName = System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files/VidCoder-Beta/
LOG: Initial PrivatePath = NULL
Calling assembly : VidCoder, Version=5.7.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Program Files\VidCoder-Beta\VidCoder.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
LOG: The same bind was seen before, and was failed with hr = 0x80070002.
```

**Comment by RandomEngy** [comment]
That's odd. Nothing much changed from 5.6 to 5.7 or so I thought. What OS are you running on?

**Comment by linucksrox** [comment]
I'm running Windows 10 Enterprise 2016 LTSB (build 1607)

**Comment by wizorald** [comment]
Same for me

**Comment by RandomEngy** [comment]
See if it works with the 5.8 Beta.

**Comment by linucksrox** [comment]
Awesome, 5.8 Beta is working for me! Thanks!

**Comment by wizorald** [comment]
All test is good for me too
