### ISSUE TITLE
Gibberish error - I'm not a programmer, so don't know what this means

### ISSUE THREAD

**Issue by kaufmanj1973** [RandomEngy/VidCoder#533]
ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at VidCoder.ViewModel.EncodeJobViewModel.CalculateWork() in D:\git\VidCoder\VidCoder\ViewModel\DataModels\EncodeJobViewModel.cs:line 235
   at VidCoder.Services.ProcessingService.<>c.<StartEncodeQueue>b__177_1(EncodeJobViewModel job) in D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1377
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at VidCoder.Services.QueueWorkTracker.ReportEncodeStart(IEnumerable`1 initialWork) in D:\git\VidCoder\VidCoder\Services\QueueWorkTracker.cs:line 85
   at VidCoder.Services.ProcessingService.StartEncodeQueue() in D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1377
   at ReactiveUI.ReactiveCommand.<>c__DisplayClass0_0.<Create>b__1(IObserver`1 observer)
   at System.Reactive.AnonymousObservable`1.SubscribeCore(IObserver`1 observer)
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer)
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass11_0.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Thanks for the report. Does this happen regularly? If it reproduces reliably I'd like to get a custom build to you.

**Comment by kaufmanj1973** [comment]
No, it doesn't happen regularly.  It was just with one particular set of
files that I tried to convert from MP4 to MKV.

**Comment by RandomEngy** [comment]
I made a change that might affect how the error is logged in 5.8 Beta. Let me know if you get the error again there.
