### ISSUE TITLE
Error Message 

### ISSUE THREAD

**Issue by Blickie** [RandomEngy/VidCoder#539]
v5.7 x64 
Opened and closed app and got this error message.

System.NullReferenceException: Object reference not set to an instance of an object.
   at VidCoder.ViewModel.MainViewModel.OnClosing() in D:\git\VidCoder\VidCoder\ViewModel\MainViewModel.cs:line 758
   at VidCoder.Services.Windows.WindowManager.OnClosing(Window window, Boolean userInitiated) in D:\git\VidCoder\VidCoder\Services\Windows\WindowManager.cs:line 595
   at VidCoder.Services.Windows.WindowManager.OnClosingHandler(Object sender, CancelEventArgs e) in D:\git\VidCoder\VidCoder\Services\Windows\WindowManager.cs:line 576
   at System.ComponentModel.CancelEventHandler.Invoke(Object sender, CancelEventArgs e)
   at System.Windows.Window.OnClosing(CancelEventArgs e)
   at System.Windows.Window.WmClose()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Should be fixed in the 5.8 Beta.
