### ISSUE TITLE
CRASHING when browsing for a folder - WIN10

### ISSUE THREAD

**Issue by BDCAPA** [RandomEngy/VidCoder#560]
I can reproduce the issue, when I try to browse for an output folder, it crashes, when trying to import video or folder, it crashes, only drag and drop works, but I still can not select an output folder anywhere (also when trying to browse a folder in settings it crashes)

ERROR CODE:
ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case. ---> System.Runtime.InteropServices.COMException: Creating an instance of the COM component with CLSID {DC1C5A9C-E88A-4DDE-A5A1-60F82A20AEF7} from the IClassFactory failed due to the following error: 80040111 ClassFactory cannot supply requested class (Exception from HRESULT: 0x80040111 (CLASS_E_CLASSNOTAVAILABLE)).
   at Ookii.Dialogs.Wpf.VistaFolderBrowserDialog.RunDialog(IntPtr owner) in D:\docs\random\codeexamples\ookii_dialogs\src\Ookii.Dialogs.Wpf\VistaFolderBrowserDialog.cs:line 169
   at Ookii.Dialogs.Wpf.VistaFolderBrowserDialog.ShowDialog(Window owner) in D:\docs\random\codeexamples\ookii_dialogs\src\Ookii.Dialogs.Wpf\VistaFolderBrowserDialog.cs:line 157
   at VidCoder.Services.FileService.GetFolderName(String initialDirectory, String description) in D:\git\VidCoder\VidCoder\Services\FileService.cs:line 133
   at VidCoder.ViewModel.MainViewModel.SetSourceFromFolder() in D:\git\VidCoder\VidCoder\ViewModel\MainViewModel.cs:line 626
   at ReactiveUI.ReactiveCommand.<>c__DisplayClass0_0.<Create>b__1(IObserver`1 observer)
   at System.Reactive.AnonymousObservable`1.SubscribeCore(IObserver`1 observer)
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer)
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass11_0.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by BDCAPA** [comment]
VidCoder-4.36-Portable and Installed versions also reproduce the problem

**Comment by RandomEngy** [comment]
Thanks for the report. What OS are you running on?

**Comment by BDCAPA** [comment]
Windows 10 Pro for Workstations (1809) Build 17763.503

**Comment by RandomEngy** [comment]
https://answers.microsoft.com/en-us/windows/forum/all/open-save-dialogs-not-working-after-1809-update/c8a06e0d-09f9-4ccb-806d-3a5fecdf20ae

It looks like Windows 1809 has an issue with opening that dialog when using a custom theme or High Contrast. It appears that version 1903 fixes the issue, so you could hold on for that or try changing your theme.

**Comment by BDCAPA** [comment]
Oooo, how much I like these windows updates. However, thank you for your help!

The best transcoding software is yours on planet earth, I have tried all and only yours works how it should.
You helped me converting 72 hours of movie shooting to proxy (1TB). You are great!
