### ISSUE TITLE
4.36 crash

### ISSUE THREAD

**Issue by 2Cool1** [RandomEngy/VidCoder#578]
ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case. ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at DynamicData.ChangeAwareList`1.RemoveRange(Int32 index, Int32 count)
   at VidCoder.Services.ProcessingService.<>c__DisplayClass131_0.<get_ApplyCurrentPresetToQueue>b__1(IExtendedList`1 encodeQueueInnerList) in D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 521
   at DynamicData.List.Internal.ReaderWriter`1.Write(Action`1 updateAction)
   at DynamicData.SourceList`1.Edit(Action`1 updateAction)
   at VidCoder.Services.ProcessingService.<get_ApplyCurrentPresetToQueue>b__131_0() in D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 524
   at ReactiveUI.ReactiveCommand.<>c__DisplayClass0_0.<Create>b__1(IObserver`1 observer)
   at System.Reactive.AnonymousObservable`1.SubscribeCore(IObserver`1 observer)
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer)
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass11_0.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Thanks for the report. Should be fixed with 5.13 Stable.
