### ISSUE TITLE
please technical support to fix this holidays and update the program as soon as possible to avoid such software errors

### ISSUE THREAD

**Issue by microbest** [RandomEngy/VidCoder#588]
While pressing the encode button to compress the required video shows me this code or this message and do not know the solution and how to get over it, please technical support to fix this holidays and update the program as soon as possible to avoid such software errors 
---------------------------------------------------------------------------------------------------->>
ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case. ---> System.InvalidOperationException: Invalid length '00:00:00' on job C:\Program Files\VidCoder\bs\bandicam 2019-09-13 05-17-58-556.mp4
   at VidCoder.ViewModel.EncodeJobViewModel.CalculateWork() in D:\git\VidCoder\VidCoder\ViewModel\DataModels\EncodeJobViewModel.cs:line 268
   at VidCoder.Services.ProcessingService.<>c.<StartEncodeQueue>b__177_1(EncodeJobViewModel job) in D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1373
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at VidCoder.Services.QueueWorkTracker.ReportEncodeStart(IEnumerable`1 initialWork) in D:\git\VidCoder\VidCoder\Services\QueueWorkTracker.cs:line 85
   at VidCoder.Services.ProcessingService.StartEncodeQueue() in D:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 1374
   at ReactiveUI.ReactiveCommand.<>c__DisplayClass0_0.<Create>b__1(IObserver`1 observer)
   at System.Reactive.AnonymousObservable`1.SubscribeCore(IObserver`1 observer)
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer)
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass11_0.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by microbest** [comment]
While pressing the encode button to compress the required video shows me this code or this message and do not know the solution and how to get over it, please technical support to fix this holidays and update the program as soon as possible to avoid such software errors

**Comment by RandomEngy** [comment]
Should be fixed in the Beta release.
