### ISSUE TITLE
Vidcoder error when opening MP4 files.

### ISSUE THREAD

**Issue by Thermalzombie** [RandomEngy/VidCoder#612]
He trying to open an anime encode mp4 files and vidcoder keeps crashing.

Using Win10 64bit 1909

Error:

ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case. ---> System.ArgumentException: The path is not of a legal form.
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at VidCoder.ViewModel.MainViewModel.SetSourceFromFile(String videoFile) in D:\git\VidCoder\VidCoder\ViewModel\MainViewModel.cs:line 618
   at VidCoder.ViewModel.MainViewModel.SetSourceFromFile() in D:\git\VidCoder\VidCoder\ViewModel\MainViewModel.cs:line 610
   at ReactiveUI.ReactiveCommand.<>c__DisplayClass0_0.<Create>b__1(IObserver`1 observer)
   at System.Reactive.AnonymousObservable`1.SubscribeCore(IObserver`1 observer)
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer)
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass11_0.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

File mediainfo:

General
Unique ID                                : 0 (0x0)
Complete name                            : \\?\D:\[Golumpa] High School Prodigies Have It Easy Even In Another World - 08 (Choujin Koukousei-tachi wa Isekai demo Yoyuu de Ikinuku You Desu!) [CR-Dub 1080p x264 AAC] [38755CA5].mkv
Format                                   : Matroska
Format version                           : Version 4
File size                                : 1.34 GiB
Duration                                 : 23 min 40 s
Overall bit rate                         : 8 112 kb/s
Encoded date                             : UTC 2010-02-22 21:41:29
Writing application                      : no_variable_data
Writing library                          : no_variable_data

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings                          : CABAC / 4 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 23 min 40 s
Nominal bit rate                         : 8 000 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.161
Title                                    : [Golumpa
Writing library                          : x264 core 142
Encoding settings                        : cabac=1 / ref=4 / deblock=1:1:1 / analyse=0x3:0x113 / me=umh / subme=8 / psy=1 / psy_rd=0.40:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=12 / lookahead_threads=2 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=0 / weightp=2 / keyint=96 / keyint_min=48 / scenecut=40 / intra_refresh=0 / rc_lookahead=48 / rc=2pass / mbtree=1 / bitrate=8000 / ratetol=1.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / vbv_maxrate=12000 / vbv_bufsize=18000 / nal_hrd=none / filler=0 / ip_ratio=1.40 / aq=1:0.60
Default                                  : Yes
Forced                                   : No

Audio
ID                                       : 2
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : A_AAC-2
Duration                                 : 23 min 40 s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 44.1 kHz
Frame rate                               : 43.066 FPS (1024 SPF)
Compression mode                         : Lossy
Delay relative to video                  : 5 ms
Language                                 : English
Default                                  : Yes
Forced                                   : No

Text
ID                                       : 3
Format                                   : ASS
Codec ID                                 : S_TEXT/ASS
Codec ID/Info                            : Advanced Sub Station Alpha
Compression mode                         : Lossless
Title                                    : English (US) / English (US)
Language                                 : English
Default                                  : Yes
Forced                                   : No

You can get the file from nyaa.si torrent site:  https://nyaa.si/view/1207244

**Comment by RandomEngy** [comment]
I don't have any issues with files with that name. The path is really weird:

\?\D:[Golumpa] High School ...

When I run MediaInfo it says D:\SomeFile.mkv. Is your drive special in any way?

**Comment by Thermalzombie** [comment]
Oh crap how do I fix this path issue it must be a qbittorrent issue.  But I was able to open these files with xmediarecode.
