### ISSUE TITLE
VidCoder crashing on startup

### ISSUE THREAD

**Issue by Larryv47** [RandomEngy/VidCoder#616]
First post here.  I don't know much, but I've used VidCoder in the past to convert video file formats.  Just tried to install the version in the MS Store on a new computer.  Installs fine, but when I launch I get this error:

VidCoder has experienced an unexpected error.
The program needs to close but the error will be automatically reported.

System.Exception: The notification platform is unavailable.

The notification platform is unavailable.

   at Windows.UI.Notifications.ToastNotificationHistory.Clear()
   at VidCoder.View.Main.<<-ctor>b__12_9>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Any idea what I can do to fix this?  I'm totally at a loss.  Thanks.

**Comment by RandomEngy** [comment]
Thanks for the report. I'll work on getting this fixed. As a short-term workaround you could use the Portable or Installer version.

Also, do you have this setting enabled?

![image](https://user-images.githubusercontent.com/9450861/72200015-014e3f80-33f9-11ea-8cd4-74d4823bb9ba.png)

**Comment by Larryv47** [comment]
Wow, thanks for the fast reply, David!  I do have notifications turned 
on as you suggest.  BTW, I've only so far tried installs by downloading 
from the Microsoft Store.  I don't know where to find the portable and 
installer versions - can you point me to these?

One other piece of info that might be helpful.

I later tried installing vidcoder on my other computer (an Acer 
notebook), also unsuccessfully, but got a very different error msg:

System.ApplicationException: Access is denied. (Exception from HRESULT: 
0x80070005 (E_ACCESSDENIED))

at System.Threading.TimerQueue.CreateAppDomainTimer(UInt32 dueTime, 
Int32 id)

at System.Threading.TimerQueue.EnsureAppDomainTimerFiresBy(UInt32 
requestedDuration)

at System.Threading.TimerQueueTimer.Change(UInt32 dueTime, UInt32 period)

at System.Threading.Timer.TimerSetup(TimerCallback callback, Object 
state, UInt32 dueTime, UInt32 period, StackCrawlMark& stackMark)

at System.Threading.Timer..ctor(TimerCallback callback, Object state, 
TimeSpan dueTime, TimeSpan period)

at 
System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.PeriodicTimer..ctor(Action 
action, TimeSpan period)

at 
System.Reactive.Concurrency.ConcurrencyAbstractionLayerImpl.StartPeriodicTimer(Action 
action, TimeSpan period)

at System.Reactive.PlatformServices.SystemClock.Register(LocalScheduler 
scheduler)

at System.Reactive.Concurrency.CurrentThreadScheduler.<>c.<.cctor>b__16_0()

at System.Lazy`1.CreateValue()

at System.Lazy`1.LazyInitValue()

at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean 
enableSafeguard)

at VidCoder.App.OnStartup(StartupEventArgs e)

at System.Windows.Application.<.ctor>b__1_0(Object unused)

at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate 
callback, Object args, Int32 numArgs)

at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, 
Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)



For reference, here's the error I sent with my original trouble report 
from my first attempt on an HP Desktop:

System.Exception: The notification platform is unavailable.

The notification platform is unavailable.

    at Windows.UI.Notifications.ToastNotificationHistory.Clear()
    at VidCoder.View.Main.<<-ctor>b__12_9>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at 
System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate 
callback, Object args, Int32 numArgs)
    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object 
source, Delegate callback, Object args, Int32 numArgs, Delegate 
catchHandler)


Thanks again!

    /Larry Vogel
    larryv47@gmail.com
    206-919-1155/

**Comment by RandomEngy** [comment]
https://vidcoder.net/

The error message on your notebook is interesting. It's crashing on a very basic system call. I don't think I'd be able to work around it. Can you try the installer version over there and tell me if you get the same problem?

**Comment by Larryv47** [comment]
Thank you so much David!

The installer version worked like a charm on both machines.  Not sure 
what's up with the Microsoft Store version.

And I understand it's a considerable commitment on your part to maintain 
apps like this that make the lives of users like myself so much easier.  
It's a great service you perform, and you probably don't get too many 
thank-yous.

Consider this a big one from me.

    /Larry Vogel
    larryv47@gmail.com
    206-919-1155/

**Comment by RandomEngy** [comment]
It's really great to hear that! Thanks for the reports. So far the Microsoft Store version has just been a basket of headaches and mysterious errors. I'll need to report these bugs to the Desktop Bridge team.
