### ISSUE TITLE
Moving window crashes program

### ISSUE THREAD

**Issue by beyond1207** [RandomEngy/VidCoder#674]
When i move the VidCoder (6.11 beta) window the program crashes with the following error:

System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.Windows.Shell.WindowChromeWorker._HandleNCHitTest(WM uMsg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Shell.WindowChromeWorker._WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Are you using a Logitech mouse with SetPoint software?

I found [this bug report](https://developercommunity.visualstudio.com/content/problem/167357/overflow-exception-in-windowchrome.html), closed for low priority. [A question on StackOverflow](https://stackoverflow.com/questions/50282355/why-does-my-wpf-application-crash-when-i-bump-my-mousewheel) talks about the problem as well.

**Comment by beyond1207** [comment]
I am using a Logitech mouse but not using SetPoint software. This is the only application that I have ever experienced this error with so I doubt its the mouse.

**Comment by RandomEngy** [comment]
According to the bug, this is a combination the Logitech drivers and using custom WindowChrome in WPF. I'll look into implementing the workaround to see if it helps you.

**Comment by RandomEngy** [comment]
I added a workaround in 6.12 Beta. Tell me if this fixes things for you.

**Comment by beyond1207** [comment]
So far it looks like your workaround worked. I can now move the window around like any other program. Thank you!
