### ISSUE TITLE
CLI encode null reference issue (latest 6.13 Beta)

### ISSUE THREAD

**Issue by atziasios** [RandomEngy/VidCoder#686]
CLI encode is failing with "null reference" exception in the latest beta (6.13). When I issue:

VidCoderCLI.exe encode -s "myVideo.mkv" -p "myPreset"

it yields:

args: encode -s myVideo.mkv -p myPreset
Action: 'encode'
Action length: 6
Connecting to named pipe 'VidCoderAutomationBeta' on machine '.'
Connected.
Sending Request message
{"CallId":1,"MethodName":"Encode","Parameters":["myVideo.mkv",null,"myPreset",null],"GenericArguments":[]}
Handling response
{
  "CallId": 1,
  "Succeeded": false,
  "Error": "System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.\r\n   at VidCoder.Services.ProcessingService.Process(String source, String destination, String presetName, String pickerName)\r\n   at VidCoder.Automation.VidCoderAutomation.<>c__DisplayClass0_0.<Encode>b__0()\r\n   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()\r\n   at System.Windows.Threading.DispatcherOperation.InvokeImpl()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)\r\n   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)\r\n   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)\r\n   at System.Windows.Threading.Dispatcher.Invoke(Action callback)\r\n   --- End of inner exception stack trace ---\r\n   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)\r\n   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)\r\n   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   at PipeMethodCalls.RequestHandler`1.<HandleRequestAsync>d__4.MoveNext()"
}
PipeMethodCalls.PipeInvokeFailedException: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at VidCoder.Services.ProcessingService.Process(String source, String destination, String presetName, String pickerName)
   at VidCoder.Automation.VidCoderAutomation.<>c__DisplayClass0_0.<Encode>b__0()
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at PipeMethodCalls.RequestHandler`1.<HandleRequestAsync>d__4.MoveNext()
   at PipeMethodCalls.MethodInvoker`1.<InvokeAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at VidCoderCLI.Program.<TryActionAsync>d__14.MoveNext()

**Comment by RandomEngy** [comment]
Thanks for the bug report. This will be fixed in the next Beta release.

**Comment by RandomEngy** [comment]
Fixed in 6.14 Beta.
