### ISSUE TITLE
Settings Error Crash

### ISSUE THREAD

**Issue by YaBoyJon23** [RandomEngy/VidCoder#692]
When I go into settings it crashes

System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.Windows.Shell.WindowChromeWorker._HandleNCHitTest(WM uMsg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Shell.WindowChromeWorker._WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate [catchHandler)

**Comment by RandomEngy** [comment]
This is a WPF bug with some Logitech mouse drivers. I applied a workaround to the main window and it looks like I need to apply it to other windows as well. Will work on a fix.

**Comment by RandomEngy** [comment]
Should be fixed in 6.17 Beta.

**Comment by YaBoyJon23** [comment]
Just updated. Will report back if any issues.
Thanks you and your team for continued support
