### ISSUE TITLE
BUG submission: v6.18 - left/right crop oversize value causes bugcheck

### ISSUE THREAD

**Issue by YupoWert** [RandomEngy/VidCoder#712]
Hi,
While trying to left/right crop a portrait vid clip recorded in landscape (grr), I attempted to adjust the left/right manual crop values to remove the extra black padding. I entered 250 for left then (without paying attention) the same for right - unfortunately, the original value of '0' was still present, so I actually entered 2500, which immediately caused this bugcheck:

I assume it's just a lack of boundary value checking error (VidWidth - leftcrop - rightcrop >0)
It's repeatable on several clips I tried. No other testing/values attempted

Hope this helps
Many thanks

ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case. ---> System.ArgumentException: '-830*' is not a valid value for property 'Width'.
   at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal)
   at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value)
   at VidCoder.Controls.PaddingFrame.OnOutputSizeChanged(DependencyObject dependencyObject, DependencyPropertyChangedEventArgs eventArgs)
   at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   at System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   at System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   at System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   at MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.ComponentModel.PropertyChangedEventManager.OnPropertyChanged(Object sender, PropertyChangedEventArgs args)
   at ReactiveUI.ReactiveObject.ReactiveUI.IReactiveObject.RaisePropertyChanged(PropertyChangedEventArgs args)
   at ReactiveUI.IReactiveObjectExtensions.ExtensionState`1.RaisePropertyChanged(String propertyName)
   at ReactiveUI.IReactiveObjectExtensions.RaiseAndSetIfChanged[TObj,TRet](TObj this, TRet& backingField, TRet newValue, String propertyName)
   at VidCoder.Services.OutputSizeService.Refresh()
   at VidCoder.ViewModel.SizingPanelViewModel.RefreshOutputSize()
   at VidCoder.ViewModel.ProfileViewModelBase.UpdateProfileProperty[TProperty,TModel](Func`1 targetFunc, String propertyName, String raisePropertyName, TProperty value, Boolean raisePropertyChanged)
   at VidCoder.ViewModel.SizingPanelViewModel.<.ctor>b__3_37(Int32 cropRight)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value)
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.DistinctUntilChanged`2._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Switch`1._.InnerObserver.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Cast`2._.OnNext(TSource value)
   at System.Reactive.Observer`1.OnNext(T value)
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.EnumerableSelector._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Buffer`2.Boundaries._.BufferClosingObserver.OnNext(TBufferClosing value)
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Select`2.Selector._.OnNext(TSource value)
   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value)
   at System.Reactive.Observer`1.OnNext(T value)
   at ReactiveUI.IReactiveObjectExtensions.ExtensionState`1.NotifyObservable[T](TSender rxObj, T item, ISubject`1 subject)
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass11_0.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Thanks for the report. This will be fixed in the next Beta release.

**Comment by RandomEngy** [comment]
Fixed in 6.19 Beta.
