### ISSUE TITLE
Vidcoder Beta crashed when x265'ing Family Guy

### ISSUE THREAD

**Issue by Rayman24365** [RandomEngy/VidCoder#734]
This is the error that I get, but the output file seems to work just fine... but the batch stops as the program freezes.

**code = IoErr (10), message = System.Data.SQLite.SQLiteException (0x800007FF): disk I/O error
disk I/O error
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at VidCoder.Model.DatabaseConfig.SetInternal(String configName, String configValue, SQLiteConnection connection)
   at VidCoder.Config.Set[T](String key, T value)
   at VidCoder.Services.ProcessingService.<.ctor>b__20_34(IChangeSet`1 changeSet)
   at System.Reactive.ObserverBase`1.OnNext(T value)
   at System.Reactive.AutoDetachObserver`1.OnNextCore(T value)
   at System.Reactive.ObserverBase`1.OnNext(T value)
   at System.Reactive.Observer`1.OnNext(T value)
   at DynamicData.SourceList`1.InvokeNext(IChangeSet`1 changes)
   at DynamicData.SourceList`1.Edit(Action`1 updateAction)
   at DynamicData.SourceListEditConvenienceEx.Remove[T](ISourceList`1 source, T item)
   at VidCoder.Services.ProcessingService.<>c__DisplayClass212_0.<OnEncodeCompleted>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)**

The encode is done on a stable system with 1 SSD that is verified to be in working order. No other program ever reports any error. This specific error and crash now happened two times out of two encoding x265.

**Comment by RandomEngy** [comment]
It looks like you have a corrupted disk, at least where the VidCoder .sqlite file is stored. This isn't an error I can fix. You could try renaming your VidCoder.sqlite file in %appdata%\VidCoder or %appdata%\VidCoder-Beta to see if it gets re-created in a better disk location.

**Comment by Rayman24365** [comment]
Then it is solved I think. The VidCoder.sqlite file is on the NAS where the portable program is run from. After a while the NAS sleeps and if Vidcoder seeks the file when it is done it won't be there for at least 15 seconds until the NAS wakes, which by then will be too late. Vidcoder is impatient like that :)
Thanks for the headsup. All solved. A+

**Comment by RandomEngy** [comment]
The timeout for disk access is set at a lower level than VidCoder. But I'm glad you've got it resolved!
