### ISSUE TITLE
Program Crash

### ISSUE THREAD

**Issue by Jordi57** [RandomEngy/VidCoder#738]
Sorry, I sent you an error message before and it is my fault, not the program.
Then I saw the messages I attached.
Do you know if the conversion made and booted from the point where the program crashed can be recovered? It's because it's a 4k movie and I use the encoding settings of MKV 2160 and it takes a long time to do the conversion. Specifically it is an 8GB file and, when it fell, it had already been working for about 30 hours. and there were 3 hours left to finish.
Thanks and sorry again.

Message:
ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case. ---> System.Data.SQLite.SQLiteException: database or disk is full
database or disk is full
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at VidCoder.Model.DatabaseConfig.SetInternal(String configName, String configValue, SQLiteConnection connection)
   at VidCoder.Config.Set[T](String key, T value)
   at VidCoder.ViewModel.MainViewModel.<get_OpenUpdates>b__357_0()
   at ReactiveUI.ReactiveCommand.<>c__DisplayClass0_0.<Create>b__1(IObserver`1 observer)
   at System.Reactive.AnonymousObservable`1.SubscribeCore(IObserver`1 observer)
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer)
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass11_0.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

![Captura de pantalla 2021-01-24 115945](https://user-images.githubusercontent.com/77919411/105629345-c6bc1700-5e42-11eb-8ac6-6f8edb798a9c.jpg)

**Comment by RandomEngy** [comment]
Looks like you ran out of disk space.

**Comment by Jordi57** [comment]
Yes, you are right. Do you know if what you have already processed can 
be taken advantage of or if you need to start all over again from 
scratch?

------ Mensaje original ------
De: "David Rickard" <notifications@github.com>
Para: "RandomEngy/VidCoder" <VidCoder@noreply.github.com>
CC: "Jordi57" <j.nebot@icloud.com>; "Author" <author@noreply.github.com>
Enviado: 24/01/2021 16:52:48
Asunto: Re: [RandomEngy/VidCoder] Program Crash (#738)

**Comment by RandomEngy** [comment]
You need to start over.

**Comment by Jordi57** [comment]
Hello,

Thanks, everything is already fixed.

I’m not a technician and I’m a hair lost with all of this.

Could you tell me what is the best encoding settings? I use Matroska 
H265 2160p60 for 4K movies and for non-4K H265 or H264 1080p30.

I've seen it make a very big reduction and I don't know if it can 
preserve the quality of the image and it also takes a long time: 30 to 
50 hours.
Do you think I have better alternatives? If you can’t advise me, could 
you tell me if there is any place where you can ask it or read it and 
learn it?

Thanks anyway.

Best regards.

Jordi

------ Mensaje original ------
De: "David Rickard" <notifications@github.com>
Para: "RandomEngy/VidCoder" <VidCoder@noreply.github.com>
CC: "Jordi57" <j.nebot@icloud.com>; "Author" <author@noreply.github.com>
Enviado: 24/01/2021 17:11:53
Asunto: Re: [RandomEngy/VidCoder] Program Crash (#738)

**Comment by RandomEngy** [comment]
That's a long topic. I'd try to avoid resampling and use the quality slider to pick how good you need the picture to look. You don't have to have it take a really long time to encode if you accept a little bit higher file size.
