### ISSUE TITLE
beta 6.27 crash

### ISSUE THREAD

**Issue by bobbobbin** [RandomEngy/VidCoder#783]
System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.RegularExpressions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Text.RegularExpressions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at VidCoder.FileCleanup.CleanHandBrakeTempFiles()
   at VidCoder.ViewModel.MainViewModel.OnClosing()
   at VidCoder.Services.Windows.WindowManager.OnClosing(Window window, Boolean userInitiated)
   at VidCoder.Services.Windows.WindowManager.OnClosingHandler(Object sender, CancelEventArgs e)
   at System.Windows.Window.OnClosing(CancelEventArgs e)
   at System.Windows.Window.WmClose()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Thanks for the report. Is this on Portable or Installer? What version of Windows do you have?

**Comment by bobbobbin** [comment]
You are welcome.

 

Installer 6.27 beta – windows 10.

 

I was trying to drag an srt file onto a video, but it wouldn’t accept it – no error message or anything – the srt just would not “stick” onto the program window.

 

I went to close the program when I noticed the error message.

 

After closing and reopening, it worked fine again, with the srt going right in.

 

Kindest regards,

Deron Adams

**Comment by RandomEngy** [comment]
Do you remember if this happened when launching VidCoder from the installer? (With the "Run VidCoder" checkbox)

**Comment by bobbobbin** [comment]
No, this occurred when the program was already running.

 

I believe I had converted one file, then when I went to do a different file, one with a subtitle, I noticed that the sub wouldn’t “load”

 

Ie I’d rag it over, but it would not be added to the file I wanted converted.
