### ISSUE TITLE
Crash in 2.14

### ISSUE THREAD

**Issue by JonnyThree** [RandomEngy/VidCoder#8]
Hello, i have just now updated beta version (x64 in Win x64). Just choose a file to convert > settings >  video tab > open the dropdown menu of x264 levels selector. I don't have the log because i have immediately unistalled the software.

**Comment by RandomEngy** [comment]
Looks like the HandBrake people moved or removed check_h264_level somewhere else. I'll ask them about it.

**Comment by kborowinski** [comment]
Can confirm JohnyThree findings. Got crash when trying to change encoding level:

System.Exception: An OnError occurred on an object (usually ObservableAsPropertyHelper) that would break a binding or command. To prevent this, Subscribe to the ThrownExceptions property of your objects ---> **System.EntryPointNotFoundException: Unable to find an entry point named 'check_h264_level' in DLL 'hb.dll'.**
   at HandBrake.ApplicationServices.Interop.HbLib.HBFunctions.check_h264_level(String level, Int32 width, Int32 height, Int32 fps_num, Int32 fps_den, Int32 interlaced, Int32 fake_interlaced)
   at HandBrake.ApplicationServices.Interop.HandBrakeUtils.IsH264LevelValid(String level, Int32 width, Int32 height, Int32 fpsNumerator, Int32 fpsDenominator, Boolean interlaced, Boolean fakeInterlaced) in D:\docs\projects\HandBrakeGit\win\CS\HandBrake.ApplicationServices\Interop\HandBrakeUtils.cs:line 225
   at VidCoder.ViewModel.LevelChoiceViewModel.<RegisterIsCompatible>b__5_0(Boolean hasVideoSource, FrameRate titleFramerate, Double profileFramerate, String videoOptions, Geometry outputSize) in D:\docs\projects\VidCoder\VidCoder\ViewModel\DataModels\LevelChoiceViewModel.cs:line 73
   at System.Reactive.Linq.ObservableImpl.CombineLatest`6._.GetResult()
   at System.Reactive.Linq.ObservableImpl.CombineLatestSink`1.Next(Int32 index)
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass5.<.cctor>b__2()
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action)
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass1`1.<Schedule>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Fixed in 2.15 Beta.
