### ISSUE TITLE
VidCoder 6.30 beta

### ISSUE THREAD

**Issue by leninmejia39** [RandomEngy/VidCoder#800]
it gives me error in window 7 64 bits
System.TypeInitializationException: The type initializer for 'HandBrake.Interop.Interop.HandBrakeEncoderHelpers' threw an exception.
 ---> System.Exception: Please Initialise with HandBrakeUtils.EnsureGlobalInit before using!
   at HandBrake.Interop.Interop.HandBrakeEncoderHelpers..cctor() in C:\git\HandBrake\win\CS\HandBrake.Interop\Interop\HandBrakeEncoderHelpers.cs:line 39
   --- End of inner exception stack trace ---
   at HandBrake.Interop.Interop.HandBrakeEncoderHelpers.GetContainer(String shortName)
   at VidCoder.Services.OutputPathService.GetExtensionForProfile(VCProfile profile, Boolean includeDot) in C:\git\VidCoder\VidCoder\Services\OutputPathService.cs:line 301
   at VidCoder.Services.OutputPathService.GetOutputExtension(Boolean includeDot) in C:\git\VidCoder\VidCoder\Services\OutputPathService.cs:line 295
   at VidCoder.Services.OutputPathService.GenerateOutputFileName() in C:\git\VidCoder\VidCoder\Services\OutputPathService.cs:line 411
   at VidCoder.Services.PresetsService.NotifySelectedPresetChanged() in C:\git\VidCoder\VidCoder\Services\PresetsService.cs:line 782
   at VidCoder.Services.PresetsService.TryUpdateSelectedPreset(PresetViewModel value) in C:\git\VidCoder\VidCoder\Services\PresetsService.cs:line 296
   at VidCoder.Controls.PresetTreeViewContainer.<>c__DisplayClass6_0.<TreeView_OnSelectedItemChanged>b__0() in C:\git\VidCoder\VidCoder\Controls\PresetTreeViewContainer.xaml.cs:line 87
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler

**Comment by leninmejia39** [comment]
Crashes When Opening the settings  https://imgur.com/i3sA1kP

**Comment by leninmejia39** [comment]
https://ibb.co/Nr2vfdQ

**Comment by RandomEngy** [comment]
Figured it out. Initialization with hardware encoding support can sometimes fail due to bad drivers, and this is what's happening to you. Someone added some code to the HandBrake interop library that was trying to fallback to a no-hardware initialization, but they missed setting a flag, so it blows up at some other point that is checking for the "initialized" flag. I have a PR out to fix:

https://github.com/HandBrake/HandBrake/pull/3508

I'll include the fix in the next VidCoder beta.

**Comment by RandomEngy** [comment]
Should be fixed in 6.31 Beta.

**Comment by leninmejia39** [comment]
yes thankyou
