### ISSUE TITLE
Vidcoder 6.31 Beta: Unexpected error

### ISSUE THREAD

**Issue by D4i4932** [RandomEngy/VidCoder#821]
I don't get the error every time, but upon cancelling an encode, I get a message saying an unexpected error has occured.

System.ArgumentException: index cannot be greater than the size of the collection
   at DynamicData.ChangeAwareList`1.Insert(Int32 index, T item) in D:\a\DynamicData\DynamicData\src\DynamicData\List\ChangeAwareList.cs:line 290
   at VidCoder.Services.ProcessingService.<>c__DisplayClass215_0.<OnEncodeCompleted>b__2(IExtendedList`1 encodeQueueInnerList) in C:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 2235
   at DynamicData.List.Internal.ReaderWriter`1.Write(Action`1 updateAction) in D:\a\DynamicData\DynamicData\src\DynamicData\List\Internal\ReaderWriter.cs:line 74
   at DynamicData.SourceList`1.Edit(Action`1 updateAction) in D:\a\DynamicData\DynamicData\src\DynamicData\List\SourceList.cs:line 128
   at VidCoder.Services.ProcessingService.<>c__DisplayClass215_0.<OnEncodeCompleted>b__0() in C:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 2232
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Thanks for the report. This will be fixed in the next Beta release.

**Comment by RandomEngy** [comment]
Fixed in 6.32 Beta.
