### ISSUE TITLE
VidCoder 6.31 Beta Exception thrown

### ISSUE THREAD

**Issue by enginewaves** [RandomEngy/VidCoder#825]
Hello, not sure on exact steps as it happened few days ago but to be sure did save exception message locally.

Roughly i was in "**Options**" window -> "**Process**" -> adjusting **_Worker _process priority_ ** and **_Max simultaneous jobs_**. Not sure have i clicked "**OK**" immediately after or navigated to other section(s) (**Advanced**, **Updates**)...

**EDIT** Heh reading error looks it's something to do with **_Worker process priority_**.

``
System.InvalidOperationException: Cannot process request because the process (9728) has exited.
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass value)
   at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value)
   at VidCoder.RemoteProxyBase`2.<>c__DisplayClass41_0.<<PrepareWorkerProcessAsync>b__2>d.MoveNext() in C:\git\VidCoder\VidCoder\Services\HandBrakeProxy\RemoteProxyBase.cs:line 433
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
``

**Comment by RandomEngy** [comment]
Thanks for the report. I'll have this fixed in the next Beta release.

**Comment by RandomEngy** [comment]
Fixed in 6.32 Beta.
