### ISSUE TITLE
6.36 Beta: Picker: Changing "Output folder" crashes the application

### ISSUE THREAD

**Issue by virtualdreams** [RandomEngy/VidCoder#879]
**Describe the bug**
Try to change to the output folder in picker dialog from a preset. Select the new folder and the application crashes with the exception below.
Copy the preset to a new name also crashes the application.
Needed to change the path in sqlite3 database manually.

**To Reproduce**
1. Go to 'Picker' and
2. Click on 'Browse' to select the output folder and press 'Select folder'.
3. See error

**Expected behavior**
The new folder is selected without any crash.

**Screenshots**
![VidCoder_ODa7ZM7GtW](https://user-images.githubusercontent.com/3603832/132351141-487b75fa-06d2-45f1-b569-dc6b6587918c.png)

**Exception**
```
ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
 ---> System.ArgumentException: Object of type 'System.Collections.Generic.KeyValuePair`2[System.String,System.Object]' cannot be converted to type 'System.String'.
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at VidCoderCommon.Utilities.Injection.CloneInjection.GetClone(PropertyInfo sourceProperty, Object val) in C:\git\VidCoder\VidCoderCommon\Utilities\Injection\CloneInjection.cs:line 80
   at VidCoderCommon.Utilities.Injection.CloneInjection.Execute(PropertyInfo sourceProperty, Object source, Object target) in C:\git\VidCoder\VidCoderCommon\Utilities\Injection\CloneInjection.cs:line 40
   at Omu.ValueInjecter.Injections.PropertyInjection.Inject(Object source, Object target)
   at Omu.ValueInjecter.Injections.ValueInjection.Map(Object source, Object target)
   at Omu.ValueInjecter.StaticValueInjecter.InjectFrom[T](Object target, Object source)
   at VidCoder.ViewModel.PickerWindowViewModel.UpdatePickerProperty[T](String propertyName, T value, Boolean raisePropertyChanged) in C:\git\VidCoder\VidCoder\ViewModel\PickerWindowViewModel.cs:line 1374
   at VidCoder.ViewModel.PickerWindowViewModel.<.ctor>b__7_63(String directoryOverride) in C:\git\VidCoder\VidCoder\ViewModel\PickerWindowViewModel.cs:line 325
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54
   at System.Reactive.Linq.ObservableImpl.Skip`1.Count._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Skip.cs:line 53
   at System.Reactive.Linq.ObservableImpl.Switch`1._.InnerObserver.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Switch.cs:line 104
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 145
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.EnumerableSelector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 1375
   at System.Reactive.Linq.ObservableImpl.Buffer`2.Boundaries._.BufferClosingObserver.OnNext(TBufferClosing value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Buffer.cs:line 829
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 240
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 145
   at ReactiveUI.IReactiveObjectExtensions.ExtensionState`1.NotifyObservable[T](TSender rxObj, T item, ISubject`1 subject) in D:\a\ReactiveUI\ReactiveUI\src\ReactiveUI\ReactiveObject\IReactiveObjectExtensions.cs:line 430
   at ReactiveUI.IReactiveObjectExtensions.ExtensionState`1.RaisePropertyChanged(String propertyName) in D:\a\ReactiveUI\ReactiveUI\src\ReactiveUI\ReactiveObject\IReactiveObjectExtensions.cs:line 385
   at ReactiveUI.IReactiveObjectExtensions.RaiseAndSetIfChanged[TObj,TRet](TObj reactiveObject, TRet& backingField, TRet newValue, String propertyName) in D:\a\ReactiveUI\ReactiveUI\src\ReactiveUI\ReactiveObject\IReactiveObjectExtensions.cs:line 131
   at VidCoder.ViewModel.PickerWindowViewModel.set_OutputDirectory(String value) in C:\git\VidCoder\VidCoder\ViewModel\PickerWindowViewModel.cs:line 581
   at VidCoder.ViewModel.PickerWindowViewModel.<get_PickOutputDirectory>b__294_0() in C:\git\VidCoder\VidCoder\ViewModel\PickerWindowViewModel.cs:line 1161
   at ReactiveUI.ReactiveCommand.<>c__DisplayClass0_0.<Create>b__1(IObserver`1 observer) in D:\a\ReactiveUI\ReactiveUI\src\ReactiveUI\ReactiveCommand\ReactiveCommand.cs:line 109
   at System.Reactive.Linq.QueryLanguage.CreateWithDisposableObservable`1.SubscribeCore(IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/Linq/QueryLanguage.Creation.cs:line 35
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer) in /_/Rx.NET/Source/src/System.Reactive/ObservableBase.cs:line 58
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass10_0.<.cctor>b__2() in D:\a\ReactiveUI\ReactiveUI\src\ReactiveUI\RxApp.cs:line 106
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at System.Reactive.Concurrency.DispatcherScheduler.<>c__DisplayClass12_0`1.<Schedule>b__0() in /_/Rx.NET/Source/src/System.Reactive/Platforms/Desktop/Concurrency/DispatcherScheduler.cs:line 98
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by RandomEngy** [comment]
Sorry you ran into this. I think it might be having trouble cloning the ExtensionData part of the Picker. If you're still running into this crash, could you send me your .sqlite file so I can reproduce the issue?

**Comment by virtualdreams** [comment]
VidCoder.sqlite in attachment. Problem still exists.

[VidCoder.zip](https://github.com/RandomEngy/VidCoder/files/7309675/VidCoder.zip)

**Comment by RandomEngy** [comment]
Okay I manually cleaned it so it should work for you now. I'll also make an update to automatically clean it for everyone else.

[VidCoder.zip](https://github.com/RandomEngy/VidCoder/files/7312302/VidCoder.zip)

**Comment by RandomEngy** [comment]
Okay, the next version should have code to auto-fix this issue.

I see how you got into the state and it shouldn't happen in the future; it was a transient issue when upgrading to a specific database version without cleanup code.
