### ISSUE TITLE
vidcoder crash report

### ISSUE THREAD

**Issue by bobbobbin** [RandomEngy/VidCoder#883]
System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.RegularExpressions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Text.RegularExpressions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at VidCoder.FileCleanup.CleanHandBrakeTempFiles()
   at VidCoder.ViewModel.MainViewModel.OnClosing()
   at VidCoder.Services.Windows.WindowManager.OnClosing(Window window, Boolean userInitiated)
   at VidCoder.Services.Windows.WindowManager.OnClosingHandler(Object sender, CancelEventArgs e)
   at System.Windows.Window.WmClose()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
I'll explicitly add System.Text.RegularExpressions as a NuGet dependency to see if that solves it. Will be in the next Beta release.

**Comment by RandomEngy** [comment]
Should be fixed in 6.37 Beta.
