### ISSUE TITLE
Reason of this crash??

### ISSUE THREAD

**Issue by Kill3rWolf** [RandomEngy/VidCoder#886]
System.IO.FileNotFoundException: Could not load file or assembly 'WinCopies.WindowsAPICodePack.Shell, Version=2.1.1.0, Culture=neutral, PublicKeyToken=a5d06180d9f8fba2'. The system cannot find the file specified.
File name: 'WinCopies.WindowsAPICodePack.Shell, Version=2.1.1.0, Culture=neutral, PublicKeyToken=a5d06180d9f8fba2'
   at VidCoder.Services.ProcessingService.<>c__DisplayClass216_0.<OnEncodeCompleted>b__0()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Kill3rWolf** [comment]
System.AggregateException: One or more errors occurred. (System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at VidCoder.DispatchUtilities.Invoke(Action action) in C:\git\VidCoder\VidCoder\Utilities\DispatchUtilities.cs:line 16
   at VidCoder.View.Main.EnsureVisible() in C:\git\VidCoder\VidCoder\View\Main.xaml.cs:line 310
   at VidCoder.Automation.VidCoderAutomation.BringToForeground() in C:\git\VidCoder\VidCoder\Automation\VidCoderAutomation.cs:line 79
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at PipeMethodCalls.RequestHandler`1.GetTypedResponseForRequest(SerializedPipeRequest request))
 ---> PipeMethodCalls.PipeInvokeFailedException: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at VidCoder.DispatchUtilities.Invoke(Action action) in C:\git\VidCoder\VidCoder\Utilities\DispatchUtilities.cs:line 16
   at VidCoder.View.Main.EnsureVisible() in C:\git\VidCoder\VidCoder\View\Main.xaml.cs:line 310
   at VidCoder.Automation.VidCoderAutomation.BringToForeground() in C:\git\VidCoder\VidCoder\Automation\VidCoderAutomation.cs:line 79
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at PipeMethodCalls.RequestHandler`1.GetTypedResponseForRequest(SerializedPipeRequest request)
   at PipeMethodCalls.MethodInvoker`1.InvokeAsync(Expression`1 expression, CancellationToken cancellationToken)
   at VidCoderCommon.Services.AutomationClient.TryActionAsync(Expression`1 action) in C:\git\VidCoder\VidCoderCommon\Services\AutomationClient.cs:line 46
   at VidCoderCommon.Services.AutomationClient.RunActionAsync(Expression`1 action) in C:\git\VidCoder\VidCoderCommon\Services\AutomationClient.cs:line 19
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at VidCoder.App.OnStartup(StartupEventArgs e) in C:\git\VidCoder\VidCoder\App.xaml.cs:line 69
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
What version of Windows are you running? Installer or portable? It's a bit confusing because I include WinCopies.WindowsAPICodePack.Shell.dll with both.

**Comment by RandomEngy** [comment]
Can you go to %temp%\RarSFX0 while VidCoder is running and tell me if you see `WinCopies.WindowsAPICodePack.Shell.dll` there? When does this exception happen for you?

**Comment by Kill3rWolf** [comment]
@RandomEngy Okay, give me some time. I switch to Handbrake, cause I don't wanna hamper my encoding. But in deeply, missing Vidcoder features so much! I'll inform you of my next video encoding.

Please wait until then...

**Comment by RandomEngy** [comment]
Let me know if this happens with the installer version as well.
