### ISSUE TITLE
NullReferenceException on startup

### ISSUE THREAD

**Issue by RandomEngy** [RandomEngy/VidCoder#889]
System.AggregateException: One or more errors occurred. (System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at VidCoder.DispatchUtilities.Invoke(Action action) in C:\git\VidCoder\VidCoder\Utilities\DispatchUtilities.cs:line 16
   at VidCoder.View.Main.EnsureVisible() in C:\git\VidCoder\VidCoder\View\Main.xaml.cs:line 310
   at VidCoder.Automation.VidCoderAutomation.BringToForeground() in C:\git\VidCoder\VidCoder\Automation\VidCoderAutomation.cs:line 79
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at PipeMethodCalls.RequestHandler`1.GetTypedResponseForRequest(SerializedPipeRequest request))
 ---> PipeMethodCalls.PipeInvokeFailedException: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at VidCoder.DispatchUtilities.Invoke(Action action) in C:\git\VidCoder\VidCoder\Utilities\DispatchUtilities.cs:line 16
   at VidCoder.View.Main.EnsureVisible() in C:\git\VidCoder\VidCoder\View\Main.xaml.cs:line 310
   at VidCoder.Automation.VidCoderAutomation.BringToForeground() in C:\git\VidCoder\VidCoder\Automation\VidCoderAutomation.cs:line 79
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at PipeMethodCalls.RequestHandler`1.GetTypedResponseForRequest(SerializedPipeRequest request)
   at PipeMethodCalls.MethodInvoker`1.InvokeAsync(Expression`1 expression, CancellationToken cancellationToken)
   at VidCoderCommon.Services.AutomationClient.TryActionAsync(Expression`1 action) in C:\git\VidCoder\VidCoderCommon\Services\AutomationClient.cs:line 46
   at VidCoderCommon.Services.AutomationClient.RunActionAsync(Expression`1 action) in C:\git\VidCoder\VidCoderCommon\Services\AutomationClient.cs:line 19
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at VidCoder.App.OnStartup(StartupEventArgs e) in C:\git\VidCoder\VidCoder\App.xaml.cs:line 69
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

_Originally posted by @Kill3rWolf in https://github.com/RandomEngy/VidCoder/issues/886#issuecomment-927131164_

**Comment by RandomEngy** [comment]
It seems like that probably happened on startup, when it was trying to bring an already existing instance of VidCoder to the foreground. Except that Application.Current at that point was null, maybe because it wasn't started up yet or was being torn down. Do you remember if you had just started up another instance of VidCoder, or had just closed another one? When you tried to launch VidCoder again, did it work?

**Comment by Kill3rWolf** [comment]
I don't know your other question's answers, But I can answer the last question.

When you tried to launch VidCoder again, did it work?

- No, it failed with an error/warning message so many times. Then I gave up. But the same downloaded beta .exe file working again.

After my ongoing encoding video was destroyed, it was not opening.

**Comment by RandomEngy** [comment]
So was this what happened?

1) Video was encoding, but failed with an error. Either it crashed or you closed VidCoder.
2) You try to launch VidCoder and it crashes with this exception.

Trying to figure it out because it looks like there may have been a zombie VidCoder process running. If this ever happens again, check to see if there is a VidCoder.exe process running in the Task Manager. You should be able to kill it and be able to launch again.

**Comment by RandomEngy** [comment]
I've got a fix ready that will detect the zombie instance and kill it before proceeding to launch. Hopefully that will make it so you don't get into this situation again.

**Comment by RandomEngy** [comment]
Should be fixed in 6.37 Beta.
