### ISSUE TITLE
Ping exception with invalid ID

### ISSUE THREAD

**Issue by RandomEngy** [RandomEngy/VidCoder#890]
[17:21:51] sync: "Chapter 15" (15) at frame 93074 time 349372773
[18:40:05] sync: "Chapter 16" (16) at frame 99593 time 373843470
ERROR: Operation 'Ping' failed: System.IO.IOException: Cannot invoke method. Pipe has faulted.
---> System.InvalidOperationException: No pending call found for ID 19795504267264
at PipeMethodCalls.MethodInvoker1.HandleResponse(SerializedPipeResponse response) at PipeMethodCalls.PipeStreamWrapper.ProcessMessageAsync(CancellationToken cancellationToken) at PipeMethodCalls.PipeMessageProcessor.StartProcessing(PipeStreamWrapper pipeStreamWrapper) --- End of inner exception stack trace --- at PipeMethodCalls.Utilities.EnsureReadyForInvoke(PipeState state, Exception pipeFault) at PipeMethodCalls.MethodInvoker1.InvokeAsync[TResult](Expression1 expression, CancellationToken cancellationToken) at VidCoder.RemoteProxyBase2.<>c__DisplayClass41_0.<b__1>d.MoveNext() in C:\git\VidCoder\VidCoder\Services\HandBrakeProxy\RemoteProxyBase.cs:line 426
ERROR: Encode failed with code ErrorProcessCommunication
Could not clean up failed file 'H:\Movie\English Movie.1080p.BluRay.10Bit.DD5.1-Kill3rWolf.part.mkv'.
System.IO.IOException: The process cannot access the file 'H:\Movie\English Movie.1080p.BluRay.10Bit.DD5.1-Kill3rWolf.part.mkv' because it is being used by another process.
at System.IO.FileSystem.DeleteFile(String fullPath)
at System.IO.FileInfo.Delete()
at VidCoder.Services.ProcessingService.TryHandleFailedFile(FileInfo directOutputFileInfo, IAppLogger encodeLogger, String reason, String finalOutputPath) in C:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 2486
Job completed (Elapsed Time: 19h 34m)

Spend 19hrs,65% encode & my encoding failed...not only with this new beta portable version, happened with previous beta version!

_Originally posted by @Kill3rWolf in https://github.com/RandomEngy/VidCoder/issues/886#issuecomment-927928927_

**Comment by RandomEngy** [comment]
Looks like there was some corruption on the pipe and it read the response ID in the wrong place. One potential workaround is to go to Global Options -> Process and uncheck "Use worker process to encode".

How often did you see this failure? Did it always happen at the same point or was it random?

**Comment by RandomEngy** [comment]
Also, are you running any antivirus?

**Comment by Kill3rWolf** [comment]
> Also, are you running any antivirus?

No, I mean no 3rd party antivirus software. Only Windows Security, but real-time protection always stays disabled to reduce CPU & Memory usages.

> I got it, thanks. It looks like you have an identical set of DLLs there, but for some reason, it couldn't find it on your PC. I'm a bit stumped on this. It even works in the Windows 10 VM that I made without the .NET 5 runtime installed. Does the installer version work for you?

I'll let you know later.
