### ISSUE TITLE
Missing System.Text.RegularExpressions DLL on close

### ISSUE THREAD

**Issue by ThomasCSR** [RandomEngy/VidCoder#903]
System.IO.FileNotFoundException: Could not load file or assembly 'System.Text.RegularExpressions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. Den angivne fil blev ikke fundet.
File name: 'System.Text.RegularExpressions, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at VidCoder.FileCleanup.CleanHandBrakeTempFiles()
   at VidCoder.ViewModel.MainViewModel.OnClosing()
   at VidCoder.Services.Windows.WindowManager.OnClosing(Window window, Boolean userInitiated)
   at VidCoder.Services.Windows.WindowManager.OnClosingHandler(Object sender, CancelEventArgs e)
   at System.Windows.Window.OnClosing(CancelEventArgs e)
   at System.Windows.Window.WmClose()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Are you using the installer version or the portable version?

**Comment by ThomasCSR** [comment]
I'm using the installer version

**Comment by RandomEngy** [comment]
Thanks... does this happen every time you exit? They changed how assembly loading is logged in .NET 5 so I'll need to do some research to be able to debug this properly.

**Comment by RandomEngy** [comment]
I think it might be crashing only when the process was unexpectedly killed and was not able to clean up the temporary HandBrake files from last time. I think this might be a way to reproduce the crash:

1. Download and launch [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer).
2. Load up a source in VidCoder.
3. In Process Explorer, right click VidCoder and click "Kill Process".
4. Re-launch VidCoder.
5. Close VidCoder.

If the crash is happening reliably, then I have a way to get some more logs about what's going on.

1. Set up the crash scenario by doing steps 1-3 above.
2. Go to the `C:\Program Files\VidCoder` folder .
3. Shift + Right click and choose "Open in Windows Terminal"
![image](https://user-images.githubusercontent.com/9450861/141687800-34ddbc9e-9691-4e65-942c-8ab1def5f570.png)
OR press Win+X, I to open powershell and enter `cd "C:\Program Files\VidCoder"` .
4. Enter `$Env:COREHOST_TRACEFILE = $Env:appdata + "\VidCoder\trace.txt"` To set the trace file location.
5. Enter `$Env:COREHOST_TRACE = 1` . At this point the terminal window is ready to launch with tracing enabled.
6. Enter `.\VidCoder.exe` to launch VidCoder.
7. Close VidCoder. You should get the crash dialog here.
8. If you got the crash to happen the trace.txt log should be at `%appdata%\VidCoder\trace.txt`. If you could put that in pastebin or share it somehow I should be able to see what was happening when it failed to find `System.Text.RegularExpressions.dll`.

**Comment by RandomEngy** [comment]
Should be fixed in 7.2 Beta.
