### ISSUE TITLE
Encoding Fails when Windows is "Switch User"

### ISSUE THREAD

**Issue by xCryptic** [RandomEngy/VidCoder#91]
While I'm away from my computer, I don't like to keep it logged in. I'll switch user so it will require my password to login again, while everything still runs. When I do that, VidCoder fails with the following error:

```
## VidCoder 1.5.34.0 (x64)
# Starting job 4/7
#   Title: 1
#   Range: All
# Worker ready: Service state is Opened on pipe VidCoderWorker.4ffe1d7a-b47c-44fb-9d94-4eb6e7823409
# Connecting to process 3656 on pipe VidCoderWorker.4ffe1d7a-b47c-44fb-9d94-4eb6e7823409
[19:26:54] hb_init: starting libhb thread
[19:26:54] CPU: 
[19:26:54]  - logical processor count: 4
# Lost communication with worker process: System.TimeoutException: This request operation sent to net.pipe://localhost/VidCoderWorker.4ffe1d7a-b47c-44fb-9d94-4eb6e7823409 did not receive a reply within the configured timeout (00:00:09.9989999).  The time allotted to this operation may have been a portion of a longer timeout.  This may be because the service is still processing the operation or because the service was unable to send a reply message.  Please consider increasing the operation timeout (by casting the channel/proxy to IContextChannel and setting the OperationTimeout property) and ensure that the service is able to connect to the client.

Server stack trace: 
   at System.ServiceModel.Dispatcher.DuplexChannelBinder.SyncDuplexRequest.WaitForReply(TimeSpan timeout)
   at System.ServiceModel.Dispatcher.DuplexChannelBinder.Request(Message message, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   at System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   at VidCoderWorker.IHandBrakeEncoder.StartEncode(EncodeJob job, Boolean preview, Int32 previewNumber, Int32 previewSeconds, Double overallSelectedLengthSeconds, Int32 verbosity, Int32 previewCount, Boolean useDvdNav)
   at VidCoder.RemoteEncodeProxy.<>c__DisplayClass7.<>c__DisplayClassa.<StartEncode>b__5() in d:\docs\projects\VidCoder\VidCoder\Services\EncodeProxy\RemoteEncodeProxy.cs:line 128
   at VidCoder.RemoteEncodeProxy.ExecuteProxyOperation(Action action) in d:\docs\projects\VidCoder\VidCoder\Services\EncodeProxy\RemoteEncodeProxy.cs:line 367
# Encode failed.
# Job completed (Elapsed Time: 10s)
```

**Comment by RandomEngy** [comment]
Have you tried pressing Windows+L to lock your computer?

**Comment by RandomEngy** [comment]
A second option would be to go to Options -> Advanced and uncheck "Use worker process to encode".

**Comment by xCryptic** [comment]
>Have you tried pressing Windows+L to lock your computer?

Oh. Why have I not been using Lock all this time lol. I just tested it, and it seems to work, thanks.
