### ISSUE TITLE
Crash Using "Add Multi Files to Que"

### ISSUE THREAD

**Issue by SouthCentralTexas** [RandomEngy/VidCoder#920]
VidCoder 6.42 Installer
System.InvalidOperationException: Title must be selected.
   at VidCoder.ViewModel.MainViewModel.get_EncodeJob() in C:\git\VidCoder\VidCoder\ViewModel\MainViewModel.cs:line 3099
   at VidCoder.ViewModel.QueueTitlesWindowViewModel.<.ctor>b__2_8(Object sender, NotifyCollectionChangedEventArgs args) in C:\git\VidCoder\VidCoder\ViewModel\QueueTitlesWindowViewModel.cs:line 81
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.RemoveItem(Int32 index)
   at System.Collections.ObjectModel.Collection`1.RemoveAt(Int32 index)
   at VidCoder.TwoListSynchronizer.RemoveItems(IList list, NotifyCollectionChangedEventArgs e, Converter`2 converter) in C:\git\VidCoder\VidCoder\Utilities\ListSynchronizer\TwoListSynchronizer.cs:line 204
   at VidCoder.TwoListSynchronizer.PerformActionOnAllLists(ChangeListAction action, IList sourceList, NotifyCollectionChangedEventArgs collectionChangedArgs) in C:\git\VidCoder\VidCoder\Utilities\ListSynchronizer\TwoListSynchronizer.cs:line 181
   at VidCoder.TwoListSynchronizer.HandleCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e) in C:\git\VidCoder\VidCoder\Utilities\ListSynchronizer\TwoListSynchronizer.cs:line 158
   at VidCoder.TwoListSynchronizer.ReceiveWeakEvent(Type managerType, Object sender, EventArgs e) in C:\git\VidCoder\VidCoder\Utilities\ListSynchronizer\TwoListSynchronizer.cs:line 87
   at System.Windows.WeakEventManager.ListenerList.DeliverEvent(Listener& listener, Object sender, EventArgs args, Type managerType)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   at System.Collections.Specialized.CollectionChangedEventManager.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.RemoveItem(Int32 index)
   at System.Windows.Controls.SelectedItemCollection.RemoveItem(Int32 index)
   at System.Collections.ObjectModel.Collection`1.RemoveAt(Int32 index)
   at System.Windows.Controls.Primitives.Selector.UpdateSelectedItems(InternalSelectedItemsStorage toAdd, InternalSelectedItemsStorage toRemove)
   at System.Windows.Controls.Primitives.Selector.UpdateSelectedItems()
   at System.Windows.Controls.Primitives.Selector.UpdatePublicSelectionProperties()
   at System.Windows.Controls.Primitives.Selector.SelectionChanger.End()
   at System.Windows.Controls.Primitives.Selector.OnItemsChanged(NotifyCollectionChangedEventArgs e)
   at System.Windows.Controls.ListView.OnItemsChanged(NotifyCollectionChangedEventArgs e)
   at System.Windows.Controls.ItemsControl.OnItemCollectionChanged2(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Controls.ItemCollection.OnViewCollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   at System.Windows.WeakEventManager.DeliverEvent(Object sender, EventArgs args)
   at System.Collections.Specialized.CollectionChangedEventManager.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.OnCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.ListCollectionView.RefreshOverride()
   at System.Windows.Data.CollectionView.RefreshInternal()
   at System.Windows.Data.CollectionView.RefreshOrDefer()
   at System.Windows.Data.ListCollectionView.ProcessCollectionChanged(NotifyCollectionChangedEventArgs args)
   at System.Windows.Data.CollectionView.OnCollectionChanged(Object sender, NotifyCollectionChangedEventArgs args)
   at System.Collections.ObjectModel.ObservableCollection`1.OnCollectionChanged(NotifyCollectionChangedEventArgs e)
   at System.Collections.ObjectModel.ObservableCollection`1.ClearItems()
   at VidCoder.ViewModel.QueueTitlesWindowViewModel.RefreshTitles() in C:\git\VidCoder\VidCoder\ViewModel\QueueTitlesWindowViewModel.cs:line 273
   at VidCoder.ViewModel.QueueTitlesWindowViewModel.<.ctor>b__2_1(VideoSource _) in C:\git\VidCoder\VidCoder\ViewModel\QueueTitlesWindowViewModel.cs:line 47
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 54
   at System.Reactive.Linq.ObservableImpl.Skip`1.Count._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Skip.cs:line 53
   at System.Reactive.Linq.ObservableImpl.Switch`1._.InnerObserver.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Switch.cs:line 104
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 149
   at System.Reactive.Linq.ObservableImpl.SelectMany`2.EnumerableSelector._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/SelectMany.cs:line 1379
   at System.Reactive.Linq.ObservableImpl.Buffer`2.Boundaries._.BufferClosingObserver.OnNext(TBufferClosing value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Buffer.cs:line 829
   at System.Reactive.Linq.ObservableImpl.Merge`1.Observables._.InnerObserver.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Merge.cs:line 240
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 149
   at ReactiveUI.IReactiveObjectExtensions.ExtensionState`1.NotifyObservable[T](TSender rxObj, T item, ISubject`1 subject) in D:\a\ReactiveUI\ReactiveUI\src\ReactiveUI\ReactiveObject\IReactiveObjectExtensions.cs:line 430
   at ReactiveUI.IReactiveObjectExtensions.ExtensionState`1.RaisePropertyChanged(String propertyName) in D:\a\ReactiveUI\ReactiveUI\src\ReactiveUI\ReactiveObject\IReactiveObjectExtensions.cs:line 385
   at ReactiveUI.IReactiveObjectExtensions.RaiseAndSetIfChanged[TObj,TRet](TObj reactiveObject, TRet& backingField, TRet newValue, String propertyName) in D:\a\ReactiveUI\ReactiveUI\src\ReactiveUI\ReactiveObject\IReactiveObjectExtensions.cs:line 121
   at VidCoder.ViewModel.MainViewModel.StartScan(String path, EncodeJobViewModel jobVM) in C:\git\VidCoder\VidCoder\ViewModel\MainViewModel.cs:line 3399
   at VidCoder.ViewModel.MainViewModel.SetSourceFromFolder(String videoFolder) in C:\git\VidCoder\VidCoder\ViewModel\MainViewModel.cs:line 834
   at VidCoder.ViewModel.MainViewModel.SetSource(String sourcePath) in C:\git\VidCoder\VidCoder\ViewModel\MainViewModel.cs:line 866
   at VidCoder.ViewModel.MainViewModel.<>c__DisplayClass34_0.<HandlePaths>b__0() in C:\git\VidCoder\VidCoder\ViewModel\MainViewModel.cs:line 508
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by SouthCentralTexas** [comment]
OpSys Windows 10 Pro Ver 10.0.19042 Build 19042 with AMD FX-8370 & 32 GB RAM
Simultaneously running pgms RedFox AnyDVD-HD & Elby CloneDVD2

**Comment by RandomEngy** [comment]
Why did you close this? Is it no longer an issue?

**Comment by SouthCentralTexas** [comment]
No, it is still an issue.  Did not realize I closed it.  Joined Github for this issue and this was my first post.  There is an option to "Reopen and comment".  Perhaps this will correct the issue status.

**Comment by RandomEngy** [comment]
Ahh, okay. I added a couple of checks that should prevent that crash from happening in the future. Will be fixed in the next release.

**Comment by SouthCentralTexas** [comment]
Thank you for the attention.  There is an option below, "Close with comment" which I'm going to select.  Please advise if this is not the proper action.

**Comment by RandomEngy** [comment]
Fixed in 6.43.
