### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by sasoriza** [RandomEngy/VidCoder#926]
Getting this error on launch:

VidCoder 6.42 Installer
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: Failed initializing notifications
 ---> System.UnauthorizedAccessException: Zugriff verweigert (0x80070005 (E_ACCESSDENIED))
   at Microsoft.Toolkit.Uwp.Notifications.IApplicationResolver.GetAppIDForProcess(UInt32 dwProcessID, String& ppszAppID, Boolean& pfPinningPrevented, Boolean& pfExplicitAppID, Boolean& pfEmbeddedShortcutValid)
   at Microsoft.Toolkit.Uwp.Notifications.Win32AppInfo.Get()
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.Initialize()
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Toolkit.Uwp.Notifications.ToastNotificationManagerCompat.get_History()
   at lambda_method4(Closure , IResolverContext )
   at DryIoc.Factory.<>c__DisplayClass26_1.<ApplyReuse>b__2()
   at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder)
   at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder)
   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request)
   at DryIoc.Factory.GetExpressionOrDefault(Request request)
   at DryIoc.Factory.GetDelegateOrDefault(Request request)
   at DryIoc.Container.ResolveAndCacheDefaultFactoryDelegate(Type serviceType, IfUnresolved ifUnresolved)
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved)
   at DryIoc.Resolver.Resolve[TService](IResolver resolver, IfUnresolved ifUnresolved)
   at Microsoft.AnyContainer.DryIoc.DryIocAnyContainer.Resolve[T]()
   at Microsoft.AnyContainer.StaticResolver.Resolve[T]()
   at VidCoder.Services.ProcessingService..ctor() in C:\git\VidCoder\VidCoder\Services\ProcessingService.cs:line 66
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at DryIoc.ReflectionFactory.<>c__DisplayClass21_0.<GetActivator>b__0()
   at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder)
   at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder)
   at DryIoc.ReflectionFactory.CreateServiceExpression(MemberInfo ctorOrMember, Expression factoryExpr, Expression[] paramExprs, Request request)
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request)
   at DryIoc.Factory.GetExpressionOrDefault(Request request)
   at DryIoc.Factory.GetDelegateOrDefault(Request request)
   at DryIoc.Container.ResolveAndCacheDefaultFactoryDelegate(Type serviceType, IfUnresolved ifUnresolved)
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved)
   at DryIoc.Resolver.Resolve[TService](IResolver resolver, IfUnresolved ifUnresolved)
   at Microsoft.AnyContainer.DryIoc.DryIocAnyContainer.Resolve[T]()
   at Microsoft.AnyContainer.StaticResolver.Resolve[T]()
   at VidCoder.ViewModel.MainViewModel..ctor() in C:\git\VidCoder\VidCoder\ViewModel\MainViewModel.cs:line 307
   at VidCoder.App.OnStartup(StartupEventArgs e) in C:\git\VidCoder\VidCoder\App.xaml.cs:line 170
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Thanks for the report. It should be fixed in the next release.

**Comment by RandomEngy** [comment]
Fixed in 6.43.
