### ISSUE TITLE
System.InvalidOperationException: Rats.

### ISSUE THREAD

**Issue by RandomEngy** [RandomEngy/VidCoder#928]
### What were you doing when VidCoder crashed?

Testing the new crash reporting feature

### Crash details

```text
VidCoder 1.0 Beta Installer
System.InvalidOperationException: Rats.
   at VidCoder.View.Main.<>c.<.ctor>b__13_7(Object sender, RoutedEventArgs args) in C:\git\VidCoder\VidCoder\View\Main.xaml.cs:line 199
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by RandomEngy** [comment]
It works!
