### ISSUE TITLE
problems with vidcoder 1.5.34

### ISSUE THREAD

**Issue by lucabis** [RandomEngy/VidCoder#95]
It is from a few days VidCoder , crashes.
This is the error :
System.Data.SQLite.SQLiteException (0x80004005): Insertion failed because the database is full
database or disk is full
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at VidCoder.Model.DatabaseConfig.SetConfigValue(String configName, String configValue, SQLiteConnection connection) in d:\docs\projects\VidCoder\VidCoder\Model\DatabaseConfig.cs:line 137
   at VidCoder.ViewModel.MainViewModel.<>c__DisplayClass6d.<StartScan>b__6c() in d:\docs\projects\VidCoder\VidCoder\ViewModel\MainViewModel.cs:line 2482
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)

how do I fix ?
Thank you

**Comment by RandomEngy** [comment]
Can you check how much free space you have on your system drive?

**Comment by lucabis** [comment]
on the system disk around 100MB , secondary drive where I perform encodings 70 gb

**Comment by RandomEngy** [comment]
100MB sounds quite low and it seems likely you ran out of space and it couldn't write to VidCoder's internal storage on the system disk.
