### ISSUE TITLE
System.ComponentModel.Win32Exception: An error occurred trying to start process 'C:\Program Files\VidCoder\unins000.exe' with working directory 'C:\Users\ambro\AppData\Local\Temp\RarSFX0'. Impossibile trovare il file specificato.

### ISSUE THREAD

**Issue by AndyLessinia** [RandomEngy/VidCoder#981]
### What were you doing when VidCoder crashed?

I was trying to open the portable version of vidcoder.

### Crash details

```text
VidCoder 7.10 Portable
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Program Files\VidCoder\unins000.exe' with working directory 'C:\Users\ambro\AppData\Local\Temp\RarSFX0'. Impossibile trovare il file specificato.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at VidCoder.App.OnStartup(StartupEventArgs e) in C:\git\VidCoder\VidCoder\App.xaml.cs:line 142
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by RandomEngy** [comment]
Should be fixed with v7.11.
