### ISSUE TITLE
System.ComponentModel.Win32Exception: An error occurred trying to start process 'C:\Program Files\VidCoder\unins000.exe' with working directory 'C:\Users\ambro\AppData\Local\VidCoder.Stable\app-7.10.0'. Impossibile trovare il file specificato.

### ISSUE THREAD

**Issue by AndyLessinia** [RandomEngy/VidCoder#982]
### What were you doing when VidCoder crashed?

I was trying to install vidcoder 7.10, the programs was deleting old files.

### Crash details

```text
VidCoder 7.10 SquirrelInstaller
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'C:\Program Files\VidCoder\unins000.exe' with working directory 'C:\Users\ambro\AppData\Local\VidCoder.Stable\app-7.10.0'. Impossibile trovare il file specificato.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at VidCoder.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by RandomEngy** [comment]
Sorry about that. Should be fixed with v7.11.
