### ISSUE TITLE
Vidcoder fail to launch System.TypeInitializationException

### ISSUE THREAD

**Issue by FunkyZero** [RandomEngy/VidCoder#99]
Windows 7 x64 OS, Handbrake 0.10.5.0 x64.  I've tried 1.5.34 x64 portable and installer. Have also tried 2.30-Beta-x64-Portable with the same results. I think it may be environmental, but I have no idea how to troubleshoot this one. Any assistance you can offer would be greatly appreciated.
==========================

System.TypeInitializationException: The type initializer for 'VidCoder.Model.Database' threw an exception. ---> System.Data.SQLite.SQLiteException: SQLite error
no such table: settings
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at VidCoder.Model.DatabaseConfig.GetConfigStringRaw(String configName, SQLiteConnection connection) in d:\docs\projects\VidCoder\VidCoder\Model\DatabaseConfig.cs:line 72
   at VidCoder.Model.DatabaseConfig.get_Version() in d:\docs\projects\VidCoder\VidCoder\Model\DatabaseConfig.cs:line 20
   at VidCoder.Model.Database..cctor() in d:\docs\projects\VidCoder\VidCoder\Model\Database.cs:line 33
   --- End of inner exception stack trace ---
   at VidCoder.Model.Database.get_Connection()
   at VidCoder.App.OnStartup(StartupEventArgs e) in d:\docs\projects\VidCoder\VidCoder\App.xaml.cs:line 69
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by RandomEngy** [comment]
Hmm, this kind of exception would normally mean a corrupt %appdata%\VidCoder\VidCoder.sqlite, though you say it happens on both the Beta and Stable which seems to mean that your system can't make the database correctly.

You could try deleting or renaming the sqlite files in the VidCoder and VidCoder-Beta folders though given your case that may not work. Not sure what to do beyond that.

**Comment by FunkyZero** [comment]
Just an update (not that it is in any way useful) but I completely scrubbed the machine and re-installed Win7 x64 again (the problem was occurring on a fresh install too so go figure...) and now it is working. I can't begin to guess what was causing it, but it's working now.
